# Generated by Django 3.2.12 on 2022-06-27 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0004_auto_20220627_0328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempcheckoutline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scg_checkout.product"
            ),
        ),
    ]
