# Generated by Django 3.2.13 on 2022-07-02 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scg_checkout", "0006_auto_20220627_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempcheckout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
