# Generated by Django 3.2.13 on 2022-07-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0007_tempcheckout_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempcheckoutline",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scg_checkout.temporder",
            ),
        ),
        migrations.AddField(
            model_name="temporder",
            name="status",
            field=models.CharField(default="confirmed", max_length=255),
        ),
    ]
