# Generated by Django 3.2.13 on 2022-07-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0008_auto_20220704_0939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporder",
            name="bill_to",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporder",
            name="order_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporder",
            name="po_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporder",
            name="po_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporder",
            name="request_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporder",
            name="ship_to",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="net_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.temporder",
            ),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="plant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.product",
            ),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="request_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.productvariant",
            ),
        ),
    ]
