# Generated by Django 3.2.13 on 2022-07-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0010_alter_temporder_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempcheckoutline",
            name="order",
        ),
        migrations.AddField(
            model_name="temporderline",
            name="checkout_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scg_checkout.tempcheckoutline",
            ),
        ),
    ]
