# Generated by Django 3.2.13 on 2022-07-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0011_auto_20220705_0259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempcheckoutline",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="temporderline",
            name="quantity",
            field=models.FloatField(default=0),
        ),
    ]
