# Generated by Django 3.2.13 on 2022-07-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0012_auto_20220713_0737"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temporder",
            options={
                "permissions": (
                    ("manage_domestic_orders", "Manage SCGP domestic orders."),
                )
            },
        ),
    ]
