# Generated by Django 3.2.13 on 2022-08-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0013_alter_temporder_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temporderline",
            options={"ordering": ("id",)},
        ),
    ]
