# Generated by Django 3.2.13 on 2022-08-22 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scg_checkout", "0015_salesorganization_business_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScgSoldTo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address_text", models.TextField(blank=True, null=True)),
                (
                    "representatives",
                    models.ManyToManyField(
                        blank=True, related_name="sold_to", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
