# Generated by Django 3.2.13 on 2022-08-31 03:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0017_alternatedmaterial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternatedmaterial",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="alternatedmaterial",
            name="material_os",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternated_material_os_material",
                to="scg_checkout.product",
            ),
        ),
        migrations.AddField(
            model_name="alternatedmaterial",
            name="material_own",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternated_material_own_material",
                to="scg_checkout.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="priority",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="sales_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.salesorganization",
            ),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="sold_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.scgsoldto",
            ),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="alternatedmaterial",
            unique_together={
                ("sales_organization", "sold_to", "material_own", "priority")
            },
        ),
        migrations.RemoveField(
            model_name="alternatedmaterial",
            name="alternated_material",
        ),
        migrations.RemoveField(
            model_name="alternatedmaterial",
            name="original_material",
        ),
    ]
