# Generated by Django 3.2.13 on 2022-08-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0019_auto_20220831_0827"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesgroup",
            name="sales_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_organization",
                to="scg_checkout.salesorganization",
            ),
        ),
        migrations.AddField(
            model_name="temporder",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scg_sold_to",
                to="scg_checkout.scgsoldto",
            ),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="confirmed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="item_no",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="type",
            field=models.CharField(
                blank=True, default="domestic", max_length=255, null=True
            ),
        ),
    ]
