# Generated by Django 3.2.13 on 2022-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0024_auto_20220901_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dia",
            field=models.TextField(blank=True, null=True),
        ),
    ]
