# Generated by Django 3.2.13 on 2022-09-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0025_product_dia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternativematerial",
            name="dia",
        ),
        migrations.RemoveField(
            model_name="alternativematerial",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="alternativematerial",
            name="gram",
        ),
    ]
