# Generated by Django 3.2.13 on 2022-09-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0026_auto_20220905_0709"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="grade_gram",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
