# Generated by Django 3.2.13 on 2022-09-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0027_alternatedmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatedmaterial",
            name="error_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
