# Generated by Django 3.2.13 on 2022-09-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0027_product_grade_gram"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporderline",
            name="overdue_1",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="overdue_2",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
