# Generated by Django 3.2.13 on 2022-09-07 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scg_checkout", "0028_alternatedmaterial_error_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2022-02-05"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="temporder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="temporder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
