# Generated by Django 3.2.13 on 2022-09-07 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scg_checkout", "0029_auto_20220907_0430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="update_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
