# Generated by Django 3.2.13 on 2022-09-08 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0029_auto_20220907_0514"),
    ]

    operations = [
        migrations.AddField(
            model_name="scgsoldto",
            name="sale_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.salesorganization",
            ),
        ),
    ]
