# Generated by Django 3.2.13 on 2022-09-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0029_auto_20220907_0514"),
        ("scg_checkout", "0031_auto_20220907_0536"),
    ]

    operations = []
