# Generated by Django 3.2.13 on 2022-09-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0030_scgsoldto_sale_organization"),
        ("scg_checkout", "0032_merge_0029_auto_20220907_0514_0031_auto_20220907_0536"),
    ]

    operations = []
