# Generated by Django 3.2.13 on 2022-09-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0033_merge_20220908_0603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativematerialos",
            options={
                "ordering": [
                    "alternative_material__sales_organization__code",
                    "alternative_material__sold_to__code",
                    "alternative_material__sold_to__name",
                ]
            },
        ),
    ]
