# Generated by Django 3.2.13 on 2022-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0035_alter_alternativematerialos_material_os"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScgOrderView",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("id", models.IntegerField()),
                (
                    "contract_pi_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(max_length=255)),
                ("sold_to", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "scg_union_orders",
                "managed": False,
            },
        )
    ]
