# Generated by Django 3.2.13 on 2022-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0036_scgorderview"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporderline",
            name="flag",
            field=models.CharField(blank=True, default="Customer", max_length=255),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
