# Generated by Django 3.2.13 on 2022-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0037_auto_20220916_0641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporderline",
            name="flag",
            field=models.CharField(
                blank=True, default="Customer", max_length=255, null=True
            ),
        ),
    ]
