# Generated by Django 3.2.13 on 2022-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0038_alter_temporderline_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporderline",
            name="attention_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
