# Generated by Django 3.2.13 on 2022-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0039_temporderline_attention_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporder",
            name="so_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="actual_gi_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="delivery",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="dtp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="dtr",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="gi_status",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="temporderline",
            name="original_request_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
