# Generated by Django 3.2.13 on 2022-09-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0040_auto_20220917_1053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temporder",
            options={},
        ),
    ]
