# Generated by Django 3.2.13 on 2022-09-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0015_soldtomaster_sold_to_name"),
        ("sap_migration", "0021_auto_20220926_1822"),
        ("scg_checkout", "0041_alter_temporder_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativematerialos",
            options={
                "ordering": [
                    "alternative_material__sales_organization__code",
                    "alternative_material__sold_to__sold_to_code",
                    "alternative_material__sold_to__sold_to_name",
                ]
            },
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="new_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_os",
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="old_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_own",
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AlterField(
            model_name="alternatedmaterial",
            name="order_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alternated_material",
                to="sap_migration.orderlines",
            ),
        ),
        migrations.AlterField(
            model_name="alternativematerial",
            name="material_own",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_material_own",
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AlterField(
            model_name="alternativematerial",
            name="sold_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.soldtomaster",
            ),
        ),
        migrations.AlterField(
            model_name="alternativematerialos",
            name="material_os",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.materialmaster",
            ),
        ),
    ]
