# Generated by Django 3.2.13 on 2022-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0043_auto_20221003_0918"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatedmaterial",
            name="quantity_change_of_roll",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alternatedmaterial",
            name="quantity_change_of_ton",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
