# Generated by Django 3.2.13 on 2023-07-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0120_alternatematerialosmappingfilelog"),
        ("scg_checkout", "0044_auto_20221007_0416"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatedmaterial",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alternated_material_order",
                to="sap_migration.order",
            ),
        ),
    ]
