PMT_MAT_SEARCH_API_SUCCESS_RESPONSE = {
    "message": "Success",
    "statusCode": 200,
    "result": [
        {
            "materialNo": "Z033219642",
            "factoryCode": "254B",
            "partNo": "0436-105-00",
            "pc": "0436-105-00G3",
            "hierarchy": "03SO9999993851",
            "saleOrg": "0254",
            "plant": "254B",
            "custCode": "PRACH",
            "cusId": "1001318",
            "custName": "บริษัท ผลไม้กระป๋องประจวบ จำกัด",
            "description": "PRACH 6/A10_ ROYALTY 10 T5 -00",
            "saleText": "กล่องกระดาษ 6/A10_ ROYALTY 10 T5 ",
            "indGrp": "TCQ",
            "indDes": "TCQ Canned Pineapple",
            "materialType": "81",
            "printMethod": "Solid 1 สี",
            "flute": "B",
            "board": "KA185/CS110/KI185",
            "wid": 312,
            "leg": 468,
            "hig": 175,
            "boxType": "RSC ไม่มีหูจับ",
            "joinType": "กาวเครื่อง",
            "cutSheetLeng": 1607,
            "cutSheetWid": 496,
            "bun": 20,
            "bunLayer": 4,
            "layerPalet": 17,
            "boxPalet": 1360,
            "weightBox": 0.406,
            "saleUom": "PC",
            "bomUom": "ST",
            "palletSize": "1.00x1.20",
            "lastUpdate": "2023-01-03T13:57:31",
            "purTxt": "",
            "highGroup": "CT",
            "highValue": "0087",
            "pdisStatus": "C",
            "validityStartFrom": "2023-01-04T00:00:00",
            "validityEndDate": "9999-12-31T00:00:00",
            "rate": 17.95,
            "currencyKey": "THB",
            "vendorName": None,
            "netPrice": None,
            "unitOfNetPrice": None,
            "sourceListValidFrom": None,
            "sourceListValidTo": None,
            "remark": None,
            "nonmove": None,
            "nonMoveMonth": None,
            "stockWIP": None,
            "stockFG": None,
            "stockQA": None,
            "hold": None,
            "pieceSet": 1,
            "holdRemark": None,
            "custInvType": None,
            "cipInvType": None,
            "blockNo": None,
            "plateNo": None,
        }
    ],
}

PMT_MAT_SEARCH_API_FAILURE_RESPONSE = {
    "message": "Forbidden",
    "statusCode": 403,
    "result": {"errorMessage": "Object reference not set to an instance of an object."},
}
