# Generated by Django 3.2.13 on 2022-07-19 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scg_checkout", "0013_alter_temporder_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.FloatField(blank=True, null=True)),
                ("tax_amount", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("status", models.CharField(default="draft", max_length=255)),
                ("request_delivery_date", models.DateField(blank=True, null=True)),
                ("order_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ship_to", models.CharField(blank=True, max_length=255, null=True)),
                ("bill_to", models.CharField(blank=True, max_length=255, null=True)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("request_date", models.DateField(blank=True, null=True)),
                ("ref_pi_no", models.CharField(blank=True, max_length=50, null=True)),
                ("net_price", models.CharField(blank=True, max_length=50, null=True)),
                ("doc_currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "payment_term",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("incoterm", models.CharField(blank=True, max_length=10, null=True)),
                ("usage", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unloading_point",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "place_of_delivery",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "port_of_discharge",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "port_of_loading",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "no_of_containers",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("shipping_mark", models.TextField(blank=True, null=True)),
                ("uom", models.CharField(blank=True, max_length=10, null=True)),
                ("gw_uom", models.CharField(blank=True, max_length=10, null=True)),
                ("etd", models.CharField(blank=True, max_length=50, null=True)),
                ("eta", models.CharField(blank=True, max_length=50, null=True)),
                ("dlc_expiry_date", models.DateField(blank=True, null=True)),
                ("dlc_no", models.CharField(blank=True, max_length=50, null=True)),
                ("dlc_latest_delivery_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("payer", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "end_customer",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "sales_employee",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("author", models.CharField(blank=True, max_length=128, null=True)),
                ("payment_instruction", models.TextField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("production_information", models.TextField(blank=True, null=True)),
                (
                    "internal_comment_to_warehouse",
                    models.TextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distribution_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scg_checkout.distributionchannel",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scg_checkout.division",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("manage_export_orders", "Manage SCGP export orders."),
                ),
            },
        ),
        migrations.CreateModel(
            name="ExportPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("po_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sold_to_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "ship_to_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "ship_to_country",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("incoterm", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "payment_term",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExportSoldTo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExportPIProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_quantity", models.FloatField()),
                ("remaining_quantity", models.FloatField()),
                ("price_per_unit", models.FloatField()),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("weight", models.FloatField()),
                ("weight_unit", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_export.exportpi",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_export.exportproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exportpi",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scgp_export.exportsoldto",
            ),
        ),
        migrations.CreateModel(
            name="ExportOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("weight", models.FloatField()),
                ("weight_unit", models.CharField(blank=True, max_length=12, null=True)),
                ("vat_percent", models.FloatField()),
                ("item_cat_eo", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("ref_pi_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "condition_group1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "material_group2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("commission_percent", models.FloatField()),
                ("commission_amount", models.FloatField()),
                (
                    "commission_unit",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("request_date", models.DateField(blank=True, null=True)),
                ("plant", models.CharField(blank=True, max_length=10, null=True)),
                ("route", models.CharField(blank=True, max_length=50, null=True)),
                ("roll_quantity", models.FloatField()),
                ("roll_diameter", models.FloatField()),
                ("roll_core_diameter", models.FloatField()),
                ("roll_per_pallet", models.FloatField()),
                ("package_quantity", models.FloatField()),
                ("pallet_size", models.CharField(blank=True, max_length=12, null=True)),
                ("pallet_no", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "packing_list",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "shipping_point",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("delivery_tol_under", models.FloatField()),
                ("delivery_tol_over", models.FloatField()),
                ("delivery_tol_unlimited", models.BooleanField(default=False)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_export.exportorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_export.exportpiproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exportorder",
            name="pi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scgp_export.exportpi",
            ),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="sale_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.salesorganization",
            ),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="sales_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.salesoffice",
            ),
        ),
        migrations.CreateModel(
            name="ExportCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_export.exportcart",
                    ),
                ),
                (
                    "pi_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_export.exportpiproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exportcart",
            name="pi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scgp_export.exportpi"
            ),
        ),
        migrations.AddField(
            model_name="exportcart",
            name="sold_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_export.exportsoldto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exportcart",
            unique_together={("pi", "created_by")},
        ),
    ]
