# Generated by Django 3.2.13 on 2022-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0002_auto_20220726_0424"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="po_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="delivery_tol_over",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="delivery_tol_under",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="package_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="roll_core_diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="roll_diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="roll_per_pallet",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="roll_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="exportorder",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="exportorder",
            name="currency",
        ),
    ]
