# Generated by Django 3.2.13 on 2022-07-31 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0004_exportorderline_net_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorderline",
            name="export_cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_export.exportcartitem",
            ),
        ),
    ]
