# Generated by Django 3.2.13 on 2022-08-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0005_exportorderline_export_cart_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportorderline",
            name="export_cart_item",
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scgp_export.exportcartitem",
            ),
        ),
    ]
