# Generated by Django 3.2.13 on 2022-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0006_auto_20220802_0734"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exportorder",
            options={
                "ordering": ("id",),
                "permissions": (
                    ("manage_export_orders", "Manage SCGP export orders."),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="exportorderline",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="item_no",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
