# Generated by Django 3.2.13 on 2022-08-04 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0008_alter_exportorderline_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportcartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="scgp_export.exportcart",
            ),
        ),
    ]
