# Generated by Django 3.2.13 on 2022-08-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0009_alter_exportcartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportcartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scgp_export.exportcart"
            ),
        ),
    ]
