# Generated by Django 3.2.13 on 2022-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0010_alter_exportcartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportcart",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
