# Generated by Django 3.2.13 on 2022-08-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0011_exportcart_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorderline",
            name="confirmed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
