# Generated by Django 3.2.13 on 2022-08-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0011_exportcart_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="eo_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
