# Generated by Django 3.2.13 on 2022-08-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0015_salesorganization_business_unit"),
        ("scgp_export", "0012_exportorder_eo_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="status_sap",
            field=models.CharField(default="Being Process", max_length=255),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="sales_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_organizations",
                to="scg_checkout.salesorganization",
            ),
        ),
    ]
