# Generated by Django 3.2.13 on 2022-08-19 11:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0013_alter_exportorderline_confirmed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportorderline",
            name="confirmed_date",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
    ]
