# Generated by Django 3.2.13 on 2022-08-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0013_auto_20220819_0746"),
        ("scgp_export", "0014_alter_exportorderline_confirmed_date"),
    ]

    operations = []
