# Generated by Django 3.2.13 on 2022-08-22 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scgp_export", "0016_alter_exportorderline_confirmed_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exportcart",
            unique_together={("pi", "created_by", "sold_to")},
        ),
    ]
