# Generated by Django 3.2.13 on 2022-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0017_alter_exportcart_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="order_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="type",
            field=models.CharField(
                blank=True, default="export", max_length=255, null=True
            ),
        ),
    ]
