# Generated by Django 3.2.13 on 2022-09-01 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_checkout", "0022_auto_20220901_0637"),
        ("scgp_export", "0018_auto_20220831_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="scgp_sales_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.scgpsalesemployee",
            ),
        ),
        migrations.AddField(
            model_name="exportproduct",
            name="material_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.scgpmaterialgroup",
            ),
        ),
    ]
