# Generated by Django 3.2.13 on 2022-09-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0023_auto_20220915_0957"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW scg_union_orders as
            SELECT
                CONCAT(sct.id, '-', 'domestic') as "unique_id",
                sct.id,
                CAST(scc2.id as varchar) as "contract_pi_no",
                sct.status,
                CASE
                    WHEN scs.code is null
                    THEN null
                    ELSE concat(scs.code, ' - ', scs.address_text)
                END as "sold_to" ,
                sct.created_by_id,
                sct.created_at,
                sct.updated_at,
                'domestic' as "type"
            FROM scg_checkout_temporder sct
            LEFT JOIN scg_checkout_scgsoldto scs ON sct.sold_to_id  = scs.id
            LEFT JOIN scg_checkout_temporderline sct2 on sct.id = sct2.order_id
            LEFT JOIN scg_checkout_contractproduct scc on sct2.contract_product_id = scc.id
            LEFT JOIN scg_checkout_contract scc2 on scc.contract_id = scc2.id
            GROUP BY sct.id, scc2.id, scs.address_text, scs.code
            UNION
            SELECT
                CONCAT(see.id, '-', 'export') as "unique_id",
                see.id,
                see2.code as "contract_pi_no",
                see.status,
                see2.sold_to_name as "sold_to",
                see.created_by_id,
                see.created_at,
                see.updated_at,
                'export' as "type"
            FROM scgp_export_exportorder see
            LEFT JOIN scgp_export_exportpi see2 on see.pi_id = see2.id
            """
        ),
    ]
