# Generated by Django 3.2.13 on 2022-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0024_create_view_orders_union"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorderline",
            name="flag",
            field=models.CharField(blank=True, default="Customer", max_length=255),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="dlc_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="eta",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="etd",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="gw_uom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="no_of_containers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="payer",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="payment_term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="place_of_delivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="port_of_discharge",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="port_of_loading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="ref_pi_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="unloading_point",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="uom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorder",
            name="usage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="delivery_tol_under",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="ref_pi_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exportorderline",
            name="roll_quantity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
