# Generated by Django 3.2.13 on 2022-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0026_alter_exportorderline_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="etd_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="attention_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
