# Generated by Django 3.2.13 on 2022-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0027_auto_20220916_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportorder",
            name="cc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="change_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="contract_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="lot_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="pi_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorder",
            name="sales_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="eo_item_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="item_cat_pi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="no_of_package",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="no_of_rolls",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportorderline",
            name="price_currency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportproduct",
            name="grade_gram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportproduct",
            name="material_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
