# Generated by Django 3.2.13 on 2022-09-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0028_auto_20220917_1115"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exportorder",
            options={},
        ),
    ]
