# Generated by Django 3.2.13 on 2022-11-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_export", "0030_eouploadsendmailsummarylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="eouploadsendmailsummarylog",
            name="subject",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
