# Generated by Django 3.2.13 on 2022-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversion1Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("pac_ream", models.FloatField(blank=True, null=True)),
                ("ream_pal", models.FloatField(blank=True, null=True)),
                ("sh_pac", models.FloatField(blank=True, null=True)),
                ("pac_box", models.FloatField(blank=True, null=True)),
                ("box_pal", models.FloatField(blank=True, null=True)),
                ("msm_kg", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversion2Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("from_unit", models.CharField(blank=True, max_length=10, null=True)),
                ("from_value", models.FloatField(blank=True, null=True)),
                ("to_unit", models.CharField(blank=True, max_length=10, null=True)),
                ("to_value", models.FloatField(blank=True, null=True)),
                ("calculation", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversion3Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("action", models.CharField(blank=True, max_length=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=10, null=True)),
                ("factor", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerGroup1Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerGroup2Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerGroup3Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerGroup4Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerGroupMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DistributionChannelMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DivisionMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialClassificationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("grade", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "basis_weight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("roll_width", models.CharField(blank=True, max_length=50, null=True)),
                ("diameter", models.CharField(blank=True, max_length=50, null=True)),
                ("roll_length", models.CharField(blank=True, max_length=50, null=True)),
                ("core_size", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "description_th",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_type_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("base_unit", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "base_unit_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("delete_flag", models.CharField(blank=True, max_length=1, null=True)),
                ("net_weight", models.FloatField(blank=True, null=True)),
                ("gross_weight", models.FloatField(blank=True, null=True)),
                ("weight_unit", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrganizationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoldToMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "account_group_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "account_group_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_class",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_class_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "customer_block",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_block_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("delete_flag", models.CharField(blank=True, max_length=10, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoldToUnloadingPointMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "factory_calendar",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "factory_calendar_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unloading_point",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextIDMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoldToPartnerAddressMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "partner_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "address_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("name1", models.CharField(blank=True, max_length=255, null=True)),
                ("name2", models.CharField(blank=True, max_length=255, null=True)),
                ("name3", models.CharField(blank=True, max_length=255, null=True)),
                ("name4", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("postal", models.CharField(blank=True, max_length=10, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "street_sup1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_sup2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_sup3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transport_zone_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "transport_zone_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "telephone_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "telephone_extension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mobile_no", models.CharField(blank=True, max_length=50, null=True)),
                ("fax_no", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "unique_together": {("sold_to_code", "partner_code", "address_code")},
            },
        ),
        migrations.CreateModel(
            name="SoldToChannelPartnerMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distribution_channel_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "division_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "partner_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "partner_role",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("address_link", models.TextField(blank=True, null=True)),
            ],
            options={
                "unique_together": {
                    (
                        "sold_to_code",
                        "sales_organization_code",
                        "distribution_channel_code",
                        "division_code",
                        "partner_code",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="SoldToChannelMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distribution_channel_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "division_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "company_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sales_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sales_group_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_term",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "payment_term_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("taxkd", models.CharField(blank=True, max_length=10, null=True)),
                ("taxkd_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("incoterm1", models.CharField(blank=True, max_length=10, null=True)),
                ("incoterm2", models.CharField(blank=True, max_length=10, null=True)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "customer_block",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_block_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("delete_flag", models.CharField(blank=True, max_length=10, null=True)),
                ("del_plant", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "del_plant_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "currency_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "over_delivery_tol",
                    models.FloatField(blank=True, max_length=10, null=True),
                ),
                (
                    "under_delivery_tol",
                    models.FloatField(blank=True, max_length=10, null=True),
                ),
                ("unlimit_tol", models.CharField(blank=True, max_length=10, null=True)),
                ("price_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "price_group_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_group_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_group1_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_group2_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_group3_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_group4_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_group5_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text_id", models.CharField(blank=True, max_length=10, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("text_line", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "unique_together": {
                    (
                        "sold_to_code",
                        "sales_organization_code",
                        "distribution_channel_code",
                        "division_code",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="MaterialSaleMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distribution_channel_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sales_unit", models.CharField(blank=True, max_length=10, null=True)),
                ("tax_class1", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "tax_class1_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group1",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_group1_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_group2_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group3",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_group3_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group4",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_group4_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group5",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_group5_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "delivery_plant",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "delivery_plant_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prodh", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh1", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh1_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh2", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh2_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh3", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh3_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh4", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh4_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh5", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh5_desc", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh6", models.CharField(blank=True, max_length=50, null=True)),
                ("prodh6_desc", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "material_price_group",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_price_group_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "item_category_group",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "item_category_group_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sale_text1_th",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text2_th",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text3_th",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text4_th",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text1_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text2_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text3_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_text4_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "acct_asssmt_grp_mat",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "material_code",
                        "sales_organization_code",
                        "distribution_channel_code",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="MaterialPurchaseMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plant_code", models.CharField(blank=True, max_length=10, null=True)),
                ("plant_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "purchase_group",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "purchase_group_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("order_unit", models.CharField(blank=True, max_length=10, null=True)),
                ("auto_po", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "unique_together": {("material_code", "plant_code")},
            },
        ),
        migrations.CreateModel(
            name="MaterialPlantMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plant_code", models.CharField(blank=True, max_length=10, null=True)),
                ("sloc", models.CharField(blank=True, max_length=10, null=True)),
                ("sloc_desc", models.CharField(blank=True, max_length=255, null=True)),
                ("unit_issue", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "unique_together": {("material_code", "plant_code", "sloc")},
            },
        ),
    ]
