# Generated by Django 3.2.13 on 2022-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldToMaterialMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distribution_channel_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sold_to_material_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "sold_to_code",
                        "sales_organization_code",
                        "distribution_channel_code",
                        "sold_to_material_code",
                    )
                },
            },
        ),
    ]
