# Generated by Django 3.2.13 on 2022-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0003_auto_20220909_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion2master",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="SoldToExternalMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sold_to_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "partner_function",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "external_customer_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "unique_together": {("sold_to_code", "external_customer_code")},
            },
        ),
    ]
