# Generated by Django 3.2.13 on 2022-09-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0004_auto_20220909_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion1master",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="conversion2master",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="conversion3master",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="materialclassificationmaster",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="materialmaster",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="soldtomaster",
            name="sold_to_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="soldtounloadingpointmaster",
            name="sold_to_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
