# Generated by Django 3.2.13 on 2022-09-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0005_auto_20220909_1658"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soldtopartneraddressmaster",
            old_name="postal",
            new_name="postal_code",
        ),
        migrations.AlterField(
            model_name="soldtochannelmaster",
            name="incoterm2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
