# Generated by Django 3.2.13 on 2022-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0006_auto_20220910_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymaster",
            name="business_unit_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesorganizationmaster",
            name="business_unit_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
