# Generated by Django 3.2.13 on 2022-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0006_auto_20220910_1403"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soldtochannelmaster",
            name="language",
        ),
        migrations.RemoveField(
            model_name="soldtochannelmaster",
            name="text_id",
        ),
        migrations.RemoveField(
            model_name="soldtochannelmaster",
            name="text_line",
        ),
        migrations.CreateModel(
            name="SoldToTextMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distribution_channel_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "division_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("text_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "text_id_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("text_line", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "unique_together": {
                    (
                        "sold_to_code",
                        "sales_organization_code",
                        "distribution_channel_code",
                        "division_code",
                        "text_id",
                    )
                },
            },
        ),
    ]
