# Generated by Django 3.2.13 on 2022-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0007_auto_20220921_2222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldtotextmaster",
            name="text_line",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="soldtochannelpartnermaster",
            unique_together=set(),
        ),
    ]
