# Generated by Django 3.2.13 on 2022-09-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0007_auto_20220920_0832"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialmaster",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialmaster",
            name="sale_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
