# Generated by Django 3.2.13 on 2022-09-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0008_auto_20220920_0836"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materialmaster",
            old_name="sale_unit",
            new_name="sales_unit",
        ),
    ]
