# Generated by Django 3.2.13 on 2022-09-20 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_master_data", "0009_rename_sale_unit_materialmaster_sales_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldtomaster",
            name="user",
            field=models.ManyToManyField(
                related_name="master_sold_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
