# Generated by Django 3.2.13 on 2022-09-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_migration", "0006_contract"),
        ("sap_master_data", "0010_soldtomaster_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companymaster",
            name="business_unit_code",
        ),
        migrations.RemoveField(
            model_name="salesorganizationmaster",
            name="business_unit_code",
        ),
        migrations.AddField(
            model_name="companymaster",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.businessunits",
            ),
        ),
        migrations.AddField(
            model_name="companymaster",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="master_company", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="materialclassificationmaster",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AddField(
            model_name="salesorganizationmaster",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.businessunits",
            ),
        ),
        migrations.AddField(
            model_name="salesorganizationmaster",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                related_name="master_sales_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="soldtoexternalmaster",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.soldtomaster",
            ),
        ),
        migrations.AddField(
            model_name="soldtopartneraddressmaster",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.soldtomaster",
            ),
        ),
    ]
