# Generated by Django 3.2.13 on 2022-09-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0007_auto_20220921_2222"),
        ("sap_master_data", "0012_materialmaster_scgp_material_group"),
    ]

    operations = []
