# Generated by Django 3.2.13 on 2022-09-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0018_merge_20220922_0709"),
        ("sap_master_data", "0013_merge_20220922_0726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymaster",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_master",
                to="sap_migration.businessunits",
            ),
        ),
    ]
