# Generated by Django 3.2.13 on 2022-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0014_alter_companymaster_business_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldtomaster",
            name="sold_to_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
