# Generated by Django 3.2.13 on 2022-09-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0008_auto_20220926_0911"),
        ("sap_master_data", "0015_soldtomaster_sold_to_name"),
    ]

    operations = []
