# Generated by Django 3.2.13 on 2022-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0018_auto_20221011_0340"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributionchannelmaster",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
