# Generated by Django 3.2.13 on 2022-10-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0019_distributionchannelmaster_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_office_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_group_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_group_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoldToExternalSalesArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sales_organization_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distribution_channel_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "division_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoldToExternalSalesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sold_to_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_group_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sales_group_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
