# Generated by Django 3.2.13 on 2022-11-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sap_master_data",
            "0020_salesgroup_soldtoexternalsalesarea_soldtoexternalsalesgroup",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldtomaster",
            name="sold_to_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
