# Generated by Django 3.2.13 on 2022-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0021_alter_soldtomaster_sold_to_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialmaster",
            name="material_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
