# Generated by Django 3.2.13 on 2022-12-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0023_alter_conversion1master_material_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymaster",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
