# Generated by Django 3.2.13 on 2022-12-20 05:08

from django.db import migrations, models


def data_migrations(apps, schema_editor):
    Companymaster = apps.get_model("sap_master_data", "CompanyMaster")
    for company in Companymaster.objects.filter(code__in=["0750", "7540"]):
        company.short_name = "SIAM KRAFT" if company.code == "0750" else "THAI CANE"
        company.full_name = (
            "บริษัท สยามคราฟท์อุตสาหกรรม จำกัด"
            if company.code == "0750"
            else "บริษัท ไทยเคนเปเปอร์ จำกัด (มหาชน)"
        )
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0024_companymaster_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymaster",
            name="short_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(data_migrations),
    ]
