# Generated by Django 3.2.13 on 2022-12-20 06:46

from django.db import migrations, models


def data_migrations(apps, schema_editor):
    SalesOrganizationMaster = apps.get_model(
        "sap_master_data", "SalesOrganizationMaster"
    )
    for salesorg in SalesOrganizationMaster.objects.filter(code__in=["0750", "7540"]):
        salesorg.short_name = "SIAM KRAFT" if salesorg.code == "0750" else "THAI CANE"
        salesorg.full_name = (
            "บริษัท สยามคราฟท์อุตสาหกรรม จำกัด"
            if salesorg.code == "0750"
            else "บริษัท ไทยเคนเปเปอร์ จำกัด (มหาชน)"
        )
        salesorg.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0025_companymaster_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorganizationmaster",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesorganizationmaster",
            name="short_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(data_migrations),
    ]
