# Generated by Django 3.2.13 on 2023-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0027_conversion2master_sap_master__materia_2a2a28_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="materialsalemaster",
            index=models.Index(
                fields=["material_code"], name="sap_master__materia_b86eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialsalemaster",
            index=models.Index(
                fields=["material_group1"], name="sap_master__materia_15a2c9_idx"
            ),
        ),
    ]
