# Generated by Django 3.2.13 on 2023-06-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0028_auto_20230622_1104"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="distributionchannelmaster",
            index=models.Index(fields=["code"], name="sap_master__code_d450bc_idx"),
        ),
        migrations.AddIndex(
            model_name="distributionchannelmaster",
            index=models.Index(fields=["type"], name="sap_master__type_65a316_idx"),
        ),
        migrations.AddIndex(
            model_name="materialsalemaster",
            index=models.Index(
                fields=["distribution_channel_code"],
                name="sap_master__distrib_1276c4_idx",
            ),
        ),
    ]
