# Generated by Django 3.2.13 on 2023-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0029_auto_20230623_0642"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomMaterial",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("parent_material_code", models.CharField(max_length=50)),
                ("plant", models.CharField(max_length=50, null=True)),
                ("item_number", models.CharField(max_length=10)),
                ("material_code", models.CharField(max_length=50)),
                ("quantity", models.FloatField(null=True)),
                ("unit", models.CharField(max_length=10, null=True)),
                ("valid_from", models.DateField(null=True)),
                ("valid_to", models.DateField(null=True)),
                ("created_date", models.DateField(null=True)),
                ("created_by_id", models.IntegerField(null=True)),
                ("last_updated_date", models.DateField(null=True)),
                ("last_updated_by_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "sap_master_data_bom_material",
            },
        ),
    ]
