# Generated by Django 3.2.13 on 2024-06-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0032_auto_20231214_1439"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bommaterial",
            unique_together={("parent_material_code", "material_code")},
        ),
    ]
