import random

ES_08 = {
    "piMessageId": "001",
    "status": "success",
    "reason": "reason",
    "data": [
        {
            "customerId": "0001011664",
            "customerName": "จก. ไทยซุ่นเฮง คราฟท์",
            "name2": "Name 2",
            "name3": "Name 3",
            "name4": "Name 4",
            "city": "กรุงเทพฯ",
            "postcode": "10220",
            "district": "บางซื่อ",
            "street1": "เลขที่ 1 ปูนซีเมนต์ไทย 1",
            "street2": "Street 2",
            "street3": "Street 3",
            "street4": "Street 4",
            "street5": "Street 5",
            "transportZone": "ZATW000009",
            "transportZoneDesc": "คลองเตย",
            "country": "TH",
            "countryName": "Thailand",
            "partnerList": [
                {
                    "saleOrg": "saleOrg",
                    "distributionChannel": "10",
                    "division": "00",
                    "partnerFunction": "AG",
                    "partnerFunctionDes": "Sold-to party",
                    "partnerNo": "0001000353",
                    "partnerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                },
                {
                    "saleOrg": "saleOrg",
                    "distributionChannel": "10",
                    "division": "00",
                    "partnerFunction": "AG",
                    "partnerFunctionDes": "Sold-to party",
                    "partnerNo": "0001000353",
                    "partnerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                },
            ],
            "shipToBillTo": [
                {"shipTo": "0000000001", "saleOrg": "0001", "billTo": "0000000001"},
                {"shipTo": "0000000002", "saleOrg": "0002", "billTo": "0000000002"},
            ],
            "saleGroup": [
                {
                    "saleOrg": "0750",
                    "distributionChannel": "10",
                    "soldTo": "0001011664",
                    "saleEmp": 10081040,
                    "saleGroup": "753",
                },
                {
                    "saleOrg": "0750",
                    "distributionChannel": "10",
                    "soldTo": "0001011664",
                    "saleEmp": 10081040,
                    "saleGroup": "753",
                },
            ],
        },
        {
            "customerId": "0001011664",
            "customerName": "จก. ไทยซุ่นเฮง คราฟท์",
            "name2": "Name 2",
            "name3": "Name 3",
            "name4": "Name 4",
            "city": "กรุงเทพฯ",
            "postcode": "10220",
            "district": "บางซื่อ",
            "street1": "เลขที่ 1 ปูนซีเมนต์ไทย 1",
            "street2": "Street 2",
            "street3": "Street 3",
            "street4": "Street 4",
            "street5": "Street 5",
            "transportZone": "ZATW000009",
            "transportZoneDesc": "คลองเตย",
            "country": "TH",
            "countryName": "Thailand",
            "partnerList": [
                {
                    "saleOrg": "saleOrg",
                    "distributionChannel": "10",
                    "division": "00",
                    "partnerFunction": "AG",
                    "partnerFunctionDes": "Sold-to party",
                    "partnerNo": "0001000353",
                    "partnerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                },
                {
                    "saleOrg": "saleOrg",
                    "distributionChannel": "10",
                    "division": "00",
                    "partnerFunction": "AG",
                    "partnerFunctionDes": "Sold-to party",
                    "partnerNo": "0001000353",
                    "partnerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                },
            ],
            "shipToBillTo": [
                {"shipTo": "0000000001", "saleOrg": "0001", "billTo": "0000000001"},
                {"shipTo": "0000000001", "saleOrg": "0001", "billTo": "0000000001"},
            ],
            "saleGroup": [
                {
                    "saleOrg": "0750",
                    "distributionChannel": "10",
                    "soldTo": "0001011664",
                    "saleEmp": 10081040,
                    "saleGroup": "753",
                },
                {
                    "saleOrg": "0750",
                    "distributionChannel": "10",
                    "soldTo": "0001011664",
                    "saleEmp": 10081040,
                    "saleGroup": "753",
                },
            ],
        },
    ],
}

ES_10 = {
    "piMessageId": "SXD_9efdaa92e7ce11ecbb2000002feb8366",
    "status": "success",
    "reason": "reason",
    "data": [
        {
            "customerId": "0000000001",
            "customerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
            "creditControlArea": "0780",
            "creditLimit": 100000,
            "creditAccount": "0000000002",
            "creditLimitUsed": 100000,
            "receivables": 3456789.97,
            "specialLiabil": 0,
            "saleValue": 98765.99,
            "creditExposure": 110000.88,
            "secondReceivables": 0,
            "creditAvaiable": 1234457889.12,
            "currency": "THB",
            "creditBlockStatus": False,
            "creditRefData": [
                {
                    "creditAccount": "0000000001",
                    "customerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                    "creditControlArea": "0780",
                    "creditLimit": 100000,
                    "creditLimitUsed": 57.87,
                    "receivables": 3456789.97,
                    "specialLiabil": 0,
                    "saleValue": 98765.99,
                    "creditExposure": 110000.88,
                    "secondReceivables": 0,
                    "currency": "THB",
                    "creditBlockStatus": False,
                },
                {
                    "creditAccount": "0000000002",
                    "customerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                    "creditControlArea": "0780",
                    "creditLimit": 100000,
                    "creditLimitUsed": 57.87,
                    "receivables": 3456789.97,
                    "specialLiabil": 0,
                    "saleValue": 98765.99,
                    "creditExposure": 110000.88,
                    "secondReceivables": 0,
                    "currency": "THB",
                    "creditBlockStatus": False,
                },
            ],
        },
        {
            "customerId": "0000000002",
            "customerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
            "creditControlArea": "0780",
            "creditLimit": 100000,
            "creditAccount": "0000000002",
            "creditLimitUsed": 100000,
            "receivables": 3456789.97,
            "specialLiabil": 0,
            "saleValue": 98765.99,
            "creditExposure": 110000.88,
            "secondReceivables": 0,
            "creditAvaiable": 1234457889.12,
            "currency": "THB",
            "creditBlockStatus": False,
            "creditRefData": [
                {
                    "creditAccount": "0000000001",
                    "customerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                    "creditControlArea": "0780",
                    "creditLimit": 100000,
                    "creditLimitUsed": 57.87,
                    "receivables": 3456789.97,
                    "specialLiabil": 0,
                    "saleValue": 98765.99,
                    "creditExposure": 110000.88,
                    "secondReceivables": 0,
                    "currency": "THB",
                    "creditBlockStatus": False,
                },
                {
                    "creditAccount": "0000000002",
                    "customerName": "บริษัท อมรินทร์พริ้นติ้งแอนด์",
                    "creditControlArea": "0780",
                    "creditLimit": 100000,
                    "creditLimitUsed": 57.87,
                    "receivables": 3456789.97,
                    "specialLiabil": 0,
                    "saleValue": 98765.99,
                    "creditExposure": 110000.88,
                    "secondReceivables": 0,
                    "currency": "THB",
                    "creditBlockStatus": False,
                },
            ],
        },
    ],
}

ES_13 = {
    "piMessageId": "0",
    "status": "success",
    "data": [
        {
            "customerId": "0000000181",
            "contractNo": "0410089237",
            "company": "0750",
            "saleOrg": "0750",
            "projectName": "TEST SAP",
            "startDate": "15/09/2020",
            "endDate": "31/10/2020",
            "paymentCondition": "NT15",
            "paymentConditionName": "Credit 15 days after receive bill",
            "contractStatus": "Partially",
            "incoterm": "CFR",
            "shipToCode": "0000000181",
            "shipToName": "SCG CEMENT-BUILDING MATERIALS CO.,LTD.",
            "country": "TH",
            "prcGroup1": "K01",
        },
    ],
}

ES_14 = {
    "piMessageId": 5100000753,
    "status": "success",
    "data": [
        {
            "customerNo": "0000000821",
            "contractNo": "0410031429",
            "companyCode": "0750",
            "projectName": "TH_AGP_MAR17_4000002163",
            "validFrom": "27/02/2017",
            "validTo": "31/03/2017",
            "pymTermKey": "NT15",
            "pymTermDes": "Credit 15 days after receive bill",
            "saleOrg": "0750",
            "distributionChannel": "10",
            "division": "00",
            "saleOffice": "0750",
            "saleGroup": "75K",
            "soldTo": "0000000821",
            "shipTo": "0001024593",
            "shipToName": "บจก. เอเซียยิปซั่มโปรดักส์",
            "payer": "0000000821",
            "billTo": "0000000821",
            "salesEmployee": "10013496",
            "author": "90010057",
            "incoterms1": "EXW",
            "incoterms2": "วังศาลา",
            "poNo": "4000002163",
            "country": "TH",
            "contractItem": [
                {
                    "itemNo": "000010",
                    "matNo": "Z02GFT170D127084DB",
                    "matDescription": "GFT 170D-1270 D184 C4 DB",
                    "targetQty": 50,
                    "salesUnit": "TON",
                    "plant": "7581",
                    "itemCategory": "ZKMN",
                    "paymentTerm": "NT15",
                    "matGroup1": "K09",
                },
                {
                    "itemNo": "000020",
                    "matNo": "Z02GFT170D127084DB",
                    "matDescription": "GFT 170D-1270 D184 C4 DB",
                    "targetQty": 50,
                    "salesUnit": "TON",
                    "plant": "7551",
                    "itemCategory": "ZKMN",
                    "paymentTerm": "NT15",
                    "matGroup1": "K09",
                },
                {
                    "itemNo": "000030",
                    "matNo": "Z02GB-160D117584EB",
                    "matDescription": "GB 160D-1175 D184 C4 EB",
                    "targetQty": 50,
                    "salesUnit": "TON",
                    "plant": "7551",
                    "itemCategory": "ZKMN",
                    "paymentTerm": "NT15",
                    "matGroup1": "K09",
                },
                {
                    "itemNo": "000040",
                    "matNo": "Z02GB-160D119584EB",
                    "matDescription": "GB 160D-1195 D184 C4 EB",
                    "targetQty": 50,
                    "salesUnit": "TON",
                    "plant": "7581",
                    "itemCategory": "ZKMN",
                    "paymentTerm": "NT15",
                    "matGroup1": "K09",
                },
                {
                    "itemNo": "000050",
                    "matNo": "Z02GB-160D119584EB",
                    "matDescription": "GB 160D-1195 D184 C4 EB",
                    "targetQty": 50,
                    "salesUnit": "TON",
                    "plant": "7551",
                    "itemCategory": "ZKMN",
                    "paymentTerm": "NT15",
                    "matGroup1": "K09",
                },
                {
                    "itemNo": "000060",
                    "matNo": "Z02GB-160D117584EB",
                    "matDescription": "GB 160D-1175 D184 C4 EB",
                    "targetQty": 50,
                    "salesUnit": "TON",
                    "plant": "7581",
                    "itemCategory": "ZKMN",
                    "paymentTerm": "NT15",
                    "matGroup1": "K09",
                },
            ],
            "conditionList": [
                {
                    "itemNo": "000010",
                    "conditionStepNo": "010",
                    "conditionCount": "01",
                    "conditionType": "ZPR1",
                    "conditionRate": "27000.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1350000.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "090",
                    "conditionCount": "01",
                    "conditionType": "ZKD2",
                    "conditionRate": "-7518.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-375900.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "718",
                    "conditionCount": "01",
                    "conditionType": "ZKD8",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "719",
                    "conditionCount": "01",
                    "conditionType": "ZKD9",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "720",
                    "conditionCount": "01",
                    "conditionType": "ZN00",
                    "conditionRate": "19482.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "974100.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "722",
                    "conditionCount": "01",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50000.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "745",
                    "conditionCount": "01",
                    "conditionType": "MWST",
                    "conditionRate": "7.0",
                    "conditionValue": "68187.0",
                    "conditionBaseValue": "974100.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "800",
                    "conditionCount": "01",
                    "conditionType": "YKD1",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "810",
                    "conditionCount": "01",
                    "conditionType": "YKD2",
                    "conditionRate": "-7518.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-375900.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "820",
                    "conditionCount": "01",
                    "conditionType": "YKD3",
                },
                {
                    "itemNo": "000010",
                    "conditionStepNo": "830",
                    "conditionCount": "01",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "010",
                    "conditionCount": "01",
                    "conditionType": "ZPR1",
                    "conditionRate": "27000.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1350000.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "090",
                    "conditionCount": "01",
                    "conditionType": "ZKD2",
                    "conditionRate": "-7518.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-375900.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "718",
                    "conditionCount": "01",
                    "conditionType": "ZKD8",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "719",
                    "conditionCount": "01",
                    "conditionType": "ZKD9",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "720",
                    "conditionCount": "01",
                    "conditionType": "ZN00",
                    "conditionRate": "19482.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "974100.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "722",
                    "conditionCount": "01",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50000.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "745",
                    "conditionCount": "01",
                    "conditionType": "MWST",
                    "conditionRate": "7.0",
                    "conditionValue": "68187.0",
                    "conditionBaseValue": "974100.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "800",
                    "conditionCount": "01",
                    "conditionType": "YKD1",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "810",
                    "conditionCount": "01",
                    "conditionType": "YKD2",
                    "conditionRate": "-7518.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-375900.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "820",
                    "conditionCount": "01",
                    "conditionType": "YKD3",
                },
                {
                    "itemNo": "000020",
                    "conditionStepNo": "830",
                    "conditionCount": "01",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "010",
                    "conditionCount": "01",
                    "conditionType": "ZPR1",
                    "conditionRate": "24000.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1200000.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "090",
                    "conditionCount": "01",
                    "conditionType": "ZKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "718",
                    "conditionCount": "01",
                    "conditionType": "ZKD8",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "719",
                    "conditionCount": "01",
                    "conditionType": "ZKD9",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "720",
                    "conditionCount": "01",
                    "conditionType": "ZN00",
                    "conditionRate": "20055.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1002750.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "722",
                    "conditionCount": "01",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50000.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "745",
                    "conditionCount": "01",
                    "conditionType": "MWST",
                    "conditionRate": "7.0",
                    "conditionValue": "70192.5",
                    "conditionBaseValue": "1002750.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "800",
                    "conditionCount": "01",
                    "conditionType": "YKD1",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "810",
                    "conditionCount": "01",
                    "conditionType": "YKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "820",
                    "conditionCount": "01",
                    "conditionType": "YKD3",
                },
                {
                    "itemNo": "000030",
                    "conditionStepNo": "830",
                    "conditionCount": "01",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "010",
                    "conditionCount": "01",
                    "conditionType": "ZPR1",
                    "conditionRate": "24000.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1200000.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "090",
                    "conditionCount": "01",
                    "conditionType": "ZKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "718",
                    "conditionCount": "01",
                    "conditionType": "ZKD8",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "719",
                    "conditionCount": "01",
                    "conditionType": "ZKD9",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "720",
                    "conditionCount": "01",
                    "conditionType": "ZN00",
                    "conditionRate": "20055.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1002750.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "722",
                    "conditionCount": "01",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50000.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "745",
                    "conditionCount": "01",
                    "conditionType": "MWST",
                    "conditionRate": "7.0",
                    "conditionValue": "70192.5",
                    "conditionBaseValue": "1002750.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "800",
                    "conditionCount": "01",
                    "conditionType": "YKD1",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "810",
                    "conditionCount": "01",
                    "conditionType": "YKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "820",
                    "conditionCount": "01",
                    "conditionType": "YKD3",
                },
                {
                    "itemNo": "000040",
                    "conditionStepNo": "830",
                    "conditionCount": "01",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "010",
                    "conditionCount": "01",
                    "conditionType": "ZPR1",
                    "conditionRate": "24000.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1200000.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "090",
                    "conditionCount": "01",
                    "conditionType": "ZKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "718",
                    "conditionCount": "01",
                    "conditionType": "ZKD8",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "719",
                    "conditionCount": "01",
                    "conditionType": "ZKD9",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "720",
                    "conditionCount": "01",
                    "conditionType": "ZN00",
                    "conditionRate": "20055.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1002750.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "722",
                    "conditionCount": "01",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50000.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "745",
                    "conditionCount": "01",
                    "conditionType": "MWST",
                    "conditionRate": "7.0",
                    "conditionValue": "70192.5",
                    "conditionBaseValue": "1002750.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "800",
                    "conditionCount": "01",
                    "conditionType": "YKD1",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "810",
                    "conditionCount": "01",
                    "conditionType": "YKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "820",
                    "conditionCount": "01",
                    "conditionType": "YKD3",
                },
                {
                    "itemNo": "000050",
                    "conditionStepNo": "830",
                    "conditionCount": "01",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "010",
                    "conditionCount": "01",
                    "conditionType": "ZPR1",
                    "conditionRate": "24000.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1200000.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "090",
                    "conditionCount": "01",
                    "conditionType": "ZKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "718",
                    "conditionCount": "01",
                    "conditionType": "ZKD8",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "719",
                    "conditionCount": "01",
                    "conditionType": "ZKD9",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "720",
                    "conditionCount": "01",
                    "conditionType": "ZN00",
                    "conditionRate": "20055.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "1002750.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "722",
                    "conditionCount": "01",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionBaseValue": "50000.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "745",
                    "conditionCount": "01",
                    "conditionType": "MWST",
                    "conditionRate": "7.0",
                    "conditionValue": "70192.5",
                    "conditionBaseValue": "1002750.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "800",
                    "conditionCount": "01",
                    "conditionType": "YKD1",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "810",
                    "conditionCount": "01",
                    "conditionType": "YKD2",
                    "conditionRate": "-3945.0",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                    "conditionValue": "-197250.0",
                    "conditionBaseValue": "50.0",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "820",
                    "conditionCount": "01",
                    "conditionType": "YKD3",
                },
                {
                    "itemNo": "000060",
                    "conditionStepNo": "830",
                    "conditionCount": "01",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPricingUnit": "1",
                },
            ],
            "orderText": [
                {
                    "textId": "Z014",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "ANY THAILAND PORTS AT THE SELLER'S OPTION"}
                    ],
                },
                {
                    "textId": "Z015",
                    "lang": "E",
                    "headerTextList": [
                        {
                            "headerText": "PACKING: GOODS ARE IN STANDARD EXPORT PACKING FCL/FCL CONT."
                        }
                    ],
                },
                {
                    "textId": "Z016",
                    "lang": 2,
                    "headerTextList": [{"headerText": "TH_AGP_MAR17_4000002163"}],
                },
                {
                    "textId": "Z056",
                    "lang": 2,
                    "headerTextList": [
                        {"headerText": "บริษัทสยามคราฟท์อุตสาหกรรม จำกัด"},
                        {"headerText": "1 ถ.ปูนซิเมนต์ไทย บางซื่อ"},
                        {"headerText": "กทม. 10800"},
                        {"headerText": "SIAM KRAFT INDUSTRY CO., LTD."},
                        {"headerText": "1 SIAM CEMENT ROAD BANGSUE"},
                        {"headerText": "BANGKOK 10800 THAILAND"},
                    ],
                },
                {
                    "textId": "ZK01",
                    "lang": 2,
                    "headerTextList": [{"headerText": "แก้วเก้า  แก้วกังวาล"}],
                },
                {
                    "textId": "ZK33",
                    "lang": 2,
                    "headerTextList": [{"headerText": "All"}],
                },
                {
                    "itemNo": "000010",
                    "textId": "0001",
                    "lang": 2,
                    "headerTextList": [
                        {"headerText": "กระดาษยิปซั่มด้านหน้า"},
                        {"headerText": "GFT 170D-1270 D184 C4 DB"},
                        {"headerText": "กระดาษยิปซั่มด้านหน้า"},
                        {"headerText": "GFT 170D-1270 D184 C4 DB"},
                    ],
                },
                {
                    "itemNo": "000010",
                    "textId": "Z012",
                    "lang": "E",
                    "headerTextList": [{"headerText": "TPC"}],
                },
                {
                    "itemNo": "000010",
                    "textId": "Z017",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "@        REAMS  X         PALLETS"},
                        {"headerText": 'DIMENSION (WXLXH) :    " X   " X  "'},
                    ],
                },
                {
                    "itemNo": "000020",
                    "textId": "0001",
                    "lang": 2,
                    "headerTextList": [
                        {"headerText": "กระดาษยิปซั่มด้านหน้า"},
                        {"headerText": "GFT 170D-1270 D184 C4 DB"},
                        {"headerText": "กระดาษยิปซั่มด้านหน้า"},
                        {"headerText": "GFT 170D-1270 D184 C4 DB"},
                    ],
                },
                {
                    "itemNo": "000020",
                    "textId": "Z012",
                    "lang": "E",
                    "headerTextList": [{"headerText": "TPC"}],
                },
                {
                    "itemNo": "000020",
                    "textId": "Z017",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "@        REAMS  X         PALLETS"},
                        {"headerText": 'DIMENSION (WXLXH) :    " X   " X  "'},
                        {"headerText": "@        REAMS  X         PALLETS"},
                        {"headerText": 'DIMENSION (WXLXH) :    " X   " X  "'},
                    ],
                },
                {
                    "itemNo": "000030",
                    "textId": "Z012",
                    "lang": "E",
                    "headerTextList": [{"headerText": "TPC"}],
                },
                {
                    "itemNo": "000030",
                    "textId": "0001",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1175 D184 C4 EB"},
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1175 D184 C4 EB"},
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1195 D184 C4 EB"},
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1195 D184 C4 EB"},
                    ],
                },
                {
                    "itemNo": "000040",
                    "textId": "Z012",
                    "lang": "E",
                    "headerTextList": [{"headerText": "TPC"}],
                },
                {
                    "itemNo": "000040",
                    "textId": "Z017",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "@        REAMS  X         PALLETS"},
                        {"headerText": 'DIMENSION (WXLXH) :    " X   " X  "'},
                    ],
                },
                {
                    "itemNo": "000050",
                    "textId": "0001",
                    "lang": 2,
                    "headerTextList": [
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1195 D184 C4 EB"},
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1195 D184 C4 EB"},
                    ],
                },
                {
                    "itemNo": "000050",
                    "textId": "Z012",
                    "lang": "E",
                    "headerTextList": [{"headerText": "TPC"}],
                },
                {
                    "itemNo": "000050",
                    "textId": "Z017",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "@        REAMS  X         PALLETS"},
                        {"headerText": 'DIMENSION (WXLXH) :    " X   " X  "'},
                    ],
                },
                {
                    "itemNo": "000060",
                    "textId": "0001",
                    "lang": 2,
                    "headerTextList": [
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1175 D184 C4 EB"},
                        {"headerText": "กระดาษยิปซั่มด้านหลัง"},
                        {"headerText": "GB 160D-1175 D184 C4 EB"},
                    ],
                },
                {
                    "itemNo": "000060",
                    "textId": "Z012",
                    "lang": "E",
                    "headerTextList": [{"headerText": "TPC"}],
                },
                {
                    "itemNo": "000060",
                    "textId": "Z017",
                    "lang": "E",
                    "headerTextList": [
                        {"headerText": "@        REAMS  X         PALLETS"},
                        {"headerText": 'DIMENSION (WXLXH) :    " X   " X  "'},
                    ],
                },
            ],
        }
    ],
}

ES_15 = {}

ES_17 = {
    "piMessageId": "PIPXXXXXXXXXXXXXXXX",
    "salesdocument": "0411088207",
    "creditStatusCode": "B",
    "creditStatusText": "Credit check was executed, document not OK",
    "data": [
        {
            "type": random.choice(["S", "E"]),
            "id": "V1",
            "number": "311",
            "message": "Standard Order 411089146 has been saved",
            "logNo": "",
            "logMsgNo": "",
            "messageV1": "Standard Order",
            "messageV2": "0411089146",
            "messageV3": "",
            "messageV4": "",
            "parameter": "SALES_HEADER_IN",
            "row": "",
            "field": "",
            "system": "PEPCLNT099",
        }
    ],
    "orderItemsOut": [
        {
            "itemNo": "000010",
            "materialNo": "Z02DBP400D31004300",
            "customerMaterial": "",
            "targetQuantity": "",
            "salesUnit": "ROL",
            "plant": "7581",
            "shippingPoint": "7505",
            "route": "711006",
            "poNo": "",
            "poItemNo": "10",
            "itemCategory": "ZTAN",
            "prcGroup1": "K08",
            "prcGroup2": "",
            "shipToPoNo": "",
            "poDateS": "30/06/2022",
            "poItemNoS": "",
            "overDeliveryTol": "5.0",
            "underDeliveryTol": "5.0",
            "paymentTerm": "",
            "netValue": "58.80",
            "currency": "THB",
            "prNo": "",
            "prItem": "",
            "rejectReason": "",
            "netWeight": "",
            "grossWeight": "",
            "productHierarchy": "",
            "priceGroup": "03",
            "materialPricingGroup": "02",
            "salesDistrict": "075001",
            "storageLocation": "",
            "itemStatus": "",
        }
    ],
    "conditionsOut": [
        {
            "itemNo": "000010",
            "conditionStepNo": "720",
            "conditionCount": "1",
            "conditionType": "ZN00",
            "conditionValue": "22050.00",
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPerUnit": "1",
            "conditionPriceDate": "07/06/2022",
            "conditionBaseBalue": "100",
            "conditionExchgRate": "1",
            "numconvert": "1050",
            "denominato": "100",
        }
    ],
    "orderSchedulesOut": [
        {
            "itemNo": "000010",
            "scheduleLine": "0001",
            "scheduleLineCate": "ZC",
            "requestDate": "13/06/2022",
            "requestQty": "5.000",
            "confirmQty": "3.000",
            "deliveryBlock": "",
        }
    ],
    "incompleteLogOut": [
        {
            "documentNo": "511176306",
            "itemNo": "000010",
            "scheduleLine": "0000",
            "partnerRole": "",
            "tableName": "VBKD",
            "fieldName": "BZIRK",
            "fieldText": "Sales district",
        }
    ],
}

ES_18 = {
    "piMessageId": "PIPXXXXXXXXXXXXXXXX",
    "salesdocument": "0410273310",
    "return": {
        "type": "S",
        "id": "V1",
        "number": "311",
        "message": "ORDER_ITEM_IN has been processed successful",
        "logNo": "",
        "logMsgNo": "000000",
        "messageV1": "VBAPKOM",
        "messageV2": "000010",
        "messageV3": "",
        "messageV4": "",
        "parameter": "ORDER_ITEM_IN",
        "row": "1",
        "field": "",
        "system": "PEPCLNT099",
    },
    "orderItemsOut": {
        "itemNo": "",
        "materialNo": "000010",
        "customerMaterialNo": "Z02KSG170D0450117N",
        "targetQuantity": "",
        "salesUnit": "5.000",
        "plant": "ROL",
        "shippingPoint": "PO42",
        "route": "7503",
        "custPoNo": "711178",
        "poItemNo": "test001",
        "itemCategory": "",
        "priceGroup1": "ZTAN",
        "priceGroup2": "",
        "shipToPoNo": "",
        "poDate": "",
        "shipToPoItemNo": "",
        "overDeliveryTol": 0,
        "unlimitTol": "",
        "underDeliveryTol": 99,
        "paymentTerms": "99.0",
        "umvkn": "TL60",
        "umvkz": "1",
        "priceGroup": "1,000",
        "materialPricingGroup": "",
        "salesDistrict": "03",
        "storageLocation": "02",
        "prNo": "075001",
        "prItem": "",
        "prStatus": "1042001280",
        "poAutoPr": "00002",
        "rejectReason": "P",
    },
    "orderSchedulesOut": {
        "itemNo": "000010",
        "scheduleLine": "0001",
        "updateflag": "U",
        "scheduleLinecate": "ZC",
        "requestDate": "13.06.2022",
        "requestQuantity": "5.000",
        "confirmQuantity": "3.000",
        "deliveryBlock": "09",
    },
    "businessOut": {
        "sdDoc": "0410273310",
        "itemNo": "000000",
        "priceGroup": "03",
        "customerGroup": "45",
        "salesDistrict": "075003",
        "incoterms1": "CFR",
        "incoterms2": "จ.สมุทรปราการ",
        "ordcombind": "X",
        "accountAssignment": "01",
        "exchgRate": "1.00000",
        "priceDate": "13.06.2022",
        "billDate": "13.06.2023",
    },
    "conditionsOut": {
        "itemNo": "000010",
        "conditionStNo": "720",
        "conditionCount": "1",
        "conditionType": "ZN00",
        "currency": "THB",
        "conditionUnit": "PC",
        "conditionPUnt": "1",
        "conpricdat": "07.06.2022",
        "conbaseval": "220500.00",
        "conexchrat": "1",
        "numberConvertor": "1050",
        "denominator": "100",
        "conditionValue": "220500.00",
    },
    "incompleteLogOut": {
        "docNumber": "0511176306",
        "itemNo": "000010",
        "scheduleLine": "0001",
        "partnerRole": "",
        "tableName": "VBKD",
        "fieldName": "BZIRK",
        "fieldText": "Sales district",
    },
    "creditStatus": "B",
    "creditStatustext": "Credit check was executed, document not OK",
    "materialBlockStatusText": "Material Z02GF-170E125090AI has status: SD Block",
    "customerBlockText": "Customer 1019641 has been assigned order block: Order block",
    "customerDeleteText": "Customer 0001019641 is marked for deletion",
}

ES_21 = {}

# ES_23 = {}

ES_25 = {
    "piMessageId": "001",
    "status": "success",
    "reason": "",
    "data": [
        {
            "sdDoc": "0411089335",
            "status": "B",
            "createDate": "03/10/2022",
            "createTime": "15:13:19",
            "poNo": "Java8QA",
            "salesOrg": "0750",
            "descriptionInContract": "K01: Test by MiG",
            "creditStatus": "B",
            "deliveryStatus": "A",
            "soldTo": "0000000891",
            "soldToName1": "SIAM TOPPAN PACKAGING CO.,LTD.",
            "shipTo": "0001031456",
            "shipToName1": "บจก. เอ็ม ซี ดีการพิมพ์ (ประเทศไทย)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.เมือง จ.สมุทรปราการ",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days after receive bill",
        },
        {
            "sdDoc": "0411089336",
            "status": "C",
            "createDate": "04/10/2022",
            "createTime": "16:33:44",
            "poNo": "TEST PO NUMBER DP",
            "salesOrg": "0750",
            "creditStatus": "A",
            "deliveryStatus": "C",
            "soldTo": "0001003304",
            "soldToName1": "บจก. เพอร์แพ็ค โพรเคียวเมนต์",
            "shipTo": "0001003912",
            "shipToName1": "บจก. เพอร์แพ็คโพรเคียวเมนต์",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "เขตยานนาวา จ.กรุงเทพฯ",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days after receive bill",
        },
        {
            "sdDoc": "0411089337",
            "status": "C",
            "createDate": "04/10/2022",
            "createTime": "16:37:43",
            "poNo": "TEST PO NUMBER DP",
            "salesOrg": "0750",
            "creditStatus": "A",
            "deliveryStatus": "C",
            "soldTo": "0001003304",
            "soldToName1": "บจก. เพอร์แพ็ค โพรเคียวเมนต์",
            "shipTo": "0001003912",
            "shipToName1": "บจก. เพอร์แพ็คโพรเคียวเมนต์",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "เขตยานนาวา จ.กรุงเทพฯ",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days after receive bill",
        },
        {
            "sdDoc": "0411089339",
            "status": "B",
            "createDate": "05/10/2022",
            "createTime": "18:44:15",
            "poNo": "Test PEQ_11OCT_07",
            "salesOrg": "0750",
            "descriptionInContract": "test",
            "deliveryStatus": "B",
            "soldTo": "0001003410",
            "soldToName1": "บริษัท เฮงหลี ทรานส์เฟอร์ จำกัด",
            "shipTo": "0001003483",
            "shipToName1": "บริษัท ไทย แพค พริ้นท์ จำกัด",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.ศรีราชา จ.ชลบุรี",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days after receive bill",
            "lastChangeDate": "28/10/2022",
            "lastChangeTime": "15:41:09",
        },
        {
            "sdDoc": "0411089340",
            "status": "A",
            "createDate": "06/10/2022",
            "createTime": "11:35:17",
            "poNo": "CB22230810",
            "salesOrg": "0750",
            "deliveryStatus": "A",
            "descInSalesOrder": "SKIC Sales Order Interface",
            "soldTo": "0001011222",
            "soldToName1": "บจก. กลุ่มสยามบรรจุภัณฑ์-TCCB",
            "shipTo": "0001011223",
            "shipToName1": "โรงงานชลบุรี (TCCB)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.ศรีราชา จ.ชลบุรี",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days after receive bill",
        },
        {
            "sdDoc": "0411089341",
            "status": "B",
            "createDate": "06/10/2022",
            "createTime": "17:27:21",
            "poNo": "TEST-modeF",
            "salesOrg": "0750",
            "deliveryStatus": "B",
            "soldTo": "0001012114",
            "soldToName1": "บจก. กลุ่มสยามบรรจุภัณฑ์-TCNK",
            "shipTo": "0001012119",
            "shipToName1": "โรงงานนวนคร TCNK",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.คลองหลวง จ.ปทุมธานี",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days after receive bill",
        },
    ],
    "dataItem": [
        {
            "sdDoc": "0411089335",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02KA-125D1440117N",
            "matDesc": "KA-ConfiDenz125D-144 DIA117N",
            "plant": 7561,
            "saleUnit": "ROL",
            "netWeight": 1.303,
            "netWeightUnit": "TON",
            "netPrice": 32000,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 14984.5,
            "giDateList": [{"giDate": "30/11/2022"}],
            "firstDeliveryDT": "30/11/2022",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 1303,
            "confirmQty": 1,
            "confirmQtyBase": 1303,
            "pendingQty": 1,
            "pendingQtyBase": 1303,
            "contractPI": "0410089654",
            "contractPIItemNo": "000020",
        },
        {
            "sdDoc": "0411089336",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "C",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 0.082,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 2132,
            "giDateList": [{"giDate": "04/10/2022"}],
            "firstDeliveryDT": "04/10/2022",
            "baseUnit": "KG",
            "orderQty": 0.1,
            "orderQtyBase": 82,
            "confirmQty": 0.1,
            "confirmQtyBase": 82,
            "delQty": 0.1,
            "delQtyBase": 82,
        },
        {
            "sdDoc": "0411089337",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "C",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 0.082,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 2132,
            "giDateList": [{"giDate": "04/10/2022"}],
            "firstDeliveryDT": "04/10/2022",
            "baseUnit": "KG",
            "orderQty": 0.1,
            "orderQtyBase": 82,
            "confirmQty": 0.1,
            "confirmQtyBase": 82,
            "delQty": 0.1,
            "delQtyBase": 82,
        },
        {
            "sdDoc": "0411089339",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "C",
            "matNo": "Z02CA-150D1330117N",
            "matDesc": "CA- 150D-133 DIA117 N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 0.963,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 22534.2,
            "giDateList": [{"giDate": "05/10/2022"}],
            "firstDeliveryDT": "05/10/2022",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 963,
            "confirmQty": 1,
            "confirmQtyBase": 963,
            "pendingQty": 0.037,
            "pendingQtyBase": 35.631,
            "delQty": 0.963,
            "delQtyBase": 927.369,
            "contractPI": "0410089664",
            "contractPIItemNo": "000010",
        },
        {
            "sdDoc": "0411089339",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-150D1330117N",
            "matDesc": "CA- 150D-133 DIA117 N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 5.778,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 135205.2,
            "giDateList": [{"giDate": "28/10/2022"}],
            "firstDeliveryDT": "28/10/2022",
            "baseUnit": "KG",
            "orderQty": 6,
            "orderQtyBase": 5778,
            "nonConfirmQty": 6,
            "nonConfirmQtyBase": 5778,
            "pendingQty": 6,
            "pendingQtyBase": 5778,
            "contractPI": "0410089664",
            "contractPIItemNo": "000010",
        },
        {
            "sdDoc": "0411089340",
            "itemNo": "000010",
            "custMat": "Z02CSP150D2080117N",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CSP150D2080117N",
            "matDesc": "CSP 150D-208 DIA117N",
            "plant": 7534,
            "saleUnit": "ROL",
            "netWeight": 3.008,
            "netWeightUnit": "TON",
            "netPrice": 28000,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 78358.4,
            "giDateList": [{"giDate": "03/08/2022"}],
            "firstDeliveryDT": "03/08/2022",
            "baseUnit": "KG",
            "orderQty": 2,
            "orderQtyBase": 3008,
            "nonConfirmQty": 2,
            "nonConfirmQtyBase": 3008,
            "pendingQty": 2,
            "pendingQtyBase": 3008,
            "contractPI": "0410089642",
            "contractPIItemNo": "000010",
        },
        {
            "sdDoc": "0411089341",
            "itemNo": "000010",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "B",
            "matNo": "Z02CA-090D1440117N",
            "matDesc": "CA- 090D-144 DIA117N",
            "plant": 7550,
            "saleUnit": "ROL",
            "netWeight": 5.285,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": "750A",
            "netValue": 137410,
            "giDateList": [{"giDate": "06/10/2022"}],
            "firstDeliveryDT": "06/10/2022",
            "baseUnit": "KG",
            "orderQty": 5,
            "orderQtyBase": 5285,
            "confirmQty": 4.132,
            "confirmQtyBase": 4367.524,
            "nonConfirmQty": 0.868,
            "nonConfirmQtyBase": 917.476,
            "pendingQty": 4,
            "pendingQtyBase": 4228,
            "delQty": 1,
            "delQtyBase": 1057,
        },
        {
            "sdDoc": "0411089335",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02KA-125D1440117N",
            "matDesc": "KA-ConfiDenz125D-144 DIA117N",
            "plant": 7561,
            "saleUnit": "ROL",
            "netWeight": 1.303,
            "netWeightUnit": "TON",
            "netPrice": 32000,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 14984.5,
            "firstDeliveryDT": "30/11/2022",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 1303,
            "confirmQty": 1,
            "confirmQtyBase": 1303,
            "pendingQty": 1,
            "pendingQtyBase": 1303,
            "contractPI": "0410089654",
            "contractPIItemNo": "000020",
        },
        {
            "sdDoc": "0411089336",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "C",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 0.082,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 2132,
            "firstDeliveryDT": "04/10/2022",
            "baseUnit": "KG",
            "orderQty": 0.1,
            "orderQtyBase": 82,
            "confirmQty": 0.1,
            "confirmQtyBase": 82,
            "delQty": 0.1,
            "delQtyBase": 82,
        },
        {
            "sdDoc": "0411089337",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "C",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 0.082,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 2132,
            "firstDeliveryDT": "04/10/2022",
            "baseUnit": "KG",
            "orderQty": 0.1,
            "orderQtyBase": 82,
            "confirmQty": 0.1,
            "confirmQtyBase": 82,
            "delQty": 0.1,
            "delQtyBase": 82,
        },
        {
            "sdDoc": "0411089339",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "C",
            "matNo": "Z02CA-150D1330117N",
            "matDesc": "CA- 150D-133 DIA117 N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 0.963,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 22534.2,
            "firstDeliveryDT": "05/10/2022",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 963,
            "confirmQty": 1,
            "confirmQtyBase": 963,
            "pendingQty": 0.037,
            "pendingQtyBase": 35.631,
            "delQty": 0.963,
            "delQtyBase": 927.369,
            "contractPI": "0410089664",
            "contractPIItemNo": "000010",
        },
        {
            "sdDoc": "0411089339",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-150D1330117N",
            "matDesc": "CA- 150D-133 DIA117 N",
            "plant": 7521,
            "saleUnit": "ROL",
            "netWeight": 5.778,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 135205.2,
            "firstDeliveryDT": "28/10/2022",
            "baseUnit": "KG",
            "orderQty": 6,
            "orderQtyBase": 5778,
            "nonConfirmQty": 6,
            "nonConfirmQtyBase": 5778,
            "pendingQty": 6,
            "pendingQtyBase": 5778,
            "contractPI": "0410089664",
            "contractPIItemNo": "000010",
        },
        {
            "sdDoc": "0411089340",
            "itemNo": "000010",
            "custMat": "Z02CSP150D2080117N",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CSP150D2080117N",
            "matDesc": "CSP 150D-208 DIA117N",
            "plant": 7534,
            "saleUnit": "ROL",
            "netWeight": 3.008,
            "netWeightUnit": "TON",
            "netPrice": 28000,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 78358.4,
            "firstDeliveryDT": "03/08/2022",
            "baseUnit": "KG",
            "orderQty": 2,
            "orderQtyBase": 3008,
            "nonConfirmQty": 2,
            "nonConfirmQtyBase": 3008,
            "pendingQty": 2,
            "pendingQtyBase": 3008,
            "contractPI": "0410089642",
            "contractPIItemNo": "000010",
        },
        {
            "sdDoc": "0411089341",
            "itemNo": "000010",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "B",
            "matNo": "Z02CA-090D1440117N",
            "matDesc": "CA- 090D-144 DIA117N",
            "plant": 7550,
            "saleUnit": "ROL",
            "netWeight": 5.285,
            "netWeightUnit": "TON",
            "netPrice": 26000,
            "priceCurrency": "THB",
            "shippingPoint": "750A",
            "netValue": 137410,
            "firstDeliveryDT": "06/10/2022",
            "baseUnit": "KG",
            "orderQty": 5,
            "orderQtyBase": 5285,
            "confirmQty": 4.132,
            "confirmQtyBase": 4367.524,
            "nonConfirmQty": 0.868,
            "nonConfirmQtyBase": 917.476,
            "pendingQty": 4,
            "pendingQtyBase": 4228,
            "delQty": 1,
            "delQtyBase": 1057,
        },
    ],
}

ES_26 = {
    "piMessageId": 5100000753,
    "status": "success",
    "data": [
        {
            "orderHeaderIn": [
                {
                    "saleDocument": "0411089335",
                    "docType": "ZOR",
                    "salesOrg": "0750",
                    "distributionChannel": 10,
                    "division": "00",
                    "reqDate": "30/11/2022",
                    "incoterms1": "CFR",
                    "incoterms2": "อ.เมือง จ.สมุทรปราการ",
                    "paymentTerms": "NT60",
                    "poNo": "Java8QA",
                    "priceGroup": "04",
                    "priceDate": "30/11/2022",
                    "createDate": "03/10/2022",
                    "customerGroup": 43,
                    "salesDistrict": "075001",
                    "shippingCondition": "01",
                    "salesGroup": 751,
                    "salesOff": "0750",
                    "orderReason": "",
                    "exchangeRate": 1,
                    "orderAmtBeforeVat": 14984.5,
                    "orderAmtVat": 1048.92,
                    "orderAmtAfterVat": 16033.42,
                    "currency": "THB",
                }
            ],
            "orderPartners": [
                {
                    "partnerRole": "AG",
                    "partnerNo": "0000000891",
                    "addrLink": "0000184607",
                    "address": [
                        {
                            "addrNo": "0000184607",
                            "name": "SIAM TOPPAN PACKAGING CO.,LTD.",
                            "city": "Samut Prakan",
                            "postCode": 10280,
                            "district": "Praeksa , Muang",
                            "street": "543 Moo 4, Sukhumvit Rd.",
                            "transpzone": "ZATH011000",
                            "country": "TH",
                            "telNoList": [{"telNo": "66-2-324-0592-4"}],
                        }
                    ],
                },
                {
                    "partnerRole": "AP",
                    "partnerNo": "0000047744",
                    "addrLink": "0000184598",
                    "address": [
                        {
                            "addrNo": "0000184598",
                            "name": "SCG International Corporation",
                            "name2": "Co.,Ltd.",
                            "city": "BANGKOK",
                            "postCode": 10800,
                            "district": "BANGSUE, BANGSUE,",
                            "street": "1 SIAM CEMENT ROAD.,",
                            "transpzone": 10,
                            "country": "TH",
                            "telNoList": [
                                {"telNo": "02 586 5399"},
                                {"telNo": "025861888"},
                            ],
                        }
                    ],
                },
                {
                    "partnerRole": "AU",
                    "partnerNo": "0090011155",
                    "address": [
                        {
                            "addrNo": "0000184607",
                            "name": "SIAM TOPPAN PACKAGING CO.,LTD.",
                            "city": "Samut Prakan",
                            "postCode": 10280,
                            "district": "Praeksa , Muang",
                            "street": "543 Moo 4, Sukhumvit Rd.",
                            "transpzone": "ZATH011000",
                            "country": "TH",
                            "telNoList": [{"telNo": "66-2-324-0592-4"}],
                        }
                    ],
                },
                {
                    "partnerRole": "RE",
                    "partnerNo": "0000000891",
                    "addrLink": "0000184607",
                    "address": [
                        {
                            "addrNo": "0000184607",
                            "name": "SIAM TOPPAN PACKAGING CO.,LTD.",
                            "city": "Samut Prakan",
                            "postCode": 10280,
                            "district": "Praeksa , Muang",
                            "street": "543 Moo 4, Sukhumvit Rd.",
                            "transpzone": "ZATH011000",
                            "country": "TH",
                            "telNoList": [{"telNo": "66-2-324-0592-4"}],
                        }
                    ],
                },
                {
                    "partnerRole": "RG",
                    "partnerNo": "0000000891",
                    "addrLink": "0000184607",
                    "address": [
                        {
                            "addrNo": "0000509283",
                            "name": "บจก. เอ็ม ซี ดีการพิมพ์ (ประเทศไทย)",
                            "city": "จ.สมุทรปราการ",
                            "postCode": 10280,
                            "district": "ต.แพรกษา อ.เมืองสมุทรปราการ",
                            "street": 111,
                            "strSuppl1": "นิคมอุตสาหกรรมบางปู ซอย 14 บี",
                            "transpzone": "1A2",
                            "country": "TH",
                            "telNoList": [{"telNo": "02-7288999"}],
                        }
                    ],
                },
                {"partnerRole": "VE", "partnerNo": "0010061233"},
                {
                    "partnerRole": "WE",
                    "partnerNo": "0001031456",
                    "addrLink": "0000509283",
                },
                {"partnerRole": "ZM", "partnerNo": "0010067380"},
            ],
            "orderItems": [
                {
                    "itemNo": "000010",
                    "material": "Z02KA-125D1440117N",
                    "materialDesc": "KA-ConfiDenz125D-144 DIA117N",
                    "itemQty": 1,
                    "salesUnit": "ROL",
                    "plant": 7561,
                    "paymentTerm": "NT60",
                    "poNumber": "Java8QA",
                    "poItemNo": "000010",
                    "itemCategory": "ZTAN",
                    "materialGroup1": "K01",
                    "saleText1_th": "กระดาษ KA-ConfiDenz125-144D117",
                    "routeId": 711178,
                    "routeName": "กาญจนบุรี(วังศาลา)-บางปู/บางพลี/บางบ่อ",
                    "requestedDate": "30/11/2022",
                    "untimatedTol": "X",
                    "weightPerUnit": 1303,
                    "orderQty": 1,
                    "comfirmQty": 1,
                    "deliveryStatus": "A",
                    "saleQtyDivision": 1,
                    "saleQtyFactor": 1303,
                    "prdHierachy": "0210KLBKA 125",
                    "shippingPoint": 7503,
                }
            ],
            "orderCondition": [
                {
                    "itemNo": "000010",
                    "conditionRate": -20500,
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": -26711.5,
                    "conditionBaseValue": 1.303,
                },
                {
                    "itemNo": "000010",
                    "conditionRate": 11500,
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 14984.5,
                    "conditionBaseValue": 1.303,
                },
                {
                    "itemNo": "000010",
                    "conditionRate": 12305,
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 16033.42,
                    "conditionBaseValue": 1.303,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "conditionPriceOrder": 1048.92,
                    "conditionBaseValue": 14984.5,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "VPRS",
                    "conditionRate": 16918.06,
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionPriceOrder": 22044.23,
                    "conditionBaseValue": 1303,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD1",
                    "conditionBaseValue": 41696,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD2",
                    "conditionRate": -20500,
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": -26711.5,
                    "conditionBaseValue": 1.303,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD3",
                    "conditionBaseValue": 14984.5,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 1.303,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 1303,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "ZN00",
                    "conditionRate": 14984.5,
                    "currency": "THB",
                    "conditionUnit": "ROL",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 14984.5,
                    "conditionBaseValue": 1,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "ZPR1",
                    "conditionRate": 32000,
                    "currency": "THB",
                    "conditionUnit": "TON",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 41696,
                    "conditionBaseValue": 1.303,
                },
            ],
            "orderText": [
                {
                    "textId": "Z001",
                    "language": 2,
                    "textLine": [{"text": "เพิ่มสำเนาDP1ชุดสินค้าDuplex:TUP"}],
                },
                {
                    "textId": "Z001",
                    "language": "E",
                    "textLine": [{"text": '"เพิ่ม DP, แนบ COA, แยกบิลโรง1-2"'}],
                },
                {
                    "textId": "Z014",
                    "language": "E",
                    "textLine": [{"text": "ANY THAILAND PORTS AT THE SELLER'S OPTION"}],
                },
                {
                    "textId": "Z015",
                    "language": "E",
                    "textLine": [
                        {
                            "text": "PACKING: GOODS ARE IN STANDARD EXPORT PACKING FCL/FCL CONT."
                        }
                    ],
                },
                {"textId": "Z016", "language": 2, "textLine": [{"text": "ทดสอบ K01"}]},
                {
                    "textId": "Z056",
                    "language": 2,
                    "textLine": [
                        {"text": "บริษัทสยามคราฟท์อุตสาหกรรม จำกัด"},
                        {"text": "1 ถ.ปูนซิเมนต์ไทย บางซื่อ"},
                        {"text": "กทม. 10800"},
                    ],
                },
                {
                    "textId": "Z056",
                    "language": "E",
                    "textLine": [
                        {"text": "SIAM KRAFT INDUSTRY CO., LTD."},
                        {"text": "1 SIAM CEMENT ROAD BANGSUE"},
                        {"text": "BANGKOK 10800 THAILAND"},
                    ],
                },
                {
                    "textId": "Z067",
                    "language": 2,
                    "textLine": [{"text": '" D/P & COA on Web e-Document "'}],
                },
                {
                    "textId": "Z067",
                    "language": "E",
                    "textLine": [{"text": '" D/P & COA on Web e-Document "'}],
                },
                {
                    "textId": "ZK01",
                    "language": "E",
                    "textLine": [{"text": "pkadmin01  ppadmin"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "0001",
                    "language": 2,
                    "textLine": [
                        {"text": "กระดาษ KA-ConfiDenz125-144D117"},
                        "",
                        "",
                        "",
                    ],
                },
                {
                    "ItemNo": "000010",
                    "textId": "Z012",
                    "language": "E",
                    "textLine": [{"text": "TPC"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "Z017",
                    "language": "E",
                    "textLine": [
                        {"text": "@        REAMS  X         PALLETS"},
                        {"text": 'DIMENSION (WXLXH) :    " X   " X  "'},
                    ],
                },
            ],
        }
    ],
}

ES_29 = {
    "piMessageId": "PIPXXXXXXXXXXXXXXXX",
    "status": "success",
    "reason": "",
    "routeList": [
        {
            "route": "US710H",
            "routeDescription": "กาญจนบุรี(วังศาลา)-NASHVILLE(US)",
        }
    ],
}

ES_27 = {
    "piMessageId": "PIPXXXXXXXXXXXXXXXX",
    "salesDocumentIn": "0410273310",
    "return": [
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "ORDER_ITEM_IN has been processed successful",
            "logNo": "",
            "logMsgNo": "000000",
            "messageV1": "VBAPKOM",
            "messageV2": "000010",
            "messageV3": "",
            "messageV4": "",
            "parameter": "ORDER_ITEM_IN",
            "row": "1",
            "field": "",
            "system": "PEPCLNT099",
        }
    ],
    "orderItemsOut": [
        {
            "itemNumber": "000010",
            "materialCode": "Z02KSG170D0450117N",
            "targetQuantity": 5,
            "salesUnit": "ROL",
            "plant": "PO42",
        }
    ],
    "orderSchedulesOut": [
        {
            "itemNumber": 10,
            "newScheduleLine": 1,
            "newRequestDate": "20/07/2022",
            "newRequestQuantity": 9,
            "newConfirmQuantity": 3,
            "newDeliveryBlock": "",
        }
    ],
    "incompleteLogOut": [
        {
            "documentNumber": "0511176306",
            "itemNumber": 10,
            "scheduleLine": 1,
            "partnerRole": "",
            "tableName": "VBKD",
            "fieldName": "BZIRK",
            "fieldText": "Sales district",
        }
    ],
    "creditStatusCode": "B",
    "creditStatusText": "Credit check was executed,doc not OK",
    "materialBlockStatusText": "Material Z02GF-170E125090AI = SD Block",
    "customerBlockText": "Customer 1019641 = Order block",
    "customerDeleteText": "Customer 0001019641 is marked = deletion",
}
