# Generated by Django 3.2.13 on 2022-09-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaterialMapping",
        ),
    ]
