# Generated by Django 3.2.13 on 2022-09-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scgp_po_upload", "0002_delete_materialmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedPoUploadFileLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("failed_date_time", models.DateTimeField(auto_now=True)),
                ("note", models.CharField(max_length=255)),
            ],
        ),
    ]
