# Generated by Django 3.2.13 on 2022-09-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0003_failedpouploadfilelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoUploadFileLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="pending", max_length=255)),
                ("note", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="FailedPoUploadFileLog",
        ),
    ]
