# Generated by Django 3.2.13 on 2022-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0005_auto_20220915_0753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouploadfilelog",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
