# Generated by Django 3.2.13 on 2022-09-19 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_master_data", "0006_auto_20220910_1403"),
        ("scgp_po_upload", "0006_alter_pouploadfilelog_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoUploadCustomerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_customer_master", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sold_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_master_data.soldtomaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
