# Generated by Django 3.2.13 on 2022-11-16 13:49

from django.db import migrations, models

import scgp_po_upload.s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0007_pouploadcustomersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouploadfilelog",
            name="file",
            field=models.FileField(
                blank=True,
                storage=scgp_po_upload.s3_storage.EOrderingS3Storage(),
                upload_to="po_upload_files",
            ),
        ),
    ]
