# Generated by Django 3.2.13 on 2023-02-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0008_alter_pouploadfilelog_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouploadfilelog",
            name="po_numbers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
