# Generated by Django 3.2.13 on 2023-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0009_pouploadfilelog_po_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouploadfilelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("success", "Success"),
                    ("being_process", "Being Process"),
                    ("fail", "Fail"),
                    ("upload file", "Upload file"),
                    ("in_queue", "in queue"),
                    ("call_iPlan_request", "call iPlan request"),
                    ("call SAP", "call sap"),
                    ("call_iPlan_confirm", "call iPlan confirm"),
                ],
                default="being_process",
                max_length=255,
            ),
        ),
    ]
