# Generated by Django 3.2.13 on 2024-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0010_alter_pouploadfilelog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouploadfilelog",
            name="upload_type",
            field=models.CharField(
                choices=[("E", "E"), ("T", "T")], default="T", max_length=1
            ),
        ),
    ]
