# Generated by Django 3.2.13 on 2024-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_po_upload", "0011_pouploadfilelog_upload_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouploadfilelog",
            name="extra_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
