ES_08 = {
    "piMessageId": 5100000753,
    "status": "success",
    "type": "Mock data from internal",
    "data": {
        "customerId": "0000000821",
        "customerName": "SCG International Corporation",
        "name2": "Co.,Ltd.",
        "city": "BANGKOK",
        "postcode": 10800,
        "district": "BANGSUE, BANGSUE,",
        "street1": "1 SIAM CEMENT ROAD.,",
        "transportZone": 10,
        "transportZoneDesc": "กรุงเทพฯ",
        "country": "TH",
        "countryName": "Thailand",
        "partnerList": [
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "AG",
                "partnerFunctionDes": "Sold-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "AU",
                "partnerFunctionDes": "Author",
                "partnerNo": "0000000105",
                "partnerName": "EMP105 last curr EMP105 firstC",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "RE",
                "partnerFunctionDes": "Bill-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "RG",
                "partnerFunctionDes": "Payer",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "VE",
                "partnerFunctionDes": "Sales Employee",
                "partnerNo": "0010019734",
                "partnerName": "น.ส. โควต้า การลา",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "WE",
                "partnerFunctionDes": "Ship-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "ZM",
                "partnerFunctionDes": "Employee respons.",
                "partnerNo": "0000000105",
                "partnerName": "EMP105 last curr EMP105 firstC",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 10,
                "division": "00",
                "partnerFunction": "ZM",
                "partnerFunctionDes": "Employee respons.",
                "partnerNo": "0022200259",
                "partnerName": "นาย 0250-OT2 259",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "AG",
                "partnerFunctionDes": "Sold-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "AU",
                "partnerFunctionDes": "Author",
                "partnerNo": "0000000105",
                "partnerName": "EMP105 last curr EMP105 firstC",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "RE",
                "partnerFunctionDes": "Bill-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "RG",
                "partnerFunctionDes": "Payer",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "SP",
                "partnerFunctionDes": "Forwarding Agent",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "VE",
                "partnerFunctionDes": "Sales Employee",
                "partnerNo": "0000000105",
                "partnerName": "EMP105 last curr EMP105 firstC",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 20,
                "division": "00",
                "partnerFunction": "WE",
                "partnerFunctionDes": "Ship-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 30,
                "division": "00",
                "partnerFunction": "AG",
                "partnerFunctionDes": "Sold-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 30,
                "division": "00",
                "partnerFunction": "AU",
                "partnerFunctionDes": "Author",
                "partnerNo": "0000000105",
                "partnerName": "EMP105 last curr EMP105 firstC",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 30,
                "division": "00",
                "partnerFunction": "RE",
                "partnerFunctionDes": "Bill-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 30,
                "division": "00",
                "partnerFunction": "RG",
                "partnerFunctionDes": "Payer",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
            {
                "saleOrg": "0750",
                "distributionChannel": 30,
                "division": "00",
                "partnerFunction": "WE",
                "partnerFunctionDes": "Ship-to party",
                "partnerNo": "0000000821",
                "partnerName": "SCG International Corporation",
            },
        ],
    },
}
