ES_18 = {
    "piMessageId": "PIPXXXXXXXXXXXXXXXX",
    "salesdocument": "0410273310",
    "return": {
        "type": "S",
        "id": "V1",
        "number": "311",
        "message": "ORDER_ITEM_IN has been processed successful",
        "logNo": "",
        "logMsgNo": "000000",
        "messageV1": "VBAPKOM",
        "messageV2": "000010",
        "messageV3": "",
        "messageV4": "",
        "parameter": "ORDER_ITEM_IN",
        "row": "1",
        "field": "",
        "system": "PEPCLNT099",
    },
    "orderItemsOut": {
        "itemNo": "",
        "materialNo": "000010",
        "customerMaterialNo": "Z02KSG170D0450117N",
        "targetQuantity": "",
        "salesUnit": "5.000",
        "plant": "ROL",
        "shippingPoint": "PO42",
        "route": "7503",
        "custPoNo": "711178",
        "poItemNo": "test001",
        "itemCategory": "",
        "priceGroup1": "ZTAN",
        "priceGroup2": "",
        "shipToPoNo": "",
        "poDate": "",
        "shipToPoItemNo": "",
        "overDeliveryTol": 0,
        "unlimitTol": "",
        "underDeliveryTol": 99,
        "paymentTerms": "99.0",
        "umvkn": "TL60",
        "umvkz": "1",
        "priceGroup": "1,000",
        "materialPricingGroup": "",
        "salesDistrict": "03",
        "storageLocation": "02",
        "prNo": "075001",
        "prItem": "",
        "prStatus": "1042001280",
        "poAutoPr": "00002",
        "rejectReason": "P",
    },
    "orderSchedulesOut": {
        "itemNo": "000010",
        "scheduleLine": "0001",
        "updateflag": "U",
        "scheduleLinecate": "ZC",
        "requestDate": "13.06.2022",
        "requestQuantity": "5.000",
        "confirmQuantity": "3.000",
        "deliveryBlock": "09",
    },
    "businessOut": {
        "sdDoc": "0410273310",
        "itemNo": "000000",
        "priceGroup": "03",
        "customerGroup": "45",
        "salesDistrict": "075003",
        "incoterms1": "CFR",
        "incoterms2": "จ.สมุทรปราการ",
        "ordcombind": "X",
        "accountAssignment": "01",
        "exchgRate": "1.00000",
        "priceDate": "13.06.2022",
        "billDate": "13.06.2023",
    },
    "conditionsOut": {
        "itemNo": "000010",
        "conditionStNo": "720",
        "conditionCount": "1",
        "conditionType": "ZN00",
        "currency": "THB",
        "conditionUnit": "PC",
        "conditionPUnt": "1",
        "conpricdat": "07.06.2022",
        "conbaseval": "220500.00",
        "conexchrat": "1",
        "numberConvertor": "1050",
        "denominator": "100",
        "conditionValue": "220500.00",
    },
    "incompleteLogOut": {
        "docNumber": "0511176306",
        "itemNo": "000010",
        "scheduleLine": "0001",
        "partnerRole": "",
        "tableName": "VBKD",
        "fieldName": "BZIRK",
        "fieldText": "Sales district",
    },
    "creditStatus": "B",
    "creditStatustext": "Credit check was executed, document not OK",
    "materialBlockStatusText": "Material Z02GF-170E125090AI has status: SD Block",
    "customerBlockText": "Customer 1019641 has been assigned order block: Order block",
    "customerDeleteText": "Customer 0001019641 is marked for deletion",
}

data_sample = {
    "piMessageId": "PIPXXXXXXXXXXXXXXXX",
    "salesdocumentin": "0410273310",
    "testrun": "X",
    "orderHeaderIn": [
        {
            "reqDateH": "13/06/2022",
            "incoterms1": "CIF",
            "incoterms2": "จ.สมุทรปราการ2",
            "paymentTerms": "NT90",
            "poNo": "",
            "purchaseDate1": "",
            "priceGroup": "03",
            "priceDate": "13/06/2022",
            "currency": "THB",
            "customerGroup": "45",
            "salesDistrict": "075003",
            "shippingCondition": "01",
            "customerGroup1": "01",
            "customerGroup2": "",
            "customerGroup3": "",
            "customerGroup4": "",
            "customerGroup5": "",
            "deliveryBlock": "",
        }
    ],
    "orderHeaderInX": [
        {
            "requestDate": True,
            "incoterms1": True,
            "incoterms2": True,
            "paymentTerms": True,
            "poNo": True,
            "purchaseDate": True,
            "priceGroup": True,
            "priceDate": True,
            "currency": True,
            "customerGroup": True,
            "salesDistrict": True,
            "shippingCondition": True,
            "customerGroup1": True,
            "customerGroup2": True,
            "customerGroup3": True,
            "customerGroup4": True,
            "customerGroup5": True,
            "deliveryBlock": True,
        }
    ],
    "orderPartners": [
        {
            "partnerRole": "WE",
            "partnerNo": "0001002813",
            "itemNo": "000000",
            "addressLink": "12address",
        }
    ],
    "PartnerAddreses": [
        {
            "addressNo": "1",
            "name1": "นาย Customer Name1",
            "name2": "",
            "name3": "",
            "name4": "",
            "city": "",
            "zipCode": "10220",
            "district": "บางซื่อ",
            "street": "",
            "streetSuppl1": "",
            "streetSuppl2": "",
            "streetSuppl3": "",
            "location": "",
            "transportZone": "ZATH010029",
            "country": "TH",
            "telephoneNo": "",
        }
    ],
    "orderItemsIn": [
        {
            "itemNo": "000010",
            "targetQty": 5,
            "salesUnit": "ROL",
            "plant": "754F",
            "shippingPoint": "MY0067",
            "route": "7504",
            "orderNo": "MPS/PO/SKT023/21",
            "poItemNo": "000010",
            "itemCategory": "ZKS4",
            "priceGroup1": "",
            "priceGroup2": "",
            "poNo": "K00040064300100001WY0000000-1730896",
            "poitemNoS": "000010",
            "usage": "100",
            "overdlvtol": 0,
            "unlimitTol": "",
            "unddlvTol": 99,
            "reasonReject": "93",
            "paymentTerms": "TL60",
            "denominato": 1,
            "numconvert": 1000,
        }
    ],
    "orderItemsInx": [
        {
            "itemNo": "000010",
            "updateflag": "U",
            "targetQty": True,
            "salesUnit": True,
            "plant": True,
            "shippingPoint": True,
            "route": True,
            "purchaseOrderNo": True,
            "poItemNo": True,
            "itemCategory?:description": True,
            "priceGroup1": True,
            "priceGroup2": True,
            "poNo": True,
            "poDate": True,
            "poitemNoS": True,
            "overdlvtol": True,
            "unlimitTol": True,
            "unddlvTol": True,
            "reasonReject": True,
            "paymentTerms": True,
            "denominato": True,
            "numconvert": True,
        }
    ],
    "orderSchedulesIn": [
        {
            "itemNo": "000010",
            "scheduleLine": "0001",
            "scheduleLinecate": "ZC",
            "requestDate": "2022-06-07",
            "reqiestQuantity": 10,
            "confirmQuantity": 3,
            "deliveryBlock": "",
        }
    ],
    "orderSchedulesInx": [
        {
            "itemNo": "000010",
            "scheduleLine": "0001",
            "updateflag": True,
            "scheduleLineCate": True,
            "requestDate": True,
            "reqiestQuantity": True,
            "confirmQuantity": True,
            "deliveryBlock": True,
        }
    ],
    "orderConditionsIn": [
        {
            "itemNo": "000010",
            "conditionType": "ZPR2",
            "conditionValue": 4816,
            "currency": "THB",
            "conditionUnit": "ROL",
            "conditionPUnit": "1",
        }
    ],
    "orderConditionsInX": [
        {
            "ITM_NUMBER": "000010",
            "COND_TYPE": "ZPR2",
            "UPDATEFLAG": True,
            "COND_VALUE": True,
            "CURRENCY": True,
            "COND_UNIT": True,
            "COND_P_UNT": True,
        }
    ],
    "orderCfgsValues": [
        {"configId": "000010", "instId": "000010", "charc": "SDKUOM", "value": "MM"}
    ],
    "orderText": [
        {
            "itemNo": "000000",
            "textId": "Z016",
            "langu": "EN",
            "textLine": [{"textLine": "เพิ่มบอร์ดใหม่ส่วนลด 14%"}],
        }
    ],
}
