# Generated by Django 3.2.13 on 2023-02-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PluginConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True)),
                ("identifier", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "plugins_pluginconfiguration",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MulesoftLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("request", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("exception", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mulesoft_api_logs",
            },
        ),
    ]
