# Generated by Django 3.2.13 on 2023-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_mulesoftlog_request_time_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="mulesoftlog",
            name="feature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mulesoftlog",
            name="order_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mulesoftlog",
            name="orderid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mulesoftlog",
            name="retry",
            field=models.BooleanField(default=False),
        ),
    ]
