# Generated by Django 3.2.13 on 2023-06-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_mulesoftlog_retry_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mulesoftlog",
            old_name="request_time_ms",
            new_name="response_time_ms",
        ),
    ]
