# Generated by Django 3.2.13 on 2023-07-06 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_rename_request_time_ms_mulesoftlog_response_time_ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mulesoftlog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
