# Generated by Django 3.2.13 on 2024-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_mulesoftlog_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PmtMaterialMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(max_length=50, unique=True)),
                ("on_hold", models.BooleanField(default=False)),
                (
                    "hold_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "pmt_material_master",
            },
        ),
    ]
