# Generated by Django 3.2.13 on 2024-04-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_pmtmaterialmaster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pmtmaterialmaster",
            old_name="on_hold",
            new_name="is_hold",
        ),
    ]
