import graphene


class PmtMatSearchInput(graphene.InputObjectType):
    pc_1 = graphene.String()
    pc_2 = graphene.String()
    pc_3 = graphene.String()
    pc_4 = graphene.String()
    pc_5 = graphene.String()
    pc_6 = graphene.String()
    sale_text = graphene.String()
    description = graphene.String()
    cust_id = graphene.String()
    cust_name = graphene.String()
    part_no = graphene.String()
    mat_length = graphene.Int()
    mat_width = graphene.Int()
    mat_height = graphene.Int()


class PmtMatSearch(graphene.ObjectType):
    stock_fg = graphene.String()
    stock_qa = graphene.String()
    stock_wip = graphene.String()
    hold = graphene.String()
    cust_name = graphene.String()
    cust_id = graphene.String()
    cust_code = graphene.String()
    pc = graphene.String()
    material_no = graphene.String()
    part_no = graphene.String()
    description = graphene.String()
    sale_text = graphene.String()
    rate = graphene.Float()
    flute = graphene.String()
    board = graphene.String()
    width = graphene.Int()
    length = graphene.Int()
    height = graphene.Int()
    vendor_name = graphene.String()
    net_price = graphene.String()
    pur_txt = graphene.String()
    remark = graphene.String()
    weight_box = graphene.Float()
    plant = graphene.String()
    sale_org = graphene.String()
    last_update = graphene.String()
    hold_remark = graphene.String()
