# Generated by Django 3.2.13 on 2022-09-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="customer_material",
            new_name="customer_mat_35",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="material_no",
            new_name="material",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="price_group_1",
            new_name="prc_group_1",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="price_group_2",
            new_name="prc_group_2",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_group_5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sales_district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_condition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
