# Generated by Django 3.2.13 on 2022-09-20 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0006_auto_20220910_1403"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scg_checkout", "0041_alter_temporder_options"),
        ("sap_migration", "0002_auto_20220917_0820"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUnits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialVariantMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_master_data.materialmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "customer_mat_35",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("target_quantity", models.FloatField(blank=True, null=True)),
                ("sales_unit", models.CharField(blank=True, max_length=255, null=True)),
                ("plant", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "shipping_point",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("route", models.CharField(blank=True, max_length=255, null=True)),
                ("po_no", models.CharField(blank=True, max_length=255, null=True)),
                ("po_item_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "item_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prc_group_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prc_group_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("purch_nos", models.CharField(blank=True, max_length=255, null=True)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("over_delivery_tol", models.FloatField(blank=True, null=True)),
                ("under_delivery_tol", models.FloatField(blank=True, null=True)),
                (
                    "un_limit_tol",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_term_item",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("net_weight", models.FloatField(blank=True, null=True)),
                ("gross_weight", models.FloatField(blank=True, null=True)),
                (
                    "product_hierarchy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_pricing_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sales_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ref_doc", models.CharField(blank=True, max_length=255, null=True)),
                ("ref_doc_it", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("weight_unit", models.CharField(blank=True, max_length=12, null=True)),
                ("net_price", models.FloatField(blank=True, null=True)),
                ("vat_percent", models.FloatField(blank=True, null=True)),
                ("item_cat_eo", models.CharField(blank=True, max_length=12, null=True)),
                ("ref_pi_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "condition_group1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "material_group2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("commission_percent", models.FloatField(blank=True, null=True)),
                ("commission_amount", models.FloatField(blank=True, null=True)),
                (
                    "commission_unit",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("request_date", models.DateField(blank=True, null=True)),
                (
                    "roll_quantity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "roll_diameter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "roll_core_diameter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "roll_per_pallet",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "package_quantity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pallet_size", models.CharField(blank=True, max_length=12, null=True)),
                ("pallet_no", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "packing_list",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("delivery_tol_under", models.FloatField(blank=True, null=True)),
                ("delivery_tol_over", models.FloatField(blank=True, null=True)),
                ("delivery_tol_unlimited", models.BooleanField(default=False)),
                ("remark", models.TextField(blank=True, null=True)),
                ("confirmed_date", models.DateField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True, default="export", max_length=255, null=True
                    ),
                ),
                (
                    "overdue_1",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "overdue_2",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True, default="Customer", max_length=255, null=True
                    ),
                ),
                (
                    "attention_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "item_cat_pi",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price_currency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "no_of_rolls",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "no_of_package",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("eo_item_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "internal_comments_to_warehouse",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("ship_to", models.TextField(blank=True, null=True)),
                (
                    "product_information",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("dtr", models.CharField(blank=True, max_length=10, null=True)),
                ("dtp", models.CharField(blank=True, max_length=10, null=True)),
                ("original_request_date", models.DateField(blank=True, null=True)),
                ("delivery", models.CharField(blank=True, max_length=10, null=True)),
                ("actual_gi_date", models.DateField(blank=True, null=True)),
                ("gi_status", models.CharField(blank=True, max_length=1, null=True)),
                ("total_weight", models.FloatField(blank=True, null=True)),
                ("price_per_unit", models.FloatField(blank=True, null=True)),
                ("total_price", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesGroupMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesOfficeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="alternatematerialos",
            name="alternate_material",
        ),
        migrations.RemoveField(
            model_name="alternatematerialos",
            name="material_os",
        ),
        migrations.RemoveField(
            model_name="orderitems",
            name="item_no",
        ),
        migrations.RemoveField(
            model_name="orderitems",
            name="material",
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="cartlines",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="adjust_qty",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="author",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="bill_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="change_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_person",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="contract_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dlc_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dlc_latest_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dlc_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="doc_currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="end_customer",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="eo_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="eta",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="etd",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="etd_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="external_comments_to_customer",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="gw_uom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="incoterm",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="internal_comments_to_logistic",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="internal_comments_to_warehouse",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="item_note",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="lot_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="material_sales_text",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="net_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="no_of_containers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payer",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_instruction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pi_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="place_of_delivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="po_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="port_of_discharge",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="port_of_loading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="product_information",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="product_memo",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ref_pi_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="remark",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="remark_for_invoice",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="remark_for_order_information",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="request_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sales_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sales_employee",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sb_lot_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="scgp_sales_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scg_checkout.scgpsalesemployee",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_mark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="so_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="draft", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="status_sap",
            field=models.CharField(default="Being Process", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="text_in_sales_order",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price_inc_tax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="unloading_point",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="uom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="usage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cartlines",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="request_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AlternateMaterial",
        ),
        migrations.DeleteModel(
            name="AlternateMaterialOs",
        ),
        migrations.DeleteModel(
            name="OrderItems",
        ),
        migrations.AddField(
            model_name="orderlines",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sap_migration.cartlines",
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="material_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.materialvariantmaster",
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.order",
            ),
        ),
    ]
