# Generated by Django 3.2.13 on 2022-09-20 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0006_auto_20220910_1403"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_migration", "0003_auto_20220920_0701"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_material_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_own",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_master_data.materialmaster",
                    ),
                ),
                (
                    "sales_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_master_data.salesorganizationmaster",
                    ),
                ),
                (
                    "sold_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_master_data.soldtomaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_material_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "unique_together": {("sales_organization", "sold_to", "material_own")},
            },
        ),
        migrations.CreateModel(
            name="AlternateMaterialOs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                (
                    "alternate_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_migration.alternatematerial",
                    ),
                ),
                (
                    "material_os",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_master_data.materialmaster",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "alternate_material__sales_organization__code",
                    "alternate_material__sold_to__sold_to_code",
                ],
            },
        ),
    ]
