# Generated by Django 3.2.13 on 2022-09-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0007_auto_20220920_0832"),
        ("sap_migration", "0004_alternatematerial_alternatematerialos"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="currency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="delivery_over",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="delivery_under",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="plant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="price_per_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="quantity_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="remaining_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="total_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="weight_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.soldtomaster",
            ),
        ),
        migrations.AddField(
            model_name="salesgroupmaster",
            name="sales_organization_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
