# Generated by Django 3.2.13 on 2022-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0005_auto_20220920_0832"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("po_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sold_to_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "payment_term",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("incoterm", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "company_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
