# Generated by Django 3.2.13 on 2022-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0006_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="po_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
