# Generated by Django 3.2.13 on 2022-09-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0011_auto_20220920_1105"),
        ("sap_migration", "0006_contract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="contract_no",
            new_name="contract",
        ),
        migrations.RemoveField(
            model_name="salesgroupmaster",
            name="sales_organization_code",
        ),
        migrations.AddField(
            model_name="cart",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.contract",
            ),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.contract",
            ),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="contract_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.contractmaterial",
            ),
        ),
        migrations.AddField(
            model_name="salesgroupmaster",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.companymaster",
            ),
        ),
        migrations.AddField(
            model_name="salesgroupmaster",
            name="sales_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.salesorganizationmaster",
            ),
        ),
        migrations.AddField(
            model_name="salesofficemaster",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.companymaster",
            ),
        ),
        migrations.AddField(
            model_name="salesofficemaster",
            name="sales_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.salesorganizationmaster",
            ),
        ),
    ]
