# Generated by Django 3.2.13 on 2022-09-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0007_alter_order_po_date"),
        ("sap_migration", "0007_auto_20220920_1105"),
    ]

    operations = []
