# Generated by Django 3.2.13 on 2022-09-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0011_auto_20220920_1105"),
        ("sap_migration", "0007_auto_20220920_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.soldtomaster",
            ),
        ),
    ]
