# Generated by Django 3.2.13 on 2022-09-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0009_alter_contractmaterial_quantity_unit"),
        ("sap_migration", "0009_auto_20220921_0303"),
    ]

    operations = []
