# Generated by Django 3.2.13 on 2022-09-21 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0009_auto_20220921_0303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="sales_group",
        ),
        migrations.RemoveField(
            model_name="order",
            name="sales_office",
        ),
        migrations.AddField(
            model_name="order",
            name="sale_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sap_migration.salesgroupmaster",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sale_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sap_migration.salesofficemaster",
            ),
        ),
    ]
