# Generated by Django 3.2.13 on 2022-09-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0009_auto_20220921_0303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="company_code",
        ),
    ]
