# Generated by Django 3.2.13 on 2022-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0011_alter_contractmaterial_quantity_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartlines",
            name="selected",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
