# Generated by Django 3.2.13 on 2022-09-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0011_alter_order_po_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.contract",
            ),
        ),
    ]
