# Generated by Django 3.2.13 on 2022-09-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0012_cartlines_selected"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="sale_group",
            new_name="sales_group",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="sale_office",
            new_name="sales_office",
        ),
    ]
