# Generated by Django 3.2.13 on 2022-09-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0010_merge_20220921_0743"),
        ("sap_migration", "0012_alter_order_contract"),
    ]

    operations = []
