# Generated by Django 3.2.13 on 2022-09-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0008_merge_20220920_1121"),
        ("sap_migration", "0014_auto_20220921_1247"),
    ]

    operations = []
