# Generated by Django 3.2.13 on 2022-09-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0013_auto_20220921_1234"),
        ("sap_migration", "0015_merge_20220921_1411"),
    ]

    operations = []
