# Generated by Django 3.2.13 on 2022-09-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0016_merge_20220922_0327"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLineIPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attention_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("atp_ctp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "atp_ctp_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("block", models.CharField(blank=True, max_length=255, null=True)),
                ("run", models.CharField(blank=True, max_length=255, null=True)),
                ("iplant_confirm_quantity", models.FloatField(blank=True, null=True)),
                (
                    "item_status",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("original_date", models.DateField(blank=True, null=True)),
                (
                    "inquiry_method_code",
                    models.CharField(
                        blank=True, default="JIT", max_length=255, null=True
                    ),
                ),
                ("transportation_method", models.IntegerField(blank=True, null=True)),
                (
                    "type_of_delivery",
                    models.CharField(
                        blank=True, default="Arrival", max_length=255, null=True
                    ),
                ),
                (
                    "fix_source_assignment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "split_order_item",
                    models.CharField(
                        blank=True, default="Yes", max_length=255, null=True
                    ),
                ),
                (
                    "partial_delivery",
                    models.CharField(
                        blank=True, default="Yes", max_length=255, null=True
                    ),
                ),
                (
                    "consignment",
                    models.CharField(
                        blank=True,
                        default="1000 - Free Stock",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderlines",
            name="iplan",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.orderlineiplan",
            ),
        ),
    ]
