# Generated by Django 3.2.13 on 2022-09-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0016_merge_20220922_0246"),
        ("sap_migration", "0017_auto_20220922_0429"),
    ]

    operations = []
