# Generated by Django 3.2.13 on 2022-09-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0018_merge_20220922_0709"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractmaterial",
            options={"ordering": ["remaining_quantity", "pk"]},
        ),
    ]
