# Generated by Django 3.2.13 on 2022-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0019_alter_contractmaterial_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="net_price",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
