# Generated by Django 3.2.13 on 2022-09-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0014_alter_companymaster_business_unit"),
        ("sap_migration", "0020_alter_order_net_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.companymaster",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="credit_status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dp_no",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
