# Generated by Django 3.2.13 on 2022-09-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0016_merge_20220927_1154"),
        ("sap_migration", "0021_auto_20220926_1822"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="bill_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="distribution_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.distributionchannelmaster",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.divisionmaster",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="external_comment_to_customers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="internal_comment_to_warehouse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="po_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="production_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="sales_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sap_migration.salesgroupmaster",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="sales_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sap_migration.salesofficemaster",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="sales_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.salesorganizationmaster",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="ship_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
