# Generated by Django 3.2.13 on 2022-09-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0016_merge_20220927_1154"),
        ("sap_migration", "0021_auto_20220926_1822"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_group_5",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.customergroup1master",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.customergroup2master",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.customergroup3master",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_group_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.customergroup4master",
            ),
        ),
    ]
