# Generated by Django 3.2.13 on 2022-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0022_auto_20220928_0852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="external_comment_to_customers",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="internal_comment_to_warehouse",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="production_information",
        ),
        migrations.AddField(
            model_name="contract",
            name="external_comments_to_customer",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="internal_comments_to_warehouse",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="product_information",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="bill_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="external_comments_to_customer",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="internal_comments_to_logistic",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
