# Generated by Django 3.2.13 on 2022-09-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0022_auto_20220928_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="payment_condition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="po_no_external",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="request_date_change_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
