# Generated by Django 3.2.13 on 2022-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0023_auto_20220928_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="status",
            field=models.CharField(default="Enable", max_length=250),
        ),
    ]
