# Generated by Django 3.2.13 on 2022-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0024_merge_0023_auto_20220928_1025_0023_auto_20220928_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="eo_upload_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="eo_upload_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
