# Generated by Django 3.2.13 on 2022-09-29 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_migration", "0024_merge_0023_auto_20220928_1025_0023_auto_20220928_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="update_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
