# Generated by Django 3.2.13 on 2022-09-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0024_merge_0023_auto_20220928_1025_0023_auto_20220928_1345"),
        ("sap_migration", "0024_orderlines_status"),
    ]

    operations = []
