# Generated by Django 3.2.13 on 2022-09-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0025_auto_20220929_0710"),
        ("sap_migration", "0025_merge_20220929_0409"),
        ("sap_migration", "0025_order_update_by"),
    ]

    operations = []
