# Generated by Django 3.2.13 on 2022-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0026_merge_20220929_1010"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialvariantmaster",
            name="description_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="description_th",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="determine_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="key_combination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="propose_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="sales_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialvariantmaster",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
