# Generated by Django 3.2.13 on 2022-09-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0027_auto_20220930_0445"),
        ("sap_migration", "0027_auto_20220930_0604"),
    ]

    operations = []
