# Generated by Django 3.2.13 on 2022-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0028_merge_0027_auto_20220930_0445_0027_auto_20220930_0604"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sap_order_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
