# Generated by Django 3.2.13 on 2022-09-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0029_order_sap_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatematerialos",
            name="diameter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="basis_weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="diameter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="materialvariantmaster",
            name="grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="alternatematerial",
            name="material_own",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.materialvariantmaster",
            ),
        ),
        migrations.AlterField(
            model_name="alternatematerialos",
            name="material_os",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_migration.materialvariantmaster",
            ),
        ),
    ]
