# Generated by Django 3.2.13 on 2022-10-03 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0017_incoterm1master"),
        ("sap_migration", "0030_auto_20220930_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="incoterms_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sap_master_data.incoterms1master",
            ),
        ),
    ]
