# Generated by Django 3.2.13 on 2022-10-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0030_auto_20220930_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="etd",
            field=models.DateField(blank=True, null=True),
        ),
    ]
