# Generated by Django 3.2.13 on 2022-10-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0031_alter_order_etd"),
        ("sap_migration", "0031_alter_order_incoterms_1"),
    ]

    operations = []
