# Generated by Django 3.2.13 on 2022-10-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0032_merge_20221004_1009"),
        ("sap_migration", "0033_merge_20221004_1107"),
    ]

    operations = []
