# Generated by Django 3.2.13 on 2022-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0035_merge_20221004_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="original_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
