# Generated by Django 3.2.13 on 2022-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0035_merge_20221004_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="production_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
