# Generated by Django 3.2.13 on 2022-10-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0036_alter_orderlines_original_quantity"),
        ("sap_migration", "0036_orderlines_production_status"),
    ]

    operations = []
