# Generated by Django 3.2.13 on 2022-10-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0037_merge_20221005_1208"),
        ("sap_migration", "0037_orderlineiplan_paper_machine"),
        ("sap_migration", "0037_orderlines_atp_ctp_status"),
    ]

    operations = []
