# Generated by Django 3.2.13 on 2022-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0038_merge_20221006_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="external_comments_to_customer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="internal_comments_to_logistic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="internal_comments_to_warehouse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlines",
            name="external_comments_to_customer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlines",
            name="internal_comments_to_logistic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlines",
            name="internal_comments_to_warehouse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlines",
            name="product_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
