# Generated by Django 3.2.13 on 2022-10-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0038_merge_20221006_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="i_plan_on_hand_stock",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
