# Generated by Django 3.2.13 on 2022-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0039_auto_20221011_0334"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_thai",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
