# Generated by Django 3.2.13 on 2022-10-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0039_orderlines_i_plan_on_hand_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="i_plan_operations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
