# Generated by Django 3.2.13 on 2022-10-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0039_auto_20221011_0334"),
        ("sap_migration", "0040_orderlines_i_plan_operations"),
    ]

    operations = []
