# Generated by Django 3.2.13 on 2022-10-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0040_order_status_thai"),
        ("sap_migration", "0041_merge_20221011_1053"),
    ]

    operations = []
