# Generated by Django 3.2.13 on 2022-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0041_merge_20221011_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="inquiry_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
