# Generated by Django 3.2.13 on 2022-10-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0042_merge_0040_order_status_thai_0041_merge_20221011_1053"),
        ("sap_migration", "0042_orderlines_inquiry_method"),
    ]

    operations = []
