# Generated by Django 3.2.13 on 2022-10-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0043_merge_20221012_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="assigned_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="item_status_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="item_status_th",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
