# Generated by Django 3.2.13 on 2022-10-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0044_auto_20221013_0515"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="web_user_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
