# Generated by Django 3.2.13 on 2022-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0045_order_web_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="sap_confirm_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
