# Generated by Django 3.2.13 on 2022-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0046_orderlines_sap_confirm_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="delivery_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="net_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
