# Generated by Django 3.2.13 on 2022-10-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0046_orderlines_sap_confirm_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="item_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
