# Generated by Django 3.2.13 on 2022-10-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0047_contractmaterial_item_no"),
        ("sap_migration", "0048_route"),
    ]

    operations = []
