# Generated by Django 3.2.13 on 2022-10-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0049_merge_0047_contractmaterial_item_no_0048_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialvariantmaster",
            name="variant_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
