# Generated by Django 3.2.13 on 2022-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0050_materialvariantmaster_variant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialvariantmaster",
            name="item_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
