# Generated by Django 3.2.13 on 2022-11-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0051_materialvariantmaster_item_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineiplan",
            name="atp_ctp_detail",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
