# Generated by Django 3.2.13 on 2022-11-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0051_materialvariantmaster_item_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="unloading_point",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
