# Generated by Django 3.2.13 on 2022-11-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0052_contract_unloading_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialvariantmaster",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
