# Generated by Django 3.2.13 on 2022-11-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0052_contract_unloading_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sold_to_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
