# Generated by Django 3.2.13 on 2022-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0053_order_sold_to_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="etd",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
