# Generated by Django 3.2.13 on 2022-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0054_alter_order_etd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
