# Generated by Django 3.2.13 on 2022-11-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0052_alter_orderlineiplan_atp_ctp_detail"),
        ("sap_migration", "0055_alter_order_remark"),
    ]

    operations = []
