# Generated by Django 3.2.13 on 2022-11-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0053_alter_materialvariantmaster_code"),
        ("sap_migration", "0055_alter_order_remark"),
    ]

    operations = []
