# Generated by Django 3.2.13 on 2022-11-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0056_merge_20221103_0651"),
        ("sap_migration", "0056_merge_20221103_0756"),
    ]

    operations = []
