# Generated by Django 3.2.13 on 2022-11-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0057_merge_20221103_0832"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialvariantmaster",
            name="item_no",
        ),
    ]
