# Generated by Django 3.2.13 on 2022-11-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0058_remove_materialvariantmaster_item_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
