# Generated by Django 3.2.13 on 2022-11-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0059_order_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="confirm_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="non_confirm_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
