# Generated by Django 3.2.13 on 2022-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0061_contract_payment_term_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
