# Generated by Django 3.2.13 on 2022-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0062_contract_shipping_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="end_customer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
