# Generated by Django 3.2.13 on 2022-11-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0061_contract_payment_term_key"),
        ("sap_migration", "0063_contract_end_customer"),
    ]

    operations = []
