# Generated by Django 3.2.13 on 2022-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0062_contract_currency"),
        ("sap_migration", "0064_merge_20221116_1447"),
    ]

    operations = []
