# Generated by Django 3.2.13 on 2022-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0065_merge_0062_contract_currency_0064_merge_20221116_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="payment_term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
