# Generated by Django 3.2.13 on 2022-11-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0066_auto_20221117_0747"),
        ("sap_migration", "0066_contractmaterial_payment_term"),
    ]

    operations = []
