# Generated by Django 3.2.13 on 2022-11-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0067_merge_20221117_1057"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="remark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
