# Generated by Django 3.2.13 on 2022-11-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0068_contract_remark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="eo_upload_created",
        ),
        migrations.RemoveField(
            model_name="order",
            name="eo_upload_updated",
        ),
    ]
