# Generated by Django 3.2.13 on 2022-11-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0068_contract_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="com_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="commission",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="commission_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contractmaterial",
            name="condition_group1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
