# Generated by Django 3.2.13 on 2022-11-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0069_auto_20221117_1345"),
        ("sap_migration", "0069_auto_20221118_0710"),
    ]

    operations = []
