# Generated by Django 3.2.13 on 2022-11-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sap_master_data",
            "0020_salesgroup_soldtoexternalsalesarea_soldtoexternalsalesgroup",
        ),
        ("sap_migration", "0070_merge_0069_auto_20221117_1345_0069_auto_20221118_0710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="contractmaterial",
            unique_together={("item_no", "material_id", "contract_id")},
        ),
    ]
