# Generated by Django 3.2.13 on 2022-11-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0071_auto_20221118_0858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="internal_comments_to_warehouse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_instruction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="production_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="remark_for_order_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
