# Generated by Django 3.2.13 on 2022-11-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0072_auto_20221121_0310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="eta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
