# Generated by Django 3.2.13 on 2022-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0073_alter_order_eta"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="incoterms_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="prc_group1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
