# Generated by Django 3.2.13 on 2022-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0074_auto_20221121_1005"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="material_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
