# Generated by Django 3.2.13 on 2022-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0075_contractmaterial_material_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="eta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="etd",
            field=models.DateField(blank=True, null=True),
        ),
    ]
