# Generated by Django 3.2.13 on 2022-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0075_contractmaterial_material_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="original_item_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
