# Generated by Django 3.2.13 on 2022-12-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0076_auto_20221205_0738"),
        ("sap_migration", "0076_orderlines_original_item_no"),
    ]

    operations = []
