# Generated by Django 3.2.13 on 2022-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0077_merge_20221205_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="mat_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
