# Generated by Django 3.2.13 on 2022-12-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0077_merge_20221205_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
