# Generated by Django 3.2.13 on 2022-12-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0078_alter_order_payer"),
        ("sap_migration", "0078_contractmaterial_mat_type"),
    ]

    operations = []
