# Generated by Django 3.2.13 on 2022-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0079_merge_20221206_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="mat_group_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
