# Generated by Django 3.2.13 on 2022-12-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0079_merge_20221206_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="surname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
