# Generated by Django 3.2.13 on 2022-12-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0080_contract_surname"),
        ("sap_migration", "0080_contractmaterial_mat_group_1"),
    ]

    operations = []
