# Generated by Django 3.2.13 on 2022-12-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0081_merge_20221213_0757"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="internal_comments_to_logistic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="external_comments_to_customer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
