# Generated by Django 3.2.13 on 2022-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0082_auto_20221214_0428"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="remark_for_logistic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
