# Generated by Django 3.2.13 on 2023-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0083_order_remark_for_logistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="shipping_mark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
