# Generated by Django 3.2.13 on 2023-01-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0083_order_remark_for_logistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
