# Generated by Django 3.2.13 on 2023-01-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0083_order_remark_for_logistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="delivery_tol_unlimited",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
