# Generated by Django 3.2.13 on 2023-01-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0084_alter_orderlines_delivery_tol_unlimited"),
        ("sap_migration", "0084_orderlines_shipping_mark"),
        ("sap_migration", "0085_alter_contract_shipping_mark"),
    ]

    operations = []
