# Generated by Django 3.2.13 on 2023-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0087_orderlines_call_atp_ctp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_by_flow",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
