# Generated by Django 3.2.13 on 2023-01-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0087_orderlines_call_atp_ctp"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLineDeliveries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_order", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sales_order_item",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("delivery", models.CharField(blank=True, max_length=255, null=True)),
                ("actual_gi_date", models.DateField(blank=True, null=True)),
                ("gi_status", models.CharField(blank=True, max_length=255, null=True)),
                ("sales_org", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "distribution_channel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_point",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_migration.orderlines",
                    ),
                ),
            ],
        ),
    ]
