# Generated by Django 3.2.13 on 2023-01-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0088_order_created_by_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineiplan",
            name="consignment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineiplan",
            name="inquiry_method_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineiplan",
            name="item_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineiplan",
            name="partial_delivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineiplan",
            name="split_order_item",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineiplan",
            name="transportation_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineiplan",
            name="type_of_delivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
