# Generated by Django 3.2.13 on 2023-01-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0088_orderlinedeliveries"),
        ("sap_migration", "0089_auto_20230118_0725"),
    ]

    operations = []
