# Generated by Django 3.2.13 on 2023-01-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0090_merge_20230119_0447"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTextLang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_id", models.CharField(blank=True, max_length=10, null=True)),
                ("item_no", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_migration.contract",
                    ),
                ),
            ],
        ),
    ]
