# Generated by Django 3.2.13 on 2023-01-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0091_ordertextlang"),
        ("sap_migration", "0091_sqslog"),
    ]

    operations = []
