# Generated by Django 3.2.13 on 2023-02-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0092_merge_0091_ordertextlang_0091_sqslog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordertextlang",
            unique_together={("contract", "text_id", "item_no")},
        ),
    ]
