# Generated by Django 3.2.13 on 2023-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0093_alter_ordertextlang_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item_no_latest",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
