# Generated by Django 3.2.13 on 2023-02-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0094_order_item_no_latest"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineiplan",
            name="iplant_confirm_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="orderlineiplan",
            name="item_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlineiplan",
            name="on_hand_stock",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="orderlineiplan",
            name="order_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
