# Generated by Django 3.2.13 on 2023-02-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0094_order_item_no_latest"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="usage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
