# Generated by Django 3.2.13 on 2023-02-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0095_alter_orderline_call_apt_ctp"),
        ("sap_migration", "0095_contract_usage"),
    ]

    operations = []
