# Generated by Django 3.2.13 on 2023-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0097_auto_20230206_0806"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="return_status",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
