# Generated by Django 3.2.13 on 2023-02-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0098_orderlines_dtr_dtp_handled"),
        ("sap_migration", "0098_orderlines_return_status"),
    ]

    operations = []
