# Generated by Django 3.2.13 on 2023-02-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0099_merge_20230208_0428"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="eta_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="etd_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="external_comments_to_customer_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="gw_uom_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="internal_comments_to_logistic_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="internal_comments_to_warehouse_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="no_of_containers_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_instruction_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="port_of_discharge_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="port_of_loading_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="production_information_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="remark_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="shipping_mark_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="surname_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="uom_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
