# Generated by Django 3.2.13 on 2023-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0100_auto_20230209_0713"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="web_user_line_lang",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
