# Generated by Django 3.2.13 on 2023-02-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0101_contract_web_user_line_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineiplan",
            name="plant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
