# Generated by Django 3.2.13 on 2023-02-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0007_eouploadlog_eo_no"),
        ("sap_migration", "0102_orderlineiplan_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="eo_upload_log",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scgp_eo_upload.eouploadlog",
            ),
        ),
    ]
