# Generated by Django 3.2.13 on 2023-02-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0102_orderlineiplan_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="over_delivery_tol",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlines",
            name="under_delivery_tol",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
