# Generated by Django 3.2.13 on 2023-02-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0103_auto_20230214_0540"),
        ("sap_migration", "0103_order_eo_upload_log"),
    ]

    operations = []
