# Generated by Django 3.2.13 on 2023-02-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0104_merge_20230215_0849"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="usage_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
