# Generated by Django 3.2.13 on 2023-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0105_contract_usage_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="item_status_en_rollback",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
