# Generated by Django 3.2.13 on 2023-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0106_orderlines_item_status_en_rollback"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="web_user_line",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
