# Generated by Django 3.2.13 on 2023-02-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0107_contract_web_user_line"),
        ("sap_migration", "0107_orderlineiplan_request_iplan_response"),
    ]

    operations = []
