# Generated by Django 3.2.13 on 2023-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0108_merge_20230223_0351"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="route_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
