# Generated by Django 3.2.13 on 2023-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0109_orderlines_route_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="saved_sap_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
