# Generated by Django 3.2.13 on 2023-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0110_order_saved_sap_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="sap_confirm_qty",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
