# Generated by Django 3.2.13 on 2023-03-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0111_orderlines_sap_confirm_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="remaining_quantity_ex",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
