# Generated by Django 3.2.13 on 2023-04-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0112_contractmaterial_remaining_quantity_ex"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="weight_display",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
