# Generated by Django 3.2.13 on 2023-05-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0113_orderlines_weight_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="po_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="po_sub_contract",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
