# Generated by Django 3.2.13 on 2023-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0114_auto_20230509_0437"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="materialvariantmaster",
            index=models.Index(fields=["code"], name="sap_migrati_code_f39f7b_idx"),
        ),
        migrations.AddIndex(
            model_name="materialvariantmaster",
            index=models.Index(
                fields=["material"], name="sap_migrati_materia_f90c47_idx"
            ),
        ),
    ]
