# Generated by Django 3.2.13 on 2023-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0115_auto_20230518_0922"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="materialvariantmaster",
            index=models.Index(
                fields=["variant_type"], name="sap_migrati_variant_c696b4_idx"
            ),
        ),
    ]
