# Generated by Django 3.2.13 on 2023-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0117_order_po_upload_file_log"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contractmaterial",
            index=models.Index(
                fields=["contract"], name="sap_migrati_contrac_9d0a50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractmaterial",
            index=models.Index(
                fields=["material"], name="sap_migrati_materia_1deb27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractmaterial",
            index=models.Index(
                fields=["material_code"], name="sap_migrati_materia_55c24a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractmaterial",
            index=models.Index(
                fields=["contract_no"], name="sap_migrati_contrac_f75690_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractmaterial",
            index=models.Index(fields=["plant"], name="sap_migrati_plant_9536b3_idx"),
        ),
    ]
