# Generated by Django 3.2.13 on 2023-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0120_alternatematerialosmappingfilelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
