# Generated by Django 3.2.13 on 2023-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0120_alternatematerialosmappingfilelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="class_mark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
