# Generated by Django 3.2.13 on 2023-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0120_alternatematerialosmappingfilelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="gross_weight_ton",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="net_weight_ton",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="weight_unit_ton",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
