# Generated by Django 3.2.13 on 2023-09-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0121_orderlines_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlines",
            name="remarks",
        ),
    ]
