# Generated by Django 3.2.13 on 2023-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0122_remove_orderlines_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="additional_remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
