# Generated by Django 3.2.13 on 2023-09-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0121_auto_20230920_0952"),
        ("sap_migration", "0123_orderlines_additional_remark"),
    ]

    operations = []
