# Generated by Django 3.2.13 on 2023-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0123_orderlines_additional_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="pr_items",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="pr_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
