# Generated by Django 3.2.13 on 2023-09-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0124_auto_20230919_1011"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderlines",
            old_name="pr_items",
            new_name="pr_item",
        ),
    ]
