# Generated by Django 3.2.13 on 2023-09-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0124_merge_20230921_0619"),
        ("sap_migration", "0125_rename_pr_items_orderlines_pr_item"),
    ]

    operations = []
