# Generated by Django 3.2.13 on 2023-10-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0121_orderlines_class_mark"),
        ("sap_migration", "0126_merge_20230928_0553"),
    ]

    operations = []
