# Generated by Django 3.2.13 on 2023-10-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0029_auto_20230623_0642"),
        ("sap_migration", "0127_merge_20231019_0516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternatematerial",
            name="material_own",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.materialmaster",
            ),
        ),
        migrations.AlterField(
            model_name="alternatematerialos",
            name="material_os",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.materialmaster",
            ),
        ),
    ]
