# Generated by Django 3.2.13 on 2023-10-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0128_auto_20231019_1417"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternatematerialos",
            options={"ordering": []},
        ),
    ]
