# Generated by Django 3.2.13 on 2023-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0129_alter_alternatematerialos_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="additional_remark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
