# Generated by Django 3.2.13 on 2023-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0130_contractmaterial_additional_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmaterial",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
