# Generated by Django 3.2.13 on 2023-12-08 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_master_data", "0031_auto_20231208_0631"),
        ("sap_migration", "0130_contractmaterial_additional_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderOtcPartnerAddress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address_code", models.CharField(max_length=10, null=True)),
                ("name1", models.CharField(max_length=255, null=True)),
                ("name2", models.CharField(max_length=255, null=True)),
                ("name3", models.CharField(max_length=255, null=True)),
                ("name4", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("postal_code", models.CharField(max_length=10, null=True)),
                ("district", models.CharField(max_length=50, null=True)),
                ("street_1", models.CharField(max_length=255, null=True)),
                ("street_2", models.CharField(max_length=255, null=True)),
                ("street_3", models.CharField(max_length=255, null=True)),
                ("street_4", models.CharField(max_length=255, null=True)),
                ("location", models.CharField(max_length=255, null=True)),
                ("transport_zone_code", models.CharField(max_length=10, null=True)),
                ("transport_zone_name", models.CharField(max_length=50, null=True)),
                ("country_code", models.CharField(max_length=10, null=True)),
                ("country_name", models.CharField(max_length=50, null=True)),
                ("telephone_no", models.CharField(max_length=50, null=True)),
                ("telephone_extension", models.CharField(max_length=50, null=True)),
                ("mobile_no", models.CharField(max_length=50, null=True)),
                ("fax_no", models.CharField(max_length=50, null=True)),
                ("fax_no_ext", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("language", models.CharField(max_length=3)),
                ("taxNumber1", models.CharField(max_length=50, null=True)),
                ("taxNumber2", models.CharField(max_length=50, null=True)),
                ("created_date", models.DateField()),
                ("created_by_id", models.IntegerField()),
                ("last_updated_date", models.DateField()),
                ("last_updated_by_id", models.IntegerField()),
            ],
            options={
                "db_table": "sap_migration_order_otc_partneraddress",
            },
        ),
        migrations.AddField(
            model_name="orderlines",
            name="batch_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="bom_flag",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="bom_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sap_master_data.bommaterial",
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="price_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OrderOtcPartner",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sold_to_code", models.CharField(max_length=10, null=True)),
                ("partner_role", models.CharField(max_length=10, null=True)),
                ("created_date", models.DateField()),
                ("created_by_id", models.IntegerField()),
                ("last_updated_date", models.DateField()),
                ("last_updated_by_id", models.IntegerField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_migration.orderotcpartneraddress",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_migration.order",
                    ),
                ),
            ],
            options={
                "db_table": "sap_migration_order_otc_partner",
            },
        ),
        migrations.CreateModel(
            name="OrderlineCp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("temporder_no", models.CharField(max_length=20)),
                ("orderline_id", models.BigIntegerField()),
                ("item_no", models.CharField(max_length=10)),
                ("material_code", models.CharField(max_length=50)),
                ("confirm_date", models.DateField()),
                ("plant", models.CharField(max_length=50)),
                ("material_bom", models.CharField(max_length=500)),
                ("created_date", models.DateField()),
                ("created_by_id", models.IntegerField()),
                ("last_updated_date", models.DateField()),
                ("last_updated_by_id", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sap_migration.order",
                    ),
                ),
            ],
            options={
                "db_table": "sap_migration_orderline_cp",
            },
        ),
        migrations.CreateModel(
            name="OrderExtension",
            fields=[
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sap_migration.order",
                    ),
                ),
                ("bu", models.CharField(default="PP", max_length=10)),
                ("order_amt_before_vat", models.FloatField(null=True)),
                ("order_amt_vat", models.FloatField(null=True)),
                ("order_amt_after_vat", models.FloatField(null=True)),
                ("currency", models.CharField(max_length=10, null=True)),
                ("additional_txt_from_header", models.TextField(null=True)),
                ("additional_txt_header_note1", models.TextField(null=True)),
                ("additional_txt_cash", models.TextField(null=True)),
                ("created_date", models.DateField(null=True)),
                ("created_by_id", models.IntegerField(null=True)),
                ("last_updated_date", models.DateField(null=True)),
                ("last_updated_by_id", models.IntegerField(null=True)),
                (
                    "otc_bill_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderextension_billto",
                        to="sap_migration.orderotcpartner",
                    ),
                ),
                (
                    "otc_ship_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderextension_shipto",
                        to="sap_migration.orderotcpartner",
                    ),
                ),
                (
                    "otc_sold_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderextension_soldto",
                        to="sap_migration.orderotcpartner",
                    ),
                ),
            ],
            options={
                "db_table": "sap_migration_orderextension",
            },
        ),
    ]
