# Generated by Django 3.2.13 on 2023-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0131_auto_20231208_0631"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderextension",
            name="tax_class",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
