# Generated by Django 3.2.13 on 2024-02-21 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import scgp_po_upload.s3_storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_migration", "0131_contractmaterial_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMaterialMappingFileLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        storage=scgp_po_upload.s3_storage.EOrderingS3Storage(),
                        upload_to="customer_material_mapping_files",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_material_mapping_file_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
