# Generated by Django 3.2.13 on 2024-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0131_contractmaterial_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
