# Generated by Django 3.2.13 on 2024-02-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0132_customermaterialmappingfilelog"),
        ("sap_migration", "0132_order_product_group"),
    ]

    operations = []
