# Generated by Django 3.2.13 on 2023-12-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0132_orderextension_tax_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlines",
            name="bom_material",
        ),
        migrations.AddField(
            model_name="orderlines",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_parent",
                to="sap_migration.orderlines",
            ),
        ),
    ]
