# Generated by Django 3.2.13 on 2023-12-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_migration", "0132_orderextension_tax_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderextension",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="orderextension",
            name="last_updated_by_id",
        ),
        migrations.RemoveField(
            model_name="orderotcpartner",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="orderotcpartner",
            name="last_updated_by_id",
        ),
        migrations.RemoveField(
            model_name="orderotcpartneraddress",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="orderotcpartneraddress",
            name="last_updated_by_id",
        ),
        migrations.AddField(
            model_name="orderextension",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderextension_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderextension",
            name="last_updated_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderextension_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="batch_choice_flag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="item_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="lot_no",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="pr_item_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="production_flag",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="production_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="sale_text1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="sale_text2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="sale_text3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="sale_text4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderotcpartner",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otc_partner_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderotcpartner",
            name="last_updated_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otc_partner_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderotcpartneraddress",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otc_partneraddress_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderotcpartneraddress",
            name="last_updated_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otc_partneraddress_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="update_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderextension",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderextension",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlinecp",
            name="created_by_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Orderlinecp_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderlinecp",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlinecp",
            name="last_updated_by_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Orderlinecp_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderlinecp",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderotcpartner",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderotcpartner",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderotcpartneraddress",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderotcpartneraddress",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
