# Generated by Django 3.2.13 on 2023-12-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0133_auto_20231218_1102"),
        ("sap_migration", "0133_auto_20231218_1350"),
    ]

    operations = []
