# Generated by Django 3.2.13 on 2024-01-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0131_contractmaterial_is_active"),
        ("sap_migration", "0134_merge_0133_auto_20231218_1102_0133_auto_20231218_1350"),
    ]

    operations = []
