# Generated by Django 3.2.13 on 2024-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0136_orderlines_otc_ship_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderotcpartneraddress",
            old_name="taxNumber1",
            new_name="tax_number1",
        ),
        migrations.RenameField(
            model_name="orderotcpartneraddress",
            old_name="taxNumber2",
            new_name="tax_number2",
        ),
        migrations.AddField(
            model_name="orderotcpartneraddress",
            name="branch_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderotcpartneraddress",
            name="tax_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
