# Generated by Django 3.2.13 on 2024-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0137_auto_20240111_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderextension",
            name="temp_order_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
