# Generated by Django 3.2.13 on 2024-01-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0138_orderextension_temp_order_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlinecp",
            name="temporder_no",
        ),
    ]
