# Generated by Django 3.2.13 on 2024-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0140_auto_20240125_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlinecp",
            name="material_bom",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
