# Generated by Django 3.2.13 on 2024-02-19 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sap_migration", "0141_alter_orderlinecp_material_bom"),
    ]

    operations = []
