# Generated by Django 3.2.13 on 2024-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0142_customermaterialmappingfilelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="sales_qty_factor",
            field=models.TextField(blank=True, null=True),
        ),
    ]
