# Generated by Django 3.2.13 on 2024-02-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0132_order_product_group"),
        ("sap_migration", "0143_orderlines_sales_qty_factor"),
    ]

    operations = []
