# Generated by Django 3.2.13 on 2024-03-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0133_merge_20240229_0607"),
        ("sap_migration", "0144_merge_20240229_0458"),
    ]

    operations = []
