# Generated by Django 3.2.13 on 2024-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0145_merge_20240307_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="force_flag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="orderlinecp",
            unique_together={("item_no", "order_id")},
        ),
    ]
