# Generated by Django 3.2.13 on 2024-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sap_migration", "0146_auto_20240417_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bill_to",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_to",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
