import pytest

from saleor.graphql.tests.fixtures import ApiClient
from scg_checkout.models import SalesOrganization
from scgp_export.graphql.enums import ScgpExportOrder
from scgp_export.models import (
    ExportCart,
    ExportCartItem,
    ExportOrder,
    ExportOrderLine,
    ExportPI,
    ExportPIProduct,
    ExportProduct,
    ExportSoldTo,
)


@pytest.fixture
def scgp_export_sold_tos(db):
    return ExportSoldTo.objects.bulk_create(
        [
            ExportSoldTo(
                code="sold_to_1", name="Sold To 1", address_text="Sold To Address 1"
            ),
            ExportSoldTo(
                code="sold_to_2", name="Sold To 2", address_text="Sold To Address 2"
            ),
            ExportSoldTo(
                code="sold_to_3", name="Sold To 3", address_text="Sold To Address 3"
            ),
        ]
    )


@pytest.fixture
def scgp_export_products(db):
    return ExportProduct.objects.bulk_create(
        [
            ExportProduct(name="Product 1", slug="PR1"),
            ExportProduct(name="Product 2", slug="PR2"),
            ExportProduct(name="Product 3", slug="PR3"),
        ]
    )


@pytest.fixture
def scgp_export_pis(db, scgp_export_sold_tos):
    return ExportPI.objects.bulk_create(
        [
            ExportPI(
                sold_to=scgp_export_sold_tos[0],
                code="pi_1",
                po_no="po_no_1",
                sold_to_name="Sold To Name 1",
                ship_to_name="Ship To Name 1",
                ship_to_country="Ship To Country 1",
                incoterm="inco1",
                payment_term="term_1",
            ),
            ExportPI(
                sold_to=scgp_export_sold_tos[1],
                code="pi_2",
                po_no="po_no_2",
                sold_to_name="Sold To Name 2",
                ship_to_name="Ship To Name 2",
                ship_to_country="Ship To Country 2",
                incoterm="inco2",
                payment_term="term_2",
            ),
            ExportPI(
                sold_to=scgp_export_sold_tos[2],
                code="pi_3",
                po_no="po_no_3",
                sold_to_name="Sold To Name 3",
                ship_to_name="Ship To Name 3",
                ship_to_country="Ship To Country 3",
                incoterm="inco3",
                payment_term="term_3",
            ),
            ExportPI(
                sold_to=scgp_export_sold_tos[0],
                code="pi_4",
                po_no="po_no_4",
                sold_to_name="Sold To Name 4",
                ship_to_name="Ship To Name 4",
                ship_to_country="Ship To Country 4",
                incoterm="inco4",
                payment_term="term_4",
            ),
        ]
    )


@pytest.fixture
def scgp_export_pi_products(
    db, scgp_export_sold_tos, scgp_export_pis, scgp_export_products
):
    return ExportPIProduct.objects.bulk_create(
        [
            ExportPIProduct(
                total_quantity=10000,
                remaining_quantity=1000,
                price_per_unit=100,
                quantity_unit="test",
                currency="BTH",
                weight=50,
                weight_unit="test",
                pi=scgp_export_pis[0],
                product=scgp_export_products[0],
            ),
            ExportPIProduct(
                total_quantity=12000,
                remaining_quantity=9500,
                price_per_unit=100,
                quantity_unit="test",
                currency="BTH",
                weight=50,
                weight_unit="test",
                pi=scgp_export_pis[0],
                product=scgp_export_products[1],
            ),
            ExportPIProduct(
                total_quantity=11000,
                remaining_quantity=3400,
                price_per_unit=100,
                quantity_unit="test",
                currency="BTH",
                weight=50,
                weight_unit="test",
                pi=scgp_export_pis[1],
                product=scgp_export_products[2],
            ),
            ExportPIProduct(
                total_quantity=11000,
                remaining_quantity=3400,
                price_per_unit=120,
                quantity_unit="test",
                currency="BTH",
                weight=50,
                weight_unit="test",
                pi=scgp_export_pis[1],
                product=scgp_export_products[1],
            ),
            ExportPIProduct(
                total_quantity=11000,
                remaining_quantity=3400,
                price_per_unit=120,
                quantity_unit="test",
                currency="BTH",
                weight=50,
                weight_unit="test",
                pi=scgp_export_pis[1],
                product=scgp_export_products[0],
            ),
        ]
    )


@pytest.fixture
def scgp_export_carts(db, scgp_export_pis, scgp_export_sold_tos, customers_for_search):
    return ExportCart.objects.bulk_create(
        [
            ExportCart(
                pi=scgp_export_pis[0],
                sold_to=scgp_export_sold_tos[0],
                created_by=customers_for_search[0],
            ),
            ExportCart(
                pi=scgp_export_pis[1],
                sold_to=scgp_export_sold_tos[1],
                created_by=customers_for_search[0],
            ),
            ExportCart(
                pi=scgp_export_pis[2],
                sold_to=scgp_export_sold_tos[1],
                created_by=customers_for_search[0],
            ),
            ExportCart(
                pi=scgp_export_pis[3],
                sold_to=scgp_export_sold_tos[2],
                created_by=customers_for_search[1],
            ),
            ExportCart(
                pi=scgp_export_pis[3],
                sold_to=scgp_export_sold_tos[2],
                created_by=customers_for_search[2],
            ),
            ExportCart(
                pi=scgp_export_pis[0],
                sold_to=scgp_export_sold_tos[2],
                created_by=customers_for_search[2],
            ),
        ]
    )


@pytest.fixture
def scgp_export_cart_items(db, scgp_export_carts, scgp_export_pi_products):
    return ExportCartItem.objects.bulk_create(
        [
            ExportCartItem(
                cart=scgp_export_carts[0],
                pi_product=scgp_export_pi_products[0],
                quantity=100,
            ),
            ExportCartItem(
                cart=scgp_export_carts[0],
                pi_product=scgp_export_pi_products[1],
                quantity=101,
            ),
            ExportCartItem(
                cart=scgp_export_carts[1],
                pi_product=scgp_export_pi_products[2],
                quantity=102,
            ),
            ExportCartItem(
                cart=scgp_export_carts[3],
                pi_product=scgp_export_pi_products[0],
                quantity=1000,
            ),
            ExportCartItem(
                cart=scgp_export_carts[3],
                pi_product=scgp_export_pi_products[1],
                quantity=1001,
            ),
            ExportCartItem(
                cart=scgp_export_carts[4],
                pi_product=scgp_export_pi_products[0],
                quantity=10000,
            ),
            ExportCartItem(
                cart=scgp_export_carts[4],
                pi_product=scgp_export_pi_products[1],
                quantity=100001,
            ),
            ExportCartItem(
                cart=scgp_export_carts[4],
                pi_product=scgp_export_pi_products[2],
                quantity=100002,
            ),
            ExportCartItem(
                cart=scgp_export_carts[5],
                pi_product=scgp_export_pi_products[2],
                quantity=500,
            ),
        ]
    )


@pytest.fixture
def user1_logged(db, customers_for_search):
    return ApiClient(user=customers_for_search[0])


@pytest.fixture
def scgp_export_orders(
    db,
    customers_for_search,
    scgp_export_pis,
    scg_checkout_distribution_channel,
    scg_checkout_sales_organization,
    scg_checkout_division,
    scg_checkout_sales_office,
    scg_checkout_sales_group,
):
    return ExportOrder.objects.bulk_create(
        [
            ExportOrder(
                pi=scgp_export_pis[0],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="draft",
                payment_term="LC00",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[0],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
                    TOAN LUC PAPER JOINT STOCK COMPANY
                    TL-032021
                    STUFFING 28X40' FCL
                    TO PORT CAT LAI / VIETNAM
                """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
            ),
            ExportOrder(
                pi=scgp_export_pis[1],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="draft",
                payment_term="LC01",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[0],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
                        TOAN LUC PAPER JOINT STOCK COMPANY
                        TL-032021
                        STUFFING 28X40' FCL
                        TO PORT CAT LAI / VIETNAM
                    """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
            ),
            ExportOrder(
                pi=scgp_export_pis[1],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="confirmed",
                payment_term="LC01",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[0],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
                            TOAN LUC PAPER JOINT STOCK COMPANY
                            TL-032021
                            STUFFING 28X40' FCL
                            TO PORT CAT LAI / VIETNAM
                        """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
            ),
            ExportOrder(
                pi=scgp_export_pis[2],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="draft",
                payment_term="LC00",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[2],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
                        TOAN LUC PAPER JOINT STOCK COMPANY
                        TL-032021
                        STUFFING 28X40' FCL
                        TO PORT CAT LAI / VIETNAM
                    """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
            ),
            ExportOrder(
                pi=scgp_export_pis[2],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="Credit/Cash Issue",
                payment_term="LC00",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[0],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
                    TOAN LUC PAPER JOINT STOCK COMPANY
                    TL-032021
                    STUFFING 28X40' FCL
                    TO PORT CAT LAI / VIETNAM
                """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
                eo_no="2841999",
                status_sap="Being Process",
            ),
            ExportOrder(
                pi=scgp_export_pis[2],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="Credit/Cash Issue",
                payment_term="LC00",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[0],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
            TOAN LUC PAPER JOINT STOCK COMPANY
            TL-032021
            STUFFING 28X40' FCL
            TO PORT CAT LAI / VIETNAM
        """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
                eo_no="2841999",
                status_sap="Being Process",
            ),
            ExportOrder(
                pi=scgp_export_pis[2],
                net_price=200,
                tax_amount=14,
                total_price=214,
                doc_currency="USD",
                status="Received Order",
                payment_term="LC00",
                incoterm="CFR",
                shipping_mark="TOAN LUC PAPER JSC UNCOATED - WOODFREE PAPER - MADE IN THAILAND",
                contact_person="131038 Bob B.",
                sales_employee="90010393 Jonh N.",
                author="90010393 Alize A.",
                created_by=customers_for_search[0],
                order_type="ZBV",
                sales_organization=scg_checkout_sales_organization[0],
                distribution_channel=scg_checkout_distribution_channel[0],
                division=scg_checkout_division[0],
                sales_office=scg_checkout_sales_office[0],
                sales_group=scg_checkout_sales_group[0],
                po_date="2022-08-03",
                po_no="TL-032021",
                request_date="2022-08-03",
                ref_pi_no="5100000456",
                usage="HDSD",
                unloading_point="SHANGHAI",
                place_of_delivery="HOCHIMINH CITY",
                port_of_discharge="HOCHIMINH (CAT LAI), VIETNAM",
                port_of_loading="HOCHIMINH (CAT LAI), VIETNAM",
                no_of_containers="0, 14, 0",
                uom="BAGS",
                gw_uom="TON",
                etd="END MARCH",
                eta="EARLY APRIL",
                dlc_expiry_date="2022-08-03",
                dlc_no="0123456789",
                dlc_latest_delivery_date="2022-09-03",
                description="Y",
                payer="1027925",
                end_customer="1027925",
                payment_instruction="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                remark="""
        TOAN LUC PAPER JOINT STOCK COMPANY
        TL-032021
        STUFFING 28X40' FCL
        TO PORT CAT LAI / VIETNAM
    """,
                production_information="LAST L/C RECEIPT DATE FROM THE SPECIFIED ADVISING BANK: FEBRUARY 28, 2021",
                internal_comment_to_warehouse="TOAN LUC PAPER JSC UNCOATED  WOODFREE PAPER MADE IN THAILAND",
                created_at="2022-07-03",
                updated_at="2022-08-03",
                eo_no="2841999",
                status_sap="Complete",
            ),
        ]
    )


@pytest.fixture
def scgp_export_order_lines(
    db, scgp_export_orders, scgp_export_cart_items, scgp_export_pi_products
):
    return ExportOrderLine.objects.bulk_create(
        [
            ExportOrderLine(
                order=scgp_export_orders[0],
                pi_product=scgp_export_pi_products[0],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[0],
                item_no=1,
            ),
            ExportOrderLine(
                order=scgp_export_orders[0],
                pi_product=scgp_export_pi_products[1],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[0],
                item_no=1,
            ),
            ExportOrderLine(
                order=scgp_export_orders[0],
                pi_product=scgp_export_pi_products[2],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[0],
                item_no=1,
            ),
            ExportOrderLine(
                order=scgp_export_orders[1],
                pi_product=scgp_export_pi_products[0],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[0],
                item_no=1,
            ),
            ExportOrderLine(
                order=scgp_export_orders[1],
                pi_product=scgp_export_pi_products[1],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[0],
                item_no=1,
            ),
            ExportOrderLine(
                order=scgp_export_orders[1],
                pi_product=scgp_export_pi_products[2],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[0],
                item_no=1,
            ),
            ExportOrderLine(
                order=scgp_export_orders[2],
                pi_product=scgp_export_pi_products[2],
                quantity=10,
                quantity_unit="TON",
                weight=50,
                weight_unit="ton",
                net_price=1000,
                vat_percent=ScgpExportOrder.TAX.value * 100,
                item_cat_eo="ZMTO",
                reject_reason="NO",
                ref_pi_no="5100000456",
                material_code="Z01OSP07000001308",
                condition_group1="CA- 090D / 36 INCH DIA117N FSC Mix70%",
                material_group2="K01 Kraft roll",
                commission_percent=ScgpExportOrder.COMMISSION.value * 100,
                commission_amount=1000 * ScgpExportOrder.COMMISSION.value,
                commission_unit="USD",
                request_date="2022-08-03",
                plant="7821",
                route="VN0005",
                roll_quantity=10,
                roll_diameter=80,
                roll_core_diameter=40,
                roll_per_pallet=3,
                package_quantity=151,
                pallet_size="NP",
                pallet_no="1-151",
                packing_list="@ 1 ROLL x 151 PACKAGESDIMENSION (WXLXH):40'x40'x34'",
                shipping_point="7505 - shipping point name",
                delivery_tol_under=10,
                delivery_tol_over=10,
                delivery_tol_unlimited=False,
                remark="Remark",
                cart_item=scgp_export_cart_items[8],
                item_no=1,
            ),
        ]
    )


@pytest.fixture
def scg_export_order_sales_organization_by_business_unit(db, business_units_for_search):
    return SalesOrganization.objects.bulk_create(
        [
            SalesOrganization(
                name="sale1", code="code1", business_unit=business_units_for_search[0]
            ),
            SalesOrganization(
                name="sale2", code="code2", business_unit=business_units_for_search[0]
            ),
            SalesOrganization(
                name="sale3", code="code3", business_unit=business_units_for_search[1]
            ),
            SalesOrganization(
                name="sale4", code="code4", business_unit=business_units_for_search[1]
            ),
            SalesOrganization(
                name="sale5", code="code5", business_unit=business_units_for_search[2]
            ),
            SalesOrganization(
                name="sale6", code="code6", business_unit=business_units_for_search[2]
            ),
        ]
    )
