EO_UPLOAD_STATE_RECEIVED_ORDER = "ReceivedOrder"
EO_UPLOAD_STATE_IN_PROGRESS = "InProgress"
EO_UPLOAD_STATE_ERROR = "Error"
EO_UPLOAD_MAP_STATES = {
    "draft": EO_UPLOAD_STATE_IN_PROGRESS,
    "Received Order": EO_UPLOAD_STATE_RECEIVED_ORDER,
}
