# Generated by Django 3.2.12 on 2022-06-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scg_contract", "0002_material_productvariantmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantmaterial",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
