# Generated by Django 3.2.13 on 2022-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_require_attention_items", "0002_requireattention_a"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requireattention",
            name="attention_type",
            field=models.CharField(blank=True, default="R1", max_length=255, null=True),
        ),
    ]
