# Generated by Django 3.2.13 on 2022-09-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_require_attention_items", "0004_auto_20220906_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requireattention",
            name="attention_type",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="requireattention",
            name="item_status",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
