# Generated by Django 3.2.13 on 2023-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_require_attention_items", "0006_remove_requireattention_attention_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requireattention",
            name="inquiry_method_code",
            field=models.CharField(
                blank=True, default="JITCP", max_length=255, null=True
            ),
        ),
    ]
