# Generated by Django 3.2.13 on 2022-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EoUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("message_attributes", models.JSONField()),
                ("message_group_id", models.CharField(max_length=64)),
                ("message_deduplication_id", models.CharField(max_length=64)),
            ],
        ),
    ]
