# Generated by Django 3.2.13 on 2022-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0002_auto_20221102_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="eouploadlog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
