# Generated by Django 3.2.13 on 2022-11-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0003_eouploadlog_error_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eouploadlog",
            old_name="order_id",
            new_name="orderid",
        ),
    ]
