# Generated by Django 3.2.13 on 2022-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0004_rename_order_id_eouploadlog_orderid"),
    ]

    operations = [
        migrations.AddField(
            model_name="eouploadlog",
            name="log_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
