# Generated by Django 3.2.13 on 2022-11-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0005_eouploadlog_log_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eouploadlog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eouploadlog",
            name="message_attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eouploadlog",
            name="message_deduplication_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="eouploadlog",
            name="message_group_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
