# Generated by Django 3.2.13 on 2022-11-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0006_auto_20221102_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="eouploadlog",
            name="eo_no",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
