# Generated by Django 3.2.13 on 2024-01-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_eo_upload", "0007_eouploadlog_eo_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="eouploadlog",
            name="is_summary_email_send",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="eouploadlog",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
