# Generated by Django 3.2.13 on 2023-09-26 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import scgp_user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sap_master_data", "0029_auto_20230623_0642"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailInternalMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bu", models.CharField(max_length=255)),
                ("sale_org", models.CharField(max_length=255)),
                ("team", models.CharField(max_length=255)),
                ("product_group", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="ParentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="parent_groups", to="auth.Group"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ScgpUserLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ScgUserOldPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScgpUserTokenResetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScgpUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_user", models.CharField(blank=True, max_length=50)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
                ("sale_id", models.CharField(blank=True, max_length=10)),
                ("customer_type", models.CharField(blank=True, max_length=256)),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=50, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("password_wrong", models.IntegerField(blank=True, default=0)),
                ("time_lock", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_at_deleted",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "ad_user_at_deleted",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "username_at_deleted",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True, to="scgp_user_management.ScgpUserLanguage"
                    ),
                ),
                (
                    "scgp_bus",
                    models.ManyToManyField(
                        blank=True, to="sap_migration.BusinessUnits"
                    ),
                ),
                (
                    "scgp_distribution_channels",
                    models.ManyToManyField(
                        blank=True, to="sap_master_data.DistributionChannelMaster"
                    ),
                ),
                (
                    "scgp_divisions",
                    models.ManyToManyField(
                        blank=True, to="sap_master_data.DivisionMaster"
                    ),
                ),
                (
                    "scgp_sales_groups",
                    models.ManyToManyField(
                        blank=True, to="sap_migration.SalesGroupMaster"
                    ),
                ),
                (
                    "scgp_sales_offices",
                    models.ManyToManyField(
                        blank=True, to="sap_migration.SalesOfficeMaster"
                    ),
                ),
                (
                    "scgp_sales_organizations",
                    models.ManyToManyField(
                        blank=True, to="sap_master_data.SalesOrganizationMaster"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scgp_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_parent_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scgp_user_management.parentgroup",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("scgp_view_order_customer", "View Order Customer"),
                    ("scgp_create_order_customer", "Create Order Customer"),
                    ("scgp_change_order_customer", "Change Order Customer"),
                    ("scgp_view_order_domestic", "View Order Domestic"),
                    ("scgp_create_order_domestic", "Create Order Domestic"),
                    ("scgp_change_order_domestic", "Change Order Domestic"),
                    ("scgp_view_order_export", "View Order Export"),
                    ("scgp_create_order_export", "Create Order Export"),
                    ("scgp_change_order_export", "Change Order Export"),
                    ("scgp_view_dummy", "View Dummy"),
                    ("scgp_create_dummy", "Create Dummy"),
                    ("scgp_change_dummy", "Change Dummy"),
                    ("scgp_approve_dummy", "Approve Dummy"),
                    ("scgp_maintain_user", "Maintain User"),
                    ("scgp_maintain_user_group", "Maintain User Group"),
                    ("scgp_maintain_role", "Maintain Role"),
                    ("scgp_maintain_role_permission", "Maintain Role Permission"),
                    ("scgp_maintain_organization", "Maintain Organization"),
                    ("scgp_maintain_alt_material", "Maintain Alt Material"),
                    ("scgp_maintain_po_upload", "Maintain Po Upload"),
                    ("scgp_maintain_email", "Maintain Email"),
                    ("scgp_maintain_email_eo_upload", "Maintain Email Eo Upload"),
                    ("scgp_all_upload_po_customer", "All Upload Po Customer"),
                    ("scgp_all_upload_po_admin", "All Upload Po Admin"),
                    ("scgp_all_contract", "All Contract"),
                    ("scgp_all_report_customer", "All Report Customer"),
                    ("scgp_all_report_admin", "All Report Admin"),
                    ("scgp_all_report_domestic", "All Report Domestic"),
                    ("scgp_all_report_export", "All Report Export"),
                    ("scgp_view_stock", "View Stock"),
                    ("scgp_view_draft_order", "View Draft Order"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailConfigurationInternal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bu", models.CharField(max_length=255)),
                ("team", models.CharField(max_length=255)),
                ("create_order", models.BooleanField(default=False)),
                ("po_upload", models.BooleanField(default=False)),
                ("order_confirmation", models.BooleanField(default=False)),
                ("pending_order", models.BooleanField(default=False)),
                ("eo_upload", models.BooleanField(default=False)),
                ("require_attention", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("bu", "team")},
            },
        ),
        migrations.CreateModel(
            name="EmailConfigurationExternal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sold_to_code", models.CharField(max_length=10)),
                ("sold_to_name", models.CharField(blank=True, max_length=100)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            (
                                scgp_user_management.models.EmailConfigurationFeatureChoices[
                                    "CREATE_ORDER"
                                ],
                                "Create Order",
                            ),
                            (
                                scgp_user_management.models.EmailConfigurationFeatureChoices[
                                    "PO_UPLOAD"
                                ],
                                "PO Upload",
                            ),
                            (
                                scgp_user_management.models.EmailConfigurationFeatureChoices[
                                    "PENDING_ORDER"
                                ],
                                "Pending Order",
                            ),
                            (
                                scgp_user_management.models.EmailConfigurationFeatureChoices[
                                    "ORDER_CONFIRMATION"
                                ],
                                "Order Confirmation",
                            ),
                            (
                                scgp_user_management.models.EmailConfigurationFeatureChoices[
                                    "EO_UPLOAD"
                                ],
                                "EO Upload",
                            ),
                            (
                                scgp_user_management.models.EmailConfigurationFeatureChoices[
                                    "REQUIRE_ATTENTION"
                                ],
                                "Require Attention",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("product_group", models.CharField(blank=True, max_length=100)),
                ("mail_to", models.CharField(blank=True, max_length=512)),
                ("cc_to", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "unique_together": {("sold_to_code", "feature", "product_group")},
            },
        ),
    ]
