# Generated by Django 3.2.13 on 2023-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scgpuser",
            name="sap_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
