# Generated by Django 3.2.13 on 2024-01-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_user_management", "0003_emailconfigurationinternal_alternated_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfigurationexternal",
            name="product_group",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="emailinternalmapping",
            name="product_group",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="emailinternalmapping",
            unique_together={("bu", "sale_org", "team", "product_group")},
        ),
    ]
