# Generated by Django 3.2.13 on 2024-01-10 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scgp_user_management", "0004_alter_scgpuser_options"),
        ("scgp_user_management", "0004_auto_20240108_1318"),
    ]

    operations = []
