# Generated by Django 3.2.13 on 2024-03-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_user_management", "0005_alter_scgpuser_options"),
        ("scgp_user_management", "0005_merge_20240110_0438"),
    ]

    operations = []
