# Generated by Django 3.2.13 on 2024-04-23 05:12

from django.db import migrations, models

import scgp_user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_user_management", "0010_alter_scgpuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfigurationinternal",
            name="excel_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailconfigurationexternal",
            name="feature",
            field=models.CharField(
                choices=[
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "CREATE_ORDER"
                        ],
                        "Create Order",
                    ),
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "PO_UPLOAD"
                        ],
                        "PO Upload",
                    ),
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "PENDING_ORDER"
                        ],
                        "Pending Order",
                    ),
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "ORDER_CONFIRMATION"
                        ],
                        "Order Confirmation",
                    ),
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "EO_UPLOAD"
                        ],
                        "EO Upload",
                    ),
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "REQUIRE_ATTENTION"
                        ],
                        "Require Attention",
                    ),
                    (
                        scgp_user_management.models.EmailConfigurationFeatureChoices[
                            "EXCEL_UPLOAD"
                        ],
                        "Excel Upload",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
