# Generated by Django 3.2.13 on 2024-05-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("scgp_user_management", "0011_auto_20240423_0512"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ScgpGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scgp_group",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupMenuFunctions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_code", models.CharField(max_length=255)),
                ("menu_code", models.CharField(max_length=255)),
                ("group_index", models.IntegerField(blank=True, default=0)),
                ("menu_index", models.IntegerField(blank=True, default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_menu",
                        to="auth.group",
                    ),
                ),
                (
                    "menu_function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_menu",
                        to="scgp_user_management.menufunction",
                    ),
                ),
            ],
            options={
                "db_table": "scgp_user_management_groups_menufunction",
                "unique_together": {("group", "menu_function")},
            },
        ),
    ]
