# Generated by Django 3.2.13 on 2022-07-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContractProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_quantity", models.FloatField()),
                ("remaining_quantity", models.FloatField()),
                ("price_per_unit", models.FloatField()),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("weight", models.FloatField()),
                ("weight_unit", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_customer.customercontract",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scgp_customer.customerproduct",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="customercartitem",
            name="contract_variant",
        ),
        migrations.RemoveField(
            model_name="customerorderline",
            name="contract_variant",
        ),
        migrations.AddField(
            model_name="customercartitem",
            name="variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_customer.customerproductvariant",
            ),
        ),
        migrations.AddField(
            model_name="customerorderline",
            name="variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_customer.customerproductvariant",
            ),
        ),
        migrations.DeleteModel(
            name="CustomerContractProductVariant",
        ),
        migrations.AddField(
            model_name="customercartitem",
            name="contract_product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_customer.customercontractproduct",
            ),
        ),
        migrations.AddField(
            model_name="customerorderline",
            name="contract_product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_customer.customercontractproduct",
            ),
        ),
    ]
