# Generated by Django 3.2.13 on 2022-07-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0003_customerorder_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderline",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scgp_customer.customercartitem",
            ),
        ),
    ]
