# Generated by Django 3.2.13 on 2022-08-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0003_customerorder_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerorderline",
            options={"ordering": ("id",)},
        ),
    ]
