# Generated by Django 3.2.13 on 2022-08-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0004_alter_customerorderline_options"),
        ("scgp_customer", "0004_customerorderline_cart_item"),
    ]

    operations = []
