# Generated by Django 3.2.13 on 2022-08-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0005_merge_20220802_0330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorderline",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scgp_customer.customercartitem",
            ),
        ),
    ]
