# Generated by Django 3.2.13 on 2022-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0008_alter_customercartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorder",
            name="remark_for_logistic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
