# Generated by Django 3.2.13 on 2022-12-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scgp_customer", "0009_customerorder_remark_for_logistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorder",
            name="internal_comments_to_warehouse",
            field=models.TextField(blank=True, null=True),
        ),
    ]
