ES_18_API_SUCCESS_RESPONSE = {
    "piMessageId": "XXX",
    "salesdocument": "0037642662",
    "return": [
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "ORDER_HEADER_IN has been processed successfully",
            "messageV1": "VBAKKOM",
            "parameter": "ORDER_HEADER_IN",
            "system": "PEPCLNT900",
        },
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "SCHEDULE_IN has been processed successfully",
            "messageV1": "VBEPKOM",
            "parameter": "ITEM_IN",
            "row": 1,
            "system": "PEPCLNT900",
        },
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "SCHEDULE_IN has been processed successfully",
            "messageV1": "VBEPKOM",
            "parameter": "SCHEDULE_IN",
            "row": 1,
            "system": "PEPCLNT900",
        },
    ],
    "orderItemsOut": [
        {
            "itemNo": "000010",
            "materialNo": "Z034137835",
            "targetQuantity": 200,
            "salesUnit": "PC",
            "plant": "259B",
            "shippingPoint": "2591",
            "route": "200015",
            "custPoNo": "4500050099",
            "itemCategory": "ZPS1",
            "priceGroup2": "TJR",
            "poDate": "26/08/2023",
            "shipToPoItemNo": "C",
            "paymentTerms": "NT30",
            "umvkn": 1000,
            "umvkz": 3114,
            "priceGroup": "01",
            "materialPricingGroup": "01",
            "salesDistrict": "P00008",
            "netWeight": 622.8,
            "grossWeight": 622.8,
            "weightUnit": "KG",
            "productHierarchy": "03JO999999C883",
            "netPricePerUnit": 148,
            "netValue": 29600,
            "currency": "THB",
        },
        {
            "itemNo": "000020",
            "materialNo": "Z034137834",
            "targetQuantity": 100,
            "salesUnit": "PC",
            "plant": "259B",
            "shippingPoint": "2591",
            "route": "200015",
            "custPoNo": "4500050099",
            "itemCategory": "ZPS1",
            "priceGroup2": "TJR",
            "poDate": "26/08/2023",
            "shipToPoItemNo": "C",
            "paymentTerms": "NT30",
            "umvkn": 1000,
            "umvkz": 3048,
            "priceGroup": "01",
            "materialPricingGroup": "01",
            "salesDistrict": "P00008",
            "netWeight": 304.8,
            "grossWeight": 304.8,
            "weightUnit": "KG",
            "productHierarchy": "03JO999999C883",
            "netPricePerUnit": 140,
            "netValue": 14000,
            "currency": "THB",
        },
        {
            "itemNo": "000030",
            "materialNo": "Z034137836",
            "targetQuantity": 200,
            "salesUnit": "PC",
            "plant": "259B",
            "shippingPoint": "2591",
            "route": "200015",
            "custPoNo": "4500050099",
            "itemCategory": "ZPS1",
            "priceGroup2": "TJR",
            "poDate": "26/08/2023",
            "shipToPoItemNo": "C",
            "paymentTerms": "NT30",
            "umvkn": 1000,
            "umvkz": 3072,
            "priceGroup": "01",
            "materialPricingGroup": "01",
            "salesDistrict": "P00008",
            "netWeight": 614.4,
            "grossWeight": 614.4,
            "weightUnit": "KG",
            "productHierarchy": "03JO999999C883",
            "netPricePerUnit": 142,
            "netValue": 28400,
            "currency": "THB",
        },
        {
            "itemNo": "000040",
            "materialNo": "Z034137837",
            "targetQuantity": 197,
            "salesUnit": "PC",
            "plant": "259B",
            "shippingPoint": "2591",
            "route": "200015",
            "custPoNo": "4500050099",
            "itemCategory": "ZPS1",
            "priceGroup2": "TJR",
            "poDate": "26/08/2023",
            "shipToPoItemNo": "C",
            "paymentTerms": "NT30",
            "umvkn": 1000,
            "umvkz": 2800,
            "priceGroup": "01",
            "materialPricingGroup": "01",
            "salesDistrict": "P00008",
            "netWeight": 551.6,
            "grossWeight": 551.6,
            "weightUnit": "KG",
            "productHierarchy": "03JO999999C883",
            "netPricePerUnit": 126,
            "netValue": 24822,
            "currency": "THB",
        },
    ],
    "orderSchedulesOut": [
        {
            "itemNo": "000010",
            "scheduleLine": "0001",
            "scheduleLinecate": "CN",
            "requestDate": "28/08/2023",
            "requestQuantity": 200,
            "confirmQuantity": 200,
        },
        {
            "itemNo": "000020",
            "scheduleLine": "0001",
            "scheduleLinecate": "CN",
            "requestDate": "28/08/2023",
            "requestQuantity": 100,
            "confirmQuantity": 100,
        },
        {
            "itemNo": "000030",
            "scheduleLine": "0001",
            "scheduleLinecate": "CN",
            "requestDate": "28/08/2023",
            "requestQuantity": 200,
            "confirmQuantity": 200,
        },
        {
            "itemNo": "000040",
            "scheduleLine": "0001",
            "scheduleLinecate": "CN",
            "requestDate": "28/08/2023",
            "requestQuantity": 197,
            "confirmQuantity": 197,
        },
    ],
    "businessOut": [
        {
            "sdDoc": "0037642662",
            "priceGroup": "01",
            "customerGroup": "09",
            "salesDistrict": "P00008",
            "incoterms1": "CFR",
            "incoterms2": "ชลบุรี",
            "ordcombind": "X",
            "accountAssignment": "01",
            "exchgRate": "1.0",
            "priceDate": "26/08/2023",
            "billDate": "26/08/2023",
        },
        {
            "sdDoc": "0037642662",
            "itemNo": "000010",
            "priceGroup": "01",
            "customerGroup": "09",
            "salesDistrict": "P00008",
            "incoterms1": "CFR",
            "incoterms2": "ชลบุรี",
            "ordcombind": "X",
            "accountAssignment": "01",
            "exchgRate": "1.0",
            "priceDate": "26/08/2023",
            "billDate": "26/08/2023",
        },
        {
            "sdDoc": "0037642662",
            "itemNo": "000020",
            "priceGroup": "01",
            "customerGroup": "09",
            "salesDistrict": "P00008",
            "incoterms1": "CFR",
            "incoterms2": "ชลบุรี",
            "ordcombind": "X",
            "accountAssignment": "01",
            "exchgRate": "1.0",
            "priceDate": "26/08/2023",
            "billDate": "26/08/2023",
        },
        {
            "sdDoc": "0037642662",
            "itemNo": "000030",
            "priceGroup": "01",
            "customerGroup": "09",
            "salesDistrict": "P00008",
            "incoterms1": "CFR",
            "incoterms2": "ชลบุรี",
            "ordcombind": "X",
            "accountAssignment": "01",
            "exchgRate": "1.0",
            "priceDate": "26/08/2023",
            "billDate": "26/08/2023",
        },
        {
            "sdDoc": "0037642662",
            "itemNo": "000040",
            "priceGroup": "01",
            "customerGroup": "09",
            "salesDistrict": "P00008",
            "incoterms1": "CFR",
            "incoterms2": "ชลบุรี",
            "ordcombind": "X",
            "accountAssignment": "01",
            "exchgRate": "1.0",
            "priceDate": "26/08/2023",
            "billDate": "26/08/2023",
        },
    ],
    "conditionsOut": [
        {
            "itemNo": "000010",
            "conditionStNo": "010",
            "conditionCount": "01",
            "conditionType": "ZPP1",
            "conditionRate": 148,
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPUnt": 1,
            "conpricdat": "26/08/2023",
            "conbaseval": 200,
            "conexchrat": 1,
            "numberConvertor": 3114,
            "denominator": 1000,
            "conditionValue": 29600,
        },
        {
            "itemNo": "000010",
            "conditionStNo": 745,
            "conditionCount": "01",
            "conditionType": "MWST",
            "conpricdat": "26/08/2023",
            "conbaseval": 29600,
        },
        {
            "itemNo": "000010",
            "conditionStNo": 960,
            "conditionCount": "01",
            "conditionType": "VPRS",
            "conditionRate": 32989.71,
            "currency": "THB",
            "conditionUnit": "KG",
            "conditionPUnt": 1000,
            "conpricdat": "26/08/2023",
            "conbaseval": 622.8,
            "conexchrat": 1,
            "numberConvertor": 1,
            "denominator": 1,
            "conditionValue": 20545.99,
        },
        {
            "itemNo": "000020",
            "conditionStNo": "010",
            "conditionCount": "01",
            "conditionType": "ZPP1",
            "conditionRate": 140,
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPUnt": 1,
            "conpricdat": "26/08/2023",
            "conbaseval": 100,
            "conexchrat": 1,
            "numberConvertor": 3048,
            "denominator": 1000,
            "conditionValue": 14000,
        },
        {
            "itemNo": "000020",
            "conditionStNo": 745,
            "conditionCount": "01",
            "conditionType": "MWST",
            "conpricdat": "26/08/2023",
            "conbaseval": 14000,
        },
        {
            "itemNo": "000020",
            "conditionStNo": 960,
            "conditionCount": "01",
            "conditionType": "VPRS",
            "conditionRate": 32989.71,
            "currency": "THB",
            "conditionUnit": "KG",
            "conditionPUnt": 1000,
            "conpricdat": "26/08/2023",
            "conbaseval": 304.8,
            "conexchrat": 1,
            "numberConvertor": 1,
            "denominator": 1,
            "conditionValue": 10055.26,
        },
        {
            "itemNo": "000030",
            "conditionStNo": "010",
            "conditionCount": "01",
            "conditionType": "ZPP1",
            "conditionRate": 142,
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPUnt": 1,
            "conpricdat": "26/08/2023",
            "conbaseval": 200,
            "conexchrat": 1,
            "numberConvertor": 3072,
            "denominator": 1000,
            "conditionValue": 28400,
        },
        {
            "itemNo": "000030",
            "conditionStNo": 745,
            "conditionCount": "01",
            "conditionType": "MWST",
            "conpricdat": "26/08/2023",
            "conbaseval": 28400,
        },
        {
            "itemNo": "000030",
            "conditionStNo": 960,
            "conditionCount": "01",
            "conditionType": "VPRS",
            "conditionRate": 32989.71,
            "currency": "THB",
            "conditionUnit": "KG",
            "conditionPUnt": 1000,
            "conpricdat": "26/08/2023",
            "conbaseval": 614.4,
            "conexchrat": 1,
            "numberConvertor": 1,
            "denominator": 1,
            "conditionValue": 20268.88,
        },
        {
            "itemNo": "000040",
            "conditionStNo": "010",
            "conditionCount": "01",
            "conditionType": "ZPP1",
            "conditionRate": 126,
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPUnt": 1,
            "conpricdat": "26/08/2023",
            "conbaseval": 197,
            "conexchrat": 1,
            "numberConvertor": 2800,
            "denominator": 1000,
            "conditionValue": 24822,
        },
        {
            "itemNo": "000040",
            "conditionStNo": 745,
            "conditionCount": "01",
            "conditionType": "MWST",
            "conpricdat": "26/08/2023",
            "conbaseval": 24822,
        },
        {
            "itemNo": "000040",
            "conditionStNo": 960,
            "conditionCount": "01",
            "conditionType": "VPRS",
            "conditionRate": 32989.71,
            "currency": "THB",
            "conditionUnit": "KG",
            "conditionPUnt": 1000,
            "conpricdat": "26/08/2023",
            "conbaseval": 551.6,
            "conexchrat": 1,
            "numberConvertor": 1,
            "denominator": 1,
            "conditionValue": 18197.13,
        },
    ],
    "creditStatus": "D",
    "creditStatustext": "Document released by credit representative",
    "orderHeaderOut": {
        "orderAmtBeforeVat": 96822,
        "orderAmtAfterVat": 96822,
        "currency": "THB",
    },
    "orderPartners": [
        {"partnerRole": "AG", "partnerNo": "0001034763"},
        {"partnerRole": "AP", "partnerNo": "0000161801"},
        {"partnerRole": "AU", "partnerNo": 10069677},
        {"partnerRole": "RE", "partnerNo": "0001034763"},
        {"partnerRole": "RG", "partnerNo": "0001034763"},
        {"partnerRole": "VE", "partnerNo": 10017253},
        {"partnerRole": "WE", "partnerNo": "0001034763"},
    ],
}
ES_18_API_ERROR_RESPONSE = {
    "piMessageId": "66960507615905117721371250114963614722",
    "salesdocument": "0411100449",
    "return": [
        {
            "type": "fail",
            "id": "V1",
            "number": "391",
            "message": "Material Z02CAF115D0900117N does not exist in plant 7521  country TH",
            "messageV1": "Z02CAF115D0900117N",
            "messageV2": "7521",
            "messageV3": "TH",
            "parameter": "ITEM_IN",
            "row": 1,
            "system": "PEPCLNT900",
            "itemNo": "000010",
        }
    ],
}
