ES_16_API_SUCCESS_RESPONSE = {
    "piMessageId": "XXXXX",
    "salesdocument": "0038273452",
    "creditStatus": "A",
    "creditStatusText": "Credit check was executed, document OK",
    "data": [
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "SALES_HEADER_IN has been processed successfully",
            "messageV1": "VBAKKOM",
            "parameter": "SALES_HEADER_IN",
            "system": "PEDCLNT039",
        },
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "SALES_ITEM_IN has been processed successfully",
            "messageV1": "VBAPKOM",
            "messageV2": "000010",
            "parameter": "SALES_ITEM_IN",
            "row": 1,
            "system": "PEDCLNT039",
        },
        {
            "type": "success",
            "id": "V1",
            "number": "311",
            "message": "Standard Order 660270866 has been saved",
            "messageV1": "Standard Order",
            "messageV2": "660270866",
            "parameter": "SALES_HEADER_IN",
            "system": "PEDCLNT039",
        },
    ],
    "orderItemsOut": [
        {
            "itemNo": "000010",
            "material": "Z03SOLUTION 000003",
            "targetQuantity": 1,
            "salesUnit": "PC",
            "plant": "253B",
            "shippingPoint": "2531",
            "route": "1A0219",
            "custPoNo": "PO6506004",
            "itemCategory": "ZPS3",
            "prcGroup1": "A03",
            "poDate": "13/06/2022",
            "paymentTerm": "NT60",
            "netValue": 2300,
            "currency": "THB",
            "netWeight": 1,
            "grossWeight": 1,
            "productHierarchy": "03X3999999",
            "materialPricingGroup": "02",
            "salesDistrict": "P00057",
            "weightUnit": "KG",
            "priceDate": "13/06/2022",
            "netPricePerUnit": 2300,
        }
    ],
    "conditionsOut": [
        {
            "itemNo": "000010",
            "conditionStepNo": "015",
            "conditionCount": "01",
            "conditionType": "ZPS2",
            "conditionRate": 2300,
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPerUnit": 1,
            "conditionPriceDate": "13/06/2023",
            "conditionBaseBalue": 1,
            "conditionExchgRate": 1,
            "numconvert": 100,
            "denominato": 100,
            "conditionValue": 2300,
        },
        {
            "itemNo": "000010",
            "conditionStepNo": 745,
            "conditionCount": "01",
            "conditionType": "MWST",
            "conditionRate": 7,
            "conditionPriceDate": "13/06/2023",
            "conditionBaseBalue": 2300,
            "conditionValue": 161,
        },
        {
            "itemNo": "000010",
            "conditionStepNo": 960,
            "conditionCount": "01",
            "conditionType": "VPRS",
            "currency": "THB",
            "conditionUnit": "KG",
            "conditionPerUnit": 1,
            "conditionPriceDate": "13/06/2023",
            "conditionBaseBalue": 1,
            "conditionExchgRate": 1,
            "numconvert": 1,
            "denominato": 1,
        },
    ],
    "orderSchedulesOut": [
        {
            "itemNo": "000010",
            "scheduleLine": "0001",
            "scheduleLinecate": "CX",
            "requestDate": "13/06/2021",
            "requestQuantity": 1,
            "comfirmQuantity": 1,
        }
    ],
    "orderHeaderOut": {
        "orderAmtBeforeVat": 2300,
        "orderAmtVat": 161,
        "orderAmtAfterVat": 2461,
        "currency": "THB",
    },
    "orderPartners": [
        {"partnerRole": "AG", "partnerNo": "0001014245"},
        {"partnerRole": "AU", "partnerNo": 90025770},
        {"partnerRole": "RE", "partnerNo": "0001014245"},
        {"partnerRole": "RG", "partnerNo": "0001014245"},
        {"partnerRole": "VE", "partnerNo": "0000179592"},
        {"partnerRole": "WE", "partnerNo": "0001014245"},
    ],
}
ES_16_API_SUCCESS_RESPONSE_BOM = {
    "piMessageId": "XXXXX",
    "salesdocument": "0038273452",
    "creditStatus": "A",
    "creditStatusText": "Credit check was executed, document OK",
    "data": [
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "SALES_HEADER_IN has been processed successfully",
            "messageV1": "VBAKKOM",
            "parameter": "SALES_HEADER_IN",
            "system": "PEDCLNT039",
        },
        {
            "type": "success",
            "id": "V4",
            "number": "233",
            "message": "SALES_ITEM_IN has been processed successfully",
            "messageV1": "VBAPKOM",
            "messageV2": "000010",
            "parameter": "SALES_ITEM_IN",
            "row": 1,
            "system": "PEDCLNT039",
        },
        {
            "type": "success",
            "id": "V1",
            "number": "311",
            "message": "Standard Order 660270866 has been saved",
            "messageV1": "Standard Order",
            "messageV2": "660270866",
            "parameter": "SALES_HEADER_IN",
            "system": "PEDCLNT039",
        },
    ],
    "orderItemsOut": [
        {
            "itemNo": "000010",
            "material": "Z03SOLUTION 000003",
            "targetQuantity": 1,
            "salesUnit": "PC",
            "plant": "253B",
            "shippingPoint": "2531",
            "route": "1A0219",
            "custPoNo": "PO6506004",
            "itemCategory": "ZPS3",
            "prcGroup1": "A03",
            "poDate": "13/06/2022",
            "paymentTerm": "NT60",
            "netValue": 2300,
            "currency": "THB",
            "netWeight": 1,
            "grossWeight": 1,
            "productHierarchy": "03X3999999",
            "materialPricingGroup": "02",
            "salesDistrict": "P00057",
            "weightUnit": "KG",
            "priceDate": "13/06/2022",
            "netPricePerUnit": 2300,
        },
        {
            "itemNo": "000020",
            "material": "Z03SOLUTION 000003",
            "targetQuantity": 1,
            "salesUnit": "PC",
            "plant": "253B",
            "shippingPoint": "2531",
            "route": "1A0219",
            "custPoNo": "PO6506004",
            "itemCategory": "ZPS3",
            "prcGroup1": "A03",
            "poDate": "13/06/2022",
            "paymentTerm": "NT60",
            "netValue": 2300,
            "currency": "THB",
            "netWeight": 1,
            "grossWeight": 1,
            "productHierarchy": "03X3999999",
            "materialPricingGroup": "02",
            "salesDistrict": "P00057",
            "weightUnit": "KG",
            "priceDate": "13/06/2022",
            "netPricePerUnit": 2300,
            "parentItemNo": "000010",
            "bomFlag": True,
        },
    ],
    "conditionsOut": [
        {
            "itemNo": "000010",
            "conditionStepNo": "015",
            "conditionCount": "01",
            "conditionType": "ZPS2",
            "conditionRate": 2300,
            "currency": "THB",
            "conditionUnit": "PC",
            "conditionPerUnit": 1,
            "conditionPriceDate": "13/06/2023",
            "conditionBaseBalue": 1,
            "conditionExchgRate": 1,
            "numconvert": 100,
            "denominato": 100,
            "conditionValue": 2300,
        },
        {
            "itemNo": "000010",
            "conditionStepNo": 745,
            "conditionCount": "01",
            "conditionType": "MWST",
            "conditionRate": 7,
            "conditionPriceDate": "13/06/2023",
            "conditionBaseBalue": 2300,
            "conditionValue": 161,
        },
        {
            "itemNo": "000010",
            "conditionStepNo": 960,
            "conditionCount": "01",
            "conditionType": "VPRS",
            "currency": "THB",
            "conditionUnit": "KG",
            "conditionPerUnit": 1,
            "conditionPriceDate": "13/06/2023",
            "conditionBaseBalue": 1,
            "conditionExchgRate": 1,
            "numconvert": 1,
            "denominato": 1,
        },
    ],
    "orderSchedulesOut": [
        {
            "itemNo": "000010",
            "scheduleLine": "0001",
            "scheduleLinecate": "CX",
            "requestDate": "13/06/2021",
            "requestQuantity": 1,
            "comfirmQuantity": 1,
        }
    ],
    "orderHeaderOut": {
        "orderAmtBeforeVat": 2300,
        "orderAmtVat": 161,
        "orderAmtAfterVat": 2461,
        "currency": "THB",
    },
    "orderPartners": [
        {"partnerRole": "AG", "partnerNo": "0001014245"},
        {"partnerRole": "AU", "partnerNo": 90025770},
        {"partnerRole": "RE", "partnerNo": "0001014245"},
        {"partnerRole": "RG", "partnerNo": "0001014245"},
        {"partnerRole": "VE", "partnerNo": "0000179592"},
        {"partnerRole": "WE", "partnerNo": "0001014245"},
    ],
}
ES_16_API_ERROR_RESPONSE = {
    "piMessageId": "XXXXX",
    "data": [
        {
            "type": "fail",
            "id": "Z_EOR_ERR_ITM",
            "number": "010",
            "message": "Z01 :รหัสสินค้าดังกล่าวไม่มีข้อมูลราคาในระบบ",
            "messageV1": "000010",
            "messageV2": "Z01",
            "itemNo": "000010",
        }
    ],
    "orderItemsOut": [
        {
            "itemNo": "000010",
            "materialNo": "Z03SOLUTION 000003",
            "targetQuantity": 19000,
            "salesUnit": "PC",
            "plant": "253B",
            "poDateS": "13/06/2023",
            "itemStatus": "Z01",
        }
    ],
}
