ES25_SAMPLE_RESPONSE1 = {
    "piMessageId": "259839843847201347806539681694117189850",
    "status": "success",
    "reason": "",
    "data": [
        {
            "sdDoc": "0410289750",
            "status": "B",
            "createDate": "12/03/2024",
            "createTime": "15:33:02",
            "poNo": "TEst",
            "salesOrg": "0750",
            "descriptionInContract": "E2E  for dev.",
            "creditStatus": "A",
            "deliveryStatus": "A",
            "soldTo": "0001003199",
            "soldToName1": "บจก. รวมไทยบรรจุภัณฑ์",
            "shipTo": "0001012421",
            "shipToName1": "บจก. รวมไทยบรรจุภัณฑ์ (สมุทรปราการ)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "เขตภาษีเจริญ จ.กรุงเทพฯ",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days",
            "contractNo": "0410001425",
            "webUserId": "csadmin 01",
            "salesGroup": "752",
        },
    ],
    "dataItem": [
        {
            "sdDoc": "0410289750",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "LUMF",
            "status": "A",
            "matNo": "Z02CA-125D0930117N",
            "matDesc": "CA- 125D-93 DIA117 N",
            "plant": "7551",
            "saleUnit": "ROL",
            "netWeight": 0.695,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 15081.5,
            "firstDeliveryDT": "12/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 695,
            "confirmQty": 1,
            "confirmQtyBase": 695,
            "pendingQty": 1,
            "pendingQtyBase": 695,
            "contractPI": "0410001433",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "12/04/2024",
            "orderQtyWeight": 0.695,
            "pendingQtyWeight": 0.695,
            "materialGroup1": "",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 695,
            "pendingGiQtyTon": 0.695,
            "weightUnit": "TON",
            "grossWeightTon": 0.695,
            "netWeightTon": 0.695,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
            "bomFlag": True,
        },
        {
            "sdDoc": "0410289750",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "CHILD-125D0930117N",
            "matDesc": "CH- 125D-93 DIA117 N",
            "plant": "7551",
            "saleUnit": "ROL",
            "netWeight": 0.695,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 15081.5,
            "firstDeliveryDT": "12/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 695,
            "confirmQty": 1,
            "confirmQtyBase": 695,
            "pendingQty": 1,
            "pendingQtyBase": 695,
            "contractPI": "0410001433",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "12/04/2024",
            "orderQtyWeight": 0.695,
            "pendingQtyWeight": 0.695,
            "materialGroup1": "",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 695,
            "pendingGiQtyTon": 0.695,
            "weightUnit": "TON",
            "grossWeightTon": 0.695,
            "netWeightTon": 0.695,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
            "bomFlag": True,
            "parentItemNo": "000010",
        },
    ],
}

ES25_SAMPLE_RESPONSE2 = {
    "piMessageId": "268075222014092677168840775651018614068",
    "status": "success",
    "reason": "",
    "data": [
        {
            "sdDoc": "0410289750",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "09:26:22",
            "poNo": "14032024NqWVsL1J",
            "salesOrg": "0750",
            "descriptionInContract": "For Automate",
            "creditStatus": "B",
            "deliveryStatus": "A",
            "soldTo": "0001011222",
            "soldToName1": "บจก. กลุ่มสยามบรรจุภัณฑ์-TCCB",
            "shipTo": "0001011223",
            "shipToName1": "โรงงานชลบุรี (TCCB)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.ศรีราชา จ.ชลบุรี",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days",
            "contractNo": "0410001356",
            "webUserId": "Automate Test03",
            "salesGroup": "75C",
        },
        {
            "sdDoc": "0410289751",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "09:26:42",
            "poNo": "14032024JGFikZUb",
            "salesOrg": "0750",
            "descriptionInContract": "For Automate",
            "creditStatus": "B",
            "deliveryStatus": "A",
            "soldTo": "0001011222",
            "soldToName1": "บจก. กลุ่มสยามบรรจุภัณฑ์-TCCB",
            "shipTo": "0001011223",
            "shipToName1": "โรงงานชลบุรี (TCCB)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.ศรีราชา จ.ชลบุรี",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days",
            "contractNo": "0410001356",
            "webUserId": "Automate Test03",
            "salesGroup": "75C",
        },
        {
            "sdDoc": "0410289752",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "09:31:44",
            "poNo": 1,
            "salesOrg": "0750",
            "descriptionInContract": "For Automate",
            "creditStatus": "B",
            "deliveryStatus": "A",
            "soldTo": "0001011222",
            "soldToName1": "บจก. กลุ่มสยามบรรจุภัณฑ์-TCCB",
            "shipTo": "0001011223",
            "shipToName1": "โรงงานชลบุรี (TCCB)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.ศรีราชา จ.ชลบุรี",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days",
            "lastChangeDate": "14/03/2024",
            "lastChangeTime": "09:34:13",
            "contractNo": "0410001356",
            "webUserId": "csadmin 01",
            "salesGroup": "75C",
        },
        {
            "sdDoc": "0410289753",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "12:33:41",
            "poNo": "SIT_7300_PO_srDB_02",
            "salesOrg": "0750",
            "descriptionInContract": "testmixproduct-dom 1",
            "creditStatus": "A",
            "deliveryStatus": "A",
            "soldTo": "0001023135",
            "soldToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "shipTo": "0001023135",
            "shipToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.สามพราน จ.นครปฐม",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days",
            "contractNo": "0410001434",
            "webUserId": "csadmin 01",
            "salesGroup": "755",
        },
        {
            "sdDoc": "0410289754",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "13:07:14",
            "poNo": 123,
            "salesOrg": "0750",
            "descriptionInContract": "E2E  for dev.",
            "creditStatus": "A",
            "deliveryStatus": "A",
            "soldTo": "0001003199",
            "soldToName1": "บจก. รวมไทยบรรจุภัณฑ์",
            "shipTo": "0001012421",
            "shipToName1": "บจก. รวมไทยบรรจุภัณฑ์ (สมุทรปราการ)",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "เขตภาษีเจริญ จ.กรุงเทพฯ",
            "paymentTerm": "NT60",
            "paymentTermDesc": "Credit 60 days",
            "contractNo": "0410001303",
            "webUserId": "csadmin 01",
            "salesGroup": "752",
        },
        {
            "sdDoc": "0410289756",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "16:20:21",
            "poNo": "SIT_7300_PO_srDB_02",
            "salesOrg": "0750",
            "descriptionInContract": "testmixproduct-dom 1",
            "creditStatus": "A",
            "deliveryStatus": "A",
            "soldTo": "0001023135",
            "soldToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "shipTo": "0001023135",
            "shipToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.สามพราน จ.นครปฐม",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days",
            "contractNo": "0410001434",
            "webUserId": "csadmin 01",
            "salesGroup": "755",
        },
        {
            "sdDoc": "0410289757",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "16:25:28",
            "poNo": "SIT_7300_PO_srDB_02",
            "salesOrg": "0750",
            "descriptionInContract": "testmixproduct-dom 1",
            "creditStatus": "A",
            "deliveryStatus": "A",
            "soldTo": "0001023135",
            "soldToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "shipTo": "0001023135",
            "shipToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.สามพราน จ.นครปฐม",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days",
            "contractNo": "0410001434",
            "webUserId": "csadmin 01",
            "salesGroup": "755",
        },
        {
            "sdDoc": "0410289758",
            "status": "B",
            "createDate": "14/03/2024",
            "createTime": "16:28:41",
            "poNo": "SIT_7300_PO_srDB_02",
            "salesOrg": "0750",
            "descriptionInContract": "testmixproduct-dom 1",
            "creditStatus": "A",
            "deliveryStatus": "A",
            "soldTo": "0001023135",
            "soldToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "shipTo": "0001023135",
            "shipToName1": "บริษัท รอแยล พริ้นท์เฮ้าส์  จำกัด",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "อ.สามพราน จ.นครปฐม",
            "paymentTerm": "NT30",
            "paymentTermDesc": "Credit 30 days",
            "contractNo": "0410001434",
            "webUserId": "csadmin 01",
            "salesGroup": "755",
        },
        {
            "sdDoc": "0412121984",
            "status": "A",
            "createDate": "14/03/2024",
            "createTime": "20:00:26",
            "poNo": "ONETIME1122",
            "salesOrg": "0750",
            "deliveryStatus": "A",
            "deliveryblockHStatus": "P1",
            "soldTo": "0009999001",
            "soldToName1": "น.ส. ทดสอบ นามสมมติ",
            "shipTo": "0009999001",
            "shipToName1": "น.ส. ทดสอบ นามสมมติ",
            "countrySh": "TH",
            "countryName": "Thailand",
            "incoterms1": "CFR",
            "incoterms2": "กรุงเทพ ฯ",
            "paymentTerm": "NT00",
            "paymentTermDesc": "Cash",
            "contractNo": "0410001240",
            "salesGroup": "75B",
        },
    ],
    "dataItem": [
        {
            "sdDoc": "0410289750",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.814,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17501,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 814,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 814,
            "pendingQty": 1,
            "pendingQtyBase": 814,
            "contractPI": "0410001356",
            "contractPIItemNo": "000010",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.814,
            "pendingQtyWeight": 0.814,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 814,
            "pendingGiQtyTon": 0.814,
            "weightUnit": "TON",
            "grossWeightTon": 0.814,
            "netWeightTon": 0.814,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
            "bomFlag": "X",
            "parentItemNo": "",
        },
        {
            "sdDoc": "0410289750",
            "itemNo": "000020",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-105M0930110N",
            "matDesc": "CA- 105M-93 DIA110N",
            "plant": "7531",
            "saleUnit": "ROL",
            "netWeight": 0.576,
            "netWeightUnit": "TON",
            "netPrice": 17500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 10080,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 576,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 576,
            "pendingQty": 1,
            "pendingQtyBase": 576,
            "contractPI": "0410001356",
            "contractPIItemNo": "000050",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.576,
            "pendingQtyWeight": 0.576,
            "materialGroup1": "K01",
            "netPriceConditionRate": 17500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 576,
            "pendingGiQtyTon": 0.576,
            "weightUnit": "TON",
            "grossWeightTon": 0.576,
            "netWeightTon": 0.576,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
            "bomFlag": "X",
            "parentItemNo": "000010",
        },
        {
            "sdDoc": "0410289750",
            "itemNo": "000030",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-105M0930110N",
            "matDesc": "CA- 105M-93 DIA110N",
            "plant": "7531",
            "saleUnit": "ROL",
            "netWeight": 0.576,
            "netWeightUnit": "TON",
            "netPrice": 17500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 10080,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 576,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 576,
            "pendingQty": 1,
            "pendingQtyBase": 576,
            "contractPI": "0410001356",
            "contractPIItemNo": "000050",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.576,
            "pendingQtyWeight": 0.576,
            "materialGroup1": "K01",
            "netPriceConditionRate": 17500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 576,
            "pendingGiQtyTon": 0.576,
            "weightUnit": "TON",
            "grossWeightTon": 0.576,
            "netWeightTon": 0.576,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
            "bomFlag": "X",
            "parentItemNo": "000010",
        },
        {
            "sdDoc": "0410289750",
            "itemNo": "000040",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.814,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17501,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 814,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 814,
            "pendingQty": 1,
            "pendingQtyBase": 814,
            "contractPI": "0410001356",
            "contractPIItemNo": "000010",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.814,
            "pendingQtyWeight": 0.814,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 814,
            "pendingGiQtyTon": 0.814,
            "weightUnit": "TON",
            "grossWeightTon": 0.814,
            "netWeightTon": 0.814,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289751",
            "itemNo": "000020",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-105M0930110N",
            "matDesc": "CA- 105M-93 DIA110N",
            "plant": "7531",
            "saleUnit": "ROL",
            "netWeight": 0.576,
            "netWeightUnit": "TON",
            "netPrice": 17500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 10080,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 576,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 576,
            "pendingQty": 1,
            "pendingQtyBase": 576,
            "contractPI": "0410001356",
            "contractPIItemNo": "000050",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.576,
            "pendingQtyWeight": 0.576,
            "materialGroup1": "K01",
            "netPriceConditionRate": 17500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 576,
            "pendingGiQtyTon": 0.576,
            "weightUnit": "TON",
            "grossWeightTon": 0.576,
            "netWeightTon": 0.576,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289751",
            "itemNo": "000030",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-105M0930110N",
            "matDesc": "CA- 105M-93 DIA110N",
            "plant": "7531",
            "saleUnit": "ROL",
            "netWeight": 0.576,
            "netWeightUnit": "TON",
            "netPrice": 17500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 10080,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 576,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 576,
            "pendingQty": 1,
            "pendingQtyBase": 576,
            "contractPI": "0410001356",
            "contractPIItemNo": "000050",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.576,
            "pendingQtyWeight": 0.576,
            "materialGroup1": "K01",
            "netPriceConditionRate": 17500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 576,
            "pendingGiQtyTon": 0.576,
            "weightUnit": "TON",
            "grossWeightTon": 0.576,
            "netWeightTon": 0.576,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1080117N",
            "matDesc": "CA- 125D-108 DIA117N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.814,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17501,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 814,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 814,
            "pendingQty": 1,
            "pendingQtyBase": 814,
            "contractPI": "0410001356",
            "contractPIItemNo": "000010",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.814,
            "pendingQtyWeight": 0.814,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 814,
            "pendingGiQtyTon": 0.814,
            "weightUnit": "TON",
            "grossWeightTon": 0.814,
            "netWeightTon": 0.814,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000020",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-090D1300117N",
            "matDesc": "CA-90D-130 DIA117N FSC Mix70%",
            "plant": "7550",
            "saleUnit": "ROL",
            "netWeight": 0.958,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": "750A",
            "netValue": 21500,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 1000,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 1000,
            "pendingQty": 1,
            "pendingQtyBase": 1000,
            "contractPI": "0410001356",
            "contractPIItemNo": "000040",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.958,
            "pendingQtyWeight": 1,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 1000,
            "pendingGiQtyTon": 0.958,
            "weightUnit": "TON",
            "grossWeightTon": 0.958,
            "netWeightTon": 0.958,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000030",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-105M0930110N",
            "matDesc": "CA- 105M-93 DIA110N",
            "plant": "7531",
            "saleUnit": "ROL",
            "netWeight": 0.576,
            "netWeightUnit": "TON",
            "netPrice": 17500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 10080,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 576,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 576,
            "pendingQty": 1,
            "pendingQtyBase": 576,
            "contractPI": "0410001356",
            "contractPIItemNo": "000050",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.576,
            "pendingQtyWeight": 0.576,
            "materialGroup1": "K01",
            "netPriceConditionRate": 17500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 576,
            "pendingGiQtyTon": 0.576,
            "weightUnit": "TON",
            "grossWeightTon": 0.576,
            "netWeightTon": 0.576,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000040",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D0930117N",
            "matDesc": "CA- 125D-93 DIA117 N",
            "plant": "7551",
            "saleUnit": "ROL",
            "netWeight": 0.695,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 14942.5,
            "firstDeliveryDT": "14/03/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 695,
            "confirmQty": 1,
            "confirmQtyBase": 695,
            "pendingQty": 1,
            "pendingQtyBase": 695,
            "contractPI": "0410001356",
            "contractPIItemNo": "000010",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.695,
            "pendingQtyWeight": 0.695,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 695,
            "pendingGiQtyTon": 0.695,
            "weightUnit": "TON",
            "grossWeightTon": 0.695,
            "netWeightTon": 0.695,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000050",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D0980117N",
            "matDesc": "CA- 125D-98 DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.802,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17243,
            "firstDeliveryDT": "14/03/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 802,
            "confirmQty": 1,
            "confirmQtyBase": 802,
            "pendingQty": 1,
            "pendingQtyBase": 802,
            "contractPI": "0410001356",
            "contractPIItemNo": "000010",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.802,
            "pendingQtyWeight": 0.802,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 802,
            "pendingGiQtyTon": 0.802,
            "weightUnit": "TON",
            "grossWeightTon": 0.802,
            "netWeightTon": 0.802,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000060",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1030117N",
            "matDesc": "CA- 125D-103 DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.823,
            "netWeightUnit": "TON",
            "netPrice": 21500,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17694.5,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 823,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 823,
            "pendingQty": 1,
            "pendingQtyBase": 823,
            "contractPI": "0410001356",
            "contractPIItemNo": "000010",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.823,
            "pendingQtyWeight": 0.823,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 823,
            "pendingGiQtyTon": 0.823,
            "weightUnit": "TON",
            "grossWeightTon": 0.823,
            "netWeightTon": 0.823,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000070",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CAA090M0980125N",
            "matDesc": "CAA 90M-98 DIA125N",
            "plant": "7531",
            "saleUnit": "ROL",
            "netWeight": 0.845,
            "netWeightUnit": "TON",
            "netPrice": 23500,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 23500,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 1000,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 1000,
            "pendingQty": 1,
            "pendingQtyBase": 1000,
            "contractPI": "0410001356",
            "contractPIItemNo": "000030",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.845,
            "pendingQtyWeight": 1,
            "materialGroup1": "K01",
            "netPriceConditionRate": 23500,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 1000,
            "pendingGiQtyTon": 0.845,
            "weightUnit": "TON",
            "grossWeightTon": 0.845,
            "netWeightTon": 0.845,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000080",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-150D0930117N",
            "matDesc": "CA- 150D-93 DIA117 N",
            "plant": "7521",
            "saleUnit": "ROL",
            "netWeight": 0.719,
            "netWeightUnit": "TON",
            "netPrice": 22700,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 16321.3,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 719,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 719,
            "pendingQty": 1,
            "pendingQtyBase": 719,
            "contractPI": "0410001356",
            "contractPIItemNo": "000060",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.719,
            "pendingQtyWeight": 0.719,
            "materialGroup1": "K01",
            "netPriceConditionRate": 22700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 719,
            "pendingGiQtyTon": 0.719,
            "weightUnit": "TON",
            "grossWeightTon": 0.719,
            "netWeightTon": 0.719,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289752",
            "itemNo": "000090",
            "materialPricingGroup": "02",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-150D0980117N",
            "matDesc": "CA- 150D-98 DIA117N",
            "plant": "7521",
            "saleUnit": "ROL",
            "netWeight": 0.695,
            "netWeightUnit": "TON",
            "netPrice": 22700,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 15776.5,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 695,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 695,
            "pendingQty": 1,
            "pendingQtyBase": 695,
            "contractPI": "0410001356",
            "contractPIItemNo": "000060",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.695,
            "pendingQtyWeight": 0.695,
            "materialGroup1": "K01",
            "netPriceConditionRate": 22700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 695,
            "pendingGiQtyTon": 0.695,
            "weightUnit": "TON",
            "grossWeightTon": 0.695,
            "netWeightTon": 0.695,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289753",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D0980117N",
            "matDesc": "CA- 125D-98 / 38 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.802,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17403.4,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 802,
            "confirmQty": 1,
            "confirmQtyBase": 802,
            "pendingQty": 1,
            "pendingQtyBase": 802,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.802,
            "pendingQtyWeight": 0.802,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 802,
            "pendingGiQtyTon": 0.802,
            "weightUnit": "TON",
            "grossWeightTon": 0.802,
            "netWeightTon": 0.802,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289753",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1180117N",
            "matDesc": "CA- 125D-118 / 46 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.883,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 19161.1,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 883,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 883,
            "pendingQty": 1,
            "pendingQtyBase": 883,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.883,
            "pendingQtyWeight": 0.883,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 883,
            "pendingGiQtyTon": 0.883,
            "weightUnit": "TON",
            "grossWeightTon": 0.883,
            "netWeightTon": 0.883,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289754",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-185D1030117N",
            "matDesc": "CA-185D-103 DIA117N FSC Mix70%",
            "plant": "7581",
            "saleUnit": "ROL",
            "netWeight": 0.806,
            "netWeightUnit": "TON",
            "netPrice": 23700,
            "priceCurrency": "THB",
            "shippingPoint": 7505,
            "netValue": 19102.2,
            "firstDeliveryDT": "31/05/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 806,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 806,
            "pendingQty": 1,
            "pendingQtyBase": 806,
            "contractPI": "0410001303",
            "contractPIItemNo": "000040",
            "shiptToPODate": "14/03/2024",
            "orderQtyWeight": 0.806,
            "pendingQtyWeight": 0.806,
            "materialGroup1": "K01",
            "netPriceConditionRate": 23700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 806,
            "pendingGiQtyTon": 0.806,
            "weightUnit": "TON",
            "grossWeightTon": 0.806,
            "netWeightTon": 0.806,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289756",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D0980117N",
            "matDesc": "CA- 125D-98 / 38 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.802,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17403.4,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 802,
            "confirmQty": 1,
            "confirmQtyBase": 802,
            "pendingQty": 1,
            "pendingQtyBase": 802,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.802,
            "pendingQtyWeight": 0.802,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 802,
            "pendingGiQtyTon": 0.802,
            "weightUnit": "TON",
            "grossWeightTon": 0.802,
            "netWeightTon": 0.802,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289756",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1180117N",
            "matDesc": "CA- 125D-118 / 46 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.883,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 19161.1,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 883,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 883,
            "pendingQty": 1,
            "pendingQtyBase": 883,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.883,
            "pendingQtyWeight": 0.883,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 883,
            "pendingGiQtyTon": 0.883,
            "weightUnit": "TON",
            "grossWeightTon": 0.883,
            "netWeightTon": 0.883,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289757",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D0980117N",
            "matDesc": "CA- 125D-98 / 38 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.802,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17403.4,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 802,
            "confirmQty": 1,
            "confirmQtyBase": 802,
            "pendingQty": 1,
            "pendingQtyBase": 802,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.802,
            "pendingQtyWeight": 0.802,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 802,
            "pendingGiQtyTon": 0.802,
            "weightUnit": "TON",
            "grossWeightTon": 0.802,
            "netWeightTon": 0.802,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289757",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1180117N",
            "matDesc": "CA- 125D-118 / 46 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.883,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 19161.1,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 883,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 883,
            "pendingQty": 1,
            "pendingQtyBase": 883,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.883,
            "pendingQtyWeight": 0.883,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 883,
            "pendingGiQtyTon": 0.883,
            "weightUnit": "TON",
            "grossWeightTon": 0.883,
            "netWeightTon": 0.883,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289758",
            "itemNo": "000010",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D0980117N",
            "matDesc": "CA- 125D-98 / 38 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.802,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 17403.4,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 802,
            "confirmQty": 1,
            "confirmQtyBase": 802,
            "pendingQty": 1,
            "pendingQtyBase": 802,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.802,
            "pendingQtyWeight": 0.802,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 802,
            "pendingGiQtyTon": 0.802,
            "weightUnit": "TON",
            "grossWeightTon": 0.802,
            "netWeightTon": 0.802,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0410289758",
            "itemNo": "000020",
            "materialPricingGroup": "01",
            "itemCategory": "ZTAN",
            "status": "A",
            "matNo": "Z02CA-125D1180117N",
            "matDesc": "CA- 125D-118 / 46 INCH DIA117 N",
            "plant": "7561",
            "saleUnit": "ROL",
            "netWeight": 0.883,
            "netWeightUnit": "TON",
            "netPrice": 21700,
            "priceCurrency": "THB",
            "shippingPoint": 7503,
            "netValue": 19161.1,
            "firstDeliveryDT": "09/04/2024",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 883,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 883,
            "pendingQty": 1,
            "pendingQtyBase": 883,
            "contractPI": "0410001434",
            "contractPIItemNo": "000010",
            "productionInfo": "Production Information",
            "shiptToPODate": "09/04/2024",
            "orderQtyWeight": 0.883,
            "pendingQtyWeight": 0.883,
            "materialGroup1": "K01",
            "netPriceConditionRate": 21700,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 883,
            "pendingGiQtyTon": 0.883,
            "weightUnit": "TON",
            "grossWeightTon": 0.883,
            "netWeightTon": 0.883,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
        {
            "sdDoc": "0412121984",
            "itemNo": "000010",
            "materialPricingGroup": "02",
            "itemCategory": "ZBVN",
            "status": "A",
            "matNo": "Z02EK-080D1090102N",
            "matDesc": "EK- 80D-109 DIA102 N",
            "plant": "7521",
            "saleUnit": "ROL",
            "netWeight": 1.21,
            "netWeightUnit": "TON",
            "netPrice": 2166,
            "priceCurrency": "THB",
            "shippingPoint": 7501,
            "netValue": 2620.86,
            "firstDeliveryDT": "05/11/2023",
            "baseUnit": "KG",
            "orderQty": 1,
            "orderQtyBase": 1210,
            "nonConfirmQty": 1,
            "nonConfirmQtyBase": 1210,
            "pendingQty": 1,
            "pendingQtyBase": 1210,
            "contractPI": "0410001240",
            "contractPIItemNo": "000010",
            "orderQtyWeight": 1.21,
            "pendingQtyWeight": 1.21,
            "materialGroup1": "K01",
            "netPriceConditionRate": 2166,
            "pendingGiQty": 1,
            "pendingGiQtyBase": 1210,
            "pendingGiQtyTon": 1.21,
            "weightUnit": "TON",
            "grossWeightTon": 1.21,
            "netWeightTon": 1.21,
            "weightUnitTon": "TON",
            "priceUnit": " 1",
        },
    ],
}
