ES_26_GET_SALE_ORDER_API_SUCCESS_RESPONSE = {
    "piMessageId": "XXX",
    "status": "success",
    "data": [
        {
            "orderHeaderIn": {
                "saleDocument": "0043947141",
                "docType": "ZP30",
                "salesOrg": "0256",
                "distributionChannel": "10",
                "division": "00",
                "reqDate": "06/10/2023",
                "incoterms1": "CFR",
                "incoterms2": "โรงงานปาดังเบซาร์ สะเดา",
                "paymentTerms": "NT30",
                "poNo": "314/15694",
                "priceDate": "06/10/2023",
                "createDate": "02/10/2023",
                "customerGroup": "09",
                "salesDistrict": "P00055",
                "shippingCondition": "01",
                "salesGroup": "T37",
                "salesOff": "T003",
                "orderReason": "",
                "exchangeRate": 1,
                "orderAmtBeforeVat": 23000,
                "orderAmtVat": 1610,
                "orderAmtAfterVat": 24610,
                "currency": "THB",
                "priceGroup": "03",
            },
            "dp": [{"dpNo": "0038049446"}],
            "billing": [{"billingNo": "0032429744"}],
            "orderPartners": [
                {
                    "partnerRole": "WE",
                    "partnerNo": "0001011222",
                    "addrLink": "0000038115",
                    "itemNo": "000010",
                    "address": [
                        {
                            "addrNo": "0000038115",
                            "name": "บจก. กลุ่มสยามบรรจุภัณฑ์-TCCB",
                            "city": "จ.ชลบุรี",
                            "postCode": "20110",
                            "district": "อ.ศรีราชา",
                            "street": "321/9 ม.6 ต.สุรศักดิ์",
                            "transpzone": "20",
                            "country": "TH",
                            "telNoList": [{"telNo": "038-338500-1"}],
                        }
                    ],
                },
                {
                    "partnerRole": "AG",
                    "partnerNo": "0001007971",
                    "addrLink": "0000187433",
                    "address": [
                        {
                            "addrNo": "0000187433",
                            "name": "บริษัท ควอลิตี้คอยส์อินดัสตรี้ส์",
                            "name2": "(พี.บี.) จำกัด",
                            "city": "จังหวัดสงขลา",
                            "postCode": "90240",
                            "district": "ตำบลปาดังเบซาร์ อำเภอสะเดา",
                            "street": "333 ถนนปาดังเบซาร์",
                            "transpzone": "90",
                            "country": "TH",
                            "telNoList": [{"telNo": "74521465"}],
                            "faxNo": "074-521530",
                            "language": "2",
                        }
                    ],
                },
                {
                    "partnerRole": "AU",
                    "partnerNo": "10009291",
                    "address": [{"name": "นาย วุฒิพงศ์ จันทร์ศรีนวล"}],
                },
                {
                    "partnerRole": "RE",
                    "partnerNo": "0001007971",
                    "addrLink": "0000187433",
                    "address": [
                        {
                            "addrNo": "0000187433",
                            "name": "บริษัท ควอลิตี้คอยส์อินดัสตรี้ส์",
                            "name2": "(พี.บี.) จำกัด",
                            "city": "จังหวัดสงขลา",
                            "postCode": "90240",
                            "district": "ตำบลปาดังเบซาร์ อำเภอสะเดา",
                            "street": "333 ถนนปาดังเบซาร์",
                            "transpzone": "90",
                            "country": "TH",
                            "telNoList": [{"telNo": "74521465"}],
                            "faxNo": "074-521530",
                            "language": "2",
                        }
                    ],
                },
                {
                    "partnerRole": "RG",
                    "partnerNo": "0001007971",
                    "addrLink": "0000187433",
                    "address": [
                        {
                            "addrNo": "0000187433",
                            "name": "บริษัท ควอลิตี้คอยส์อินดัสตรี้ส์",
                            "name2": "(พี.บี.) จำกัด",
                            "city": "จังหวัดสงขลา",
                            "postCode": "90240",
                            "district": "ตำบลปาดังเบซาร์ อำเภอสะเดา",
                            "street": "333 ถนนปาดังเบซาร์",
                            "transpzone": "90",
                            "country": "TH",
                            "telNoList": [{"telNo": "74521465"}],
                            "faxNo": "074-521530",
                            "language": "2",
                        }
                    ],
                },
                {
                    "partnerRole": "VE",
                    "partnerNo": "10049947",
                    "address": [{"name": "นาย ศุภโชค ไชยนาเคนทร์"}],
                },
                {
                    "partnerRole": "WE",
                    "partnerNo": "0001007971",
                    "addrLink": "0000187433",
                    "address": [
                        {
                            "addrNo": "0000187433",
                            "name": "บริษัท ควอลิตี้คอยส์อินดัสตรี้ส์",
                            "name2": "(พี.บี.) จำกัด",
                            "city": "จังหวัดสงขลา",
                            "postCode": "90240",
                            "district": "ตำบลปาดังเบซาร์ อำเภอสะเดา",
                            "street": "333 ถนนปาดังเบซาร์",
                            "transpzone": "90",
                            "country": "TH",
                            "telNoList": [{"telNo": "74521465"}],
                            "faxNo": "074-521530",
                            "language": "2",
                        }
                    ],
                },
            ],
            "orderItems": [
                {
                    "itemNo": "000010",
                    "material": "Z035115109",
                    "materialDesc": "QCICO ARS PLUS MOSQUITO COIL8 (LO-00-CC",
                    "poSubcontract": "6036000669",
                    "itemQty": 1000,
                    "salesUnit": "ST",
                    "plant": "256B",
                    "paymentTerm": "NT30",
                    "poNumber": "314/15694",
                    "itemCategory": "ZPS9",
                    "materialGroup2": "TSR",
                    "saleText1_th": "กล่อง ARS PLUS MOSQUITO COIL8 (LOW SMOKE",
                    "saleText2_th": ") LAVENDER",
                    "routeId": "900055",
                    "routeName": "สงขลา-สงขลา",
                    "requestedDate": "06/10/2023",
                    "orderQty": 1000,
                    "comfirmQty": 1000,
                    "deliveryQty": 1000,
                    "deliveryStatus": "C",
                    "saleQtyDivision": 1,
                    "saleQtyFactor": 1,
                    "prdHierachy": "03SO999999",
                    "shippingPoint": "2561",
                    "poDates": "02/10/2023",
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "ST",
                    "shiptToPODate": "06/10/2023",
                    "weightUnit": "KG",
                    "weightUnitTon": "TON",
                    "materialType": "84",
                    "bomFlag": "X",
                    "priceDate": "06/10/2023",
                    "baseUnit": "ST",
                    "shipToItemNumber": "C",
                    "poItemNo": "30",
                    "saleText3_th": "saleText3_th",
                    "saleText4_th": "saleText4_th",
                },
                {
                    "itemNo": "000020",
                    "material": "Z035109160",
                    "materialDesc": "QCICO ARS PLUS MOSQUITO COIL8 (LO-00",
                    "itemQty": 1000,
                    "salesUnit": "PC",
                    "plant": "256B",
                    "paymentTerm": "NT30",
                    "poNumber": "314/15694",
                    "itemCategory": "ZPS1",
                    "materialGroup2": "TSR",
                    "saleText1_th": "กล่อง ARS PLUS MOSQUITO COIL8 (LOW SMOKE",
                    "saleText2_th": ") LAVENDER",
                    "routeId": "900055",
                    "routeName": "สงขลา-สงขลา",
                    "requestedDate": "06/10/2023",
                    "weightPerUnit": 595,
                    "orderQty": 1000,
                    "comfirmQty": 1000,
                    "deliveryQty": 1000,
                    "deliveryStatus": "C",
                    "saleQtyDivision": 1000,
                    "saleQtyFactor": 595,
                    "prdHierachy": "03SO999999E249",
                    "shippingPoint": "2561",
                    "poDates": "02/10/2023",
                    "netPrice": 20,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "PC",
                    "shiptToPODate": "06/10/2023",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.595,
                    "netWeightTon": 0.595,
                    "weightUnitTon": "TON",
                    "materialType": "81",
                    "bomFlag": "X",
                    "priceDate": "06/10/2023",
                    "netPricePerUnit": 20,
                    "netWeight": 595,
                    "grossWeight": 595,
                    "baseUnit": "KG",
                    # "parentItemNo": "000010"
                },
                {
                    "itemNo": "000030",
                    "material": "Z035115108",
                    "materialDesc": "QCICO แผ่นรอง ARS PLUS MOSQUITO COIL8-60",
                    "itemQty": 2000,
                    "salesUnit": "PC",
                    "plant": "256B",
                    "paymentTerm": "NT30",
                    "poNumber": "314/15694",
                    "itemCategory": "ZPS1",
                    "materialGroup2": "TSR",
                    "saleText1_th": "แผ่นรอง ARS PLUS MOSQUITO COIL8 (LOW SMO",
                    "saleText2_th": "KE) LAVENDER (C-ARS-LS-LA-03)",
                    "routeId": "900055",
                    "routeName": "สงขลา-สงขลา",
                    "requestedDate": "06/10/2023",
                    "weightPerUnit": 86,
                    "orderQty": 2000,
                    "comfirmQty": 2000,
                    "deliveryQty": 2000,
                    "deliveryStatus": "C",
                    "saleQtyDivision": 1000,
                    "saleQtyFactor": 43,
                    "prdHierachy": "03RD9999990559",
                    "shippingPoint": "2561",
                    "poDates": "02/10/2023",
                    "netPrice": 1.5,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "PC",
                    "shiptToPODate": "06/10/2023",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.086,
                    "netWeightTon": 0.086,
                    "weightUnitTon": "TON",
                    "materialType": "81",
                    "bomFlag": "X",
                    "priceDate": "06/10/2023",
                    "netPricePerUnit": 1.5,
                    "netWeight": 86,
                    "grossWeight": 86,
                    "baseUnit": "KG",
                    "parentItemNo": "000010",
                },
                {
                    "itemNo": "000040",
                    "material": "Z035115108",
                    "materialDesc": "QCICO แผ่นรอง ARS PLUS MOSQUITO COIL8-60",
                    "itemQty": 2000,
                    "salesUnit": "PC",
                    "plant": "256B",
                    "paymentTerm": "NT30",
                    "poNumber": "314/15694",
                    "itemCategory": "ZPS1",
                    "materialGroup2": "TSR",
                    "saleText1_th": "แผ่นรอง ARS PLUS MOSQUITO COIL8 (LOW SMO",
                    "saleText2_th": "KE) LAVENDER (C-ARS-LS-LA-03)",
                    "routeId": "900055",
                    "routeName": "สงขลา-สงขลา",
                    "requestedDate": "06/10/2023",
                    "weightPerUnit": 86,
                    "orderQty": 2000,
                    "comfirmQty": 2000,
                    "deliveryQty": 2000,
                    "deliveryStatus": "C",
                    "saleQtyDivision": 1000,
                    "saleQtyFactor": 43,
                    "prdHierachy": "03RD9999990559",
                    "shippingPoint": "2561",
                    "poDates": "02/10/2023",
                    "netPrice": 1.5,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "PC",
                    "shiptToPODate": "06/10/2023",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.086,
                    "netWeightTon": 0.086,
                    "weightUnitTon": "TON",
                    "materialType": "81",
                    "bomFlag": "X",
                    "priceDate": "06/10/2023",
                    "netPricePerUnit": 1.5,
                    "netWeight": 86,
                    "grossWeight": 86,
                    "baseUnit": "KG",
                    "parentItemNo": "000010",
                },
                {
                    "itemNo": "000050",
                    "material": "Z035115108",
                    "materialDesc": "QCICO แผ่นรอง ARS PLUS MOSQUITO COIL8-60",
                    "itemQty": 2000,
                    "salesUnit": "PC",
                    "plant": "256B",
                    "paymentTerm": "NT30",
                    "poNumber": "314/15694",
                    "itemCategory": "ZPS1",
                    "materialGroup2": "TSR",
                    "saleText1_th": "แผ่นรอง ARS PLUS MOSQUITO COIL8 (LOW SMO",
                    "saleText2_th": "KE) LAVENDER (C-ARS-LS-LA-03)",
                    "routeId": "900055",
                    "routeName": "สงขลา-สงขลา",
                    "requestedDate": "06/10/2023",
                    "weightPerUnit": 86,
                    "orderQty": 2000,
                    "comfirmQty": 2000,
                    "deliveryQty": 2000,
                    "deliveryStatus": "C",
                    "saleQtyDivision": 1000,
                    "saleQtyFactor": 43,
                    "prdHierachy": "03RD9999990559",
                    "shippingPoint": "2561",
                    "poDates": "02/10/2023",
                    "netPrice": 1.5,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "PC",
                    "shiptToPODate": "06/10/2023",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.086,
                    "netWeightTon": 0.086,
                    "weightUnitTon": "TON",
                    "materialType": "81",
                    "bomFlag": "X",
                    "priceDate": "06/10/2023",
                    "netPricePerUnit": 1.5,
                    "netWeight": 86,
                    "grossWeight": 86,
                    "baseUnit": "KG",
                    "parentItemNo": "000020",
                },
            ],
            "orderCondition": [
                {
                    "itemNo": "000020",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "currency": "%",
                    "conditionPriceOrder": 1400,
                    "conditionBaseValue": 20000,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "VPRS",
                    "conditionRate": 33281.93,
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionPriceOrder": 19802.75,
                    "conditionBaseValue": 595,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "ZPP1",
                    "conditionRate": 20,
                    "currency": "THB",
                    "conditionUnit": "PC",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 20000,
                    "conditionBaseValue": 1000,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "currency": "%",
                    "conditionPriceOrder": 210,
                    "conditionBaseValue": 3000,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "VPRS",
                    "conditionRate": 32364.28,
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionPriceOrder": 2783.33,
                    "conditionBaseValue": 86,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "ZPP1",
                    "conditionRate": 1.5,
                    "currency": "THB",
                    "conditionUnit": "PC",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 3000,
                    "conditionBaseValue": 2000,
                },
            ],
            "orderText": [
                {
                    "ItemNo": "000010",
                    "textId": "Z001",
                    "language": "TH",
                    "textLine": [{"text": "item level internal com to war"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "Z002",
                    "language": "TH",
                    "textLine": [{"text": "item level external com to cus"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "Z004",
                    "language": "TH",
                    "textLine": [{"text": "item level remark"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "0002",
                    "language": "TH",
                    "textLine": [{"text": "item note cip"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "Z021",
                    "language": "TH",
                    "textLine": [{"text": "PR item text"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "ZG23",
                    "language": "TH",
                    "textLine": [{"text": "Lot no"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "0006",
                    "language": "TH",
                    "textLine": [{"text": "Production memo"}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [
                        {"text": "กล่อง ARS PLUS MOSQUITO COIL8 (LOW SMOKE"},
                        {"text": ") LAVENDER"},
                    ],
                },
                {
                    "ItemNo": "000010",
                    "textId": "0001",
                    "language": "EN",
                    "textLine": [
                        {"text": "กล่อง ARS PLUS MOSQUITO COIL8 (LOW SMOKE"},
                        {"text": ") LAVENDER"},
                    ],
                },
                {
                    "ItemNo": "000020",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [
                        {"text": "กล่อง ARS PLUS MOSQUITO COIL8 (LOW SMOKE"},
                        {"text": ") LAVENDER"},
                    ],
                },
                {
                    "ItemNo": "000020",
                    "textId": "0001",
                    "language": "EN",
                    "textLine": [
                        {"text": "กล่อง ARS PLUS MOSQUITO COIL8 (LOW SMOKE"},
                        {"text": ") LAVENDER"},
                    ],
                },
                {
                    "ItemNo": "000020",
                    "textId": "Z081",
                    "language": "TH",
                    "textLine": [{"text": "C"}, {"text": "20231002/131344"}],
                },
                {
                    "ItemNo": "000030",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [
                        {"text": "แผ่นรอง ARS PLUS MOSQUITO COIL8 (LOW SMO"},
                        {"text": "KE) LAVENDER (C-ARS-LS-LA-03)"},
                    ],
                },
                {
                    "ItemNo": "000030",
                    "textId": "0001",
                    "language": "EN",
                    "textLine": [
                        {"text": "แผ่นรอง ARS PLUS MOSQUITO COIL8 (LOW SMO"},
                        {"text": "KE) LAVENDER (C-ARS-LS-LA-03)"},
                    ],
                },
                {
                    "ItemNo": "000030",
                    "textId": "Z081",
                    "language": "TH",
                    "textLine": [{"text": "C"}, {"text": "20231002/131344"}],
                },
            ],
            "orderSchedulesIn": [
                {
                    "itemNo": "000010",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "CT",
                    "reqDate": "06/10/2023",
                    "reqQty": 1000,
                    "confirmQty": 1000,
                },
                {
                    "itemNo": "000020",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "CN",
                    "reqDate": "06/10/2023",
                    "reqQty": 1000,
                    "confirmQty": 1000,
                },
                {
                    "itemNo": "000030",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "CN",
                    "reqDate": "06/10/2023",
                    "reqQty": 2000,
                    "confirmQty": 2000,
                },
            ],
        }
    ],
}

ES_26_API_SUCCESS_RESPONSE_CIP_TEST = {
    "piMessageId": "18228258241871533100749353064527736666",
    "status": "success",
    "data": [
        {
            "orderHeaderIn": {
                "saleDocument": "0410287890",
                "docType": "ZOR",
                "salesOrg": "0750",
                "distributionChannel": "10",
                "division": "00",
                "reqDate": "14/11/2023",
                "incoterms1": "CFR",
                "incoterms2": "อ.เมือง จ.ปทุมธานี",
                "paymentTerms": "NT60",
                "poNo": "test it1",
                "priceGroup": "03",
                "priceDate": "14/11/2023",
                "createDate": "14/11/2023",
                "customerGroup": "37",
                "salesDistrict": "075002",
                "shippingCondition": "01",
                "salesGroup": "75E",
                "salesOff": "0750",
                "orderReason": "",
                "exchangeRate": 1,
                "orderAmtBeforeVat": 10894,
                "orderAmtVat": 762.58,
                "orderAmtAfterVat": 11656.58,
                "currency": "THB",
                "contractNo": "0410001383",
                "unloadingPoint": "หน้าร้าน",
            },
            "dp": [{"dpNo": "0414666533"}],
            "orderPartners": [
                {
                    "partnerRole": "AG",
                    "partnerNo": "0001002895",
                    "addrLink": "0000080913",
                    "onetimeFlag": "X",
                    "address": [
                        {
                            "addrNo": "0000080913",
                            "name": "บจก. กระดาษรุ่งโรจน์-Edit",
                            "name2": "TEST",
                            "city": "จ.ปทุมธานี",
                            "postCode": "12000",
                            "district": "ต.บางขะแยง อ.เมือง",
                            "street": "39/11 ม.1",
                            "transpzone": "12",
                            "country": "TH",
                            "telNoList": [{"telNo": "5813254-5"}],
                        }
                    ],
                },
                {
                    "partnerRole": "AP",
                    "partnerNo": "0000032693",
                    "addrLink": "0000080916",
                    "address": [
                        {
                            "addrNo": "0000080916",
                            "name": "คุณสมศรี เมฆธน",
                            "country": "TH",
                            "telNoList": [{"telNo": "689-8155"}],
                        }
                    ],
                },
                {
                    "partnerRole": "AU",
                    "partnerNo": "00000105",
                    "address": [{"name": "EMP105 last curr 4 EMP105 firstC 4"}],
                },
                {
                    "partnerRole": "RE",
                    "partnerNo": "0001002895",
                    "addrLink": "0000080913",
                    "address": [
                        {
                            "addrNo": "0000080913",
                            "name": "บจก. กระดาษรุ่งโรจน์-Edit",
                            "name2": "TEST",
                            "city": "จ.ปทุมธานี",
                            "postCode": "12000",
                            "district": "ต.บางขะแยง อ.เมือง",
                            "street": "39/11 ม.1",
                            "transpzone": "12",
                            "country": "TH",
                            "telNoList": [{"telNo": "5813254-5"}],
                        }
                    ],
                },
                {
                    "partnerRole": "RG",
                    "partnerNo": "0001002895",
                    "addrLink": "0000080913",
                    "address": [
                        {
                            "addrNo": "0000080913",
                            "name": "บจก. กระดาษรุ่งโรจน์-Edit",
                            "name2": "TEST",
                            "city": "จ.ปทุมธานี",
                            "postCode": "12000",
                            "district": "ต.บางขะแยง อ.เมือง",
                            "street": "39/11 ม.1",
                            "transpzone": "12",
                            "country": "TH",
                            "telNoList": [{"telNo": "5813254-5"}],
                        }
                    ],
                },
                {
                    "partnerRole": "VE",
                    "partnerNo": "00000105",
                    "address": [{"name": "EMP105 last curr 4 EMP105 firstC 4"}],
                },
                {
                    "partnerRole": "WE",
                    "partnerNo": "0001002895",
                    "addrLink": "0000080913",
                    "address": [
                        {
                            "addrNo": "0000080913",
                            "name": "บจก. กระดาษรุ่งโรจน์-Edit",
                            "name2": "TEST",
                            "city": "จ.ปทุมธานี",
                            "postCode": "12000",
                            "district": "ต.บางขะแยง อ.เมือง",
                            "street": "39/11 ม.1",
                            "transpzone": "12",
                            "country": "TH",
                            "telNoList": [{"telNo": "5813254-5"}],
                        }
                    ],
                },
            ],
            "orderItems": [
                {
                    "itemNo": "000010",
                    "material": "Z02RFMD0284",
                    "materialDesc": "RKI125D-108x98 RRK",
                    "itemQty": 1,
                    "salesUnit": "RM",
                    "plant": "7524",
                    "paymentTerm": "NT60",
                    "poNumber": "test it1",
                    "itemCategory": "ZKS3",
                    "materialGroup1": "K02",
                    "purchaseNo": "1042002091",
                    "poSubcontract": "6036000669",
                    "saleText1_th": "กระดาษรีม RKI125D-108x98",
                    "saleText2_th": "RRK",
                    "routeId": "120008",
                    "routeName": "ปทุมธานี-ปทุมธานี",
                    "requestedDate": "14/11/2023",
                    "deliveryTolOver": 10,
                    "weightPerUnit": 66.15,
                    "orderQty": 1,
                    "comfirmQty": 1,
                    "deliveryQty": 1,
                    "deliveryStatus": "C",
                    "status": "C",
                    "saleQtyDivision": 100,
                    "saleQtyFactor": 6615,
                    "prdHierachy": "0220RC KI 125",
                    "shippingPoint": "7509",
                    "contractNo": "0410001383",
                    "contractItemNo": "000010",
                    "netPrice": 1692,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "RM",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.066,
                    "netWeightTon": 0.066,
                    "weightUnitTon": "TON",
                    "prItem": "00001",
                    "materialType": "84",
                    "bomFlag": "X",
                    "priceDate": "06/10/2023",
                    "baseUnit": "ST",
                },
                {
                    "itemNo": "000020",
                    "material": "Z02RFMD0285",
                    "materialDesc": "RKI125D-108x95 RRK",
                    "itemQty": 2,
                    "salesUnit": "RM",
                    "plant": "7524",
                    "paymentTerm": "NT60",
                    "poNumber": "test it1",
                    "itemCategory": "ZKS3",
                    "materialGroup1": "K02",
                    "purchaseNo": "1042002091",
                    "poSubcontract": "6036000669",
                    "saleText1_th": "กระดาษรีม RKI125D-108x95",
                    "saleText2_th": "RRK",
                    "routeId": "120008",
                    "routeName": "ปทุมธานี-ปทุมธานี",
                    "requestedDate": "14/11/2023",
                    "deliveryTolOver": 10,
                    "weightPerUnit": 128.26,
                    "orderQty": 2,
                    "comfirmQty": 2,
                    "deliveryQty": 2,
                    "deliveryStatus": "C",
                    "status": "C",
                    "saleQtyDivision": 100,
                    "saleQtyFactor": 6413,
                    "prdHierachy": "0220RC KI 150",
                    "shippingPoint": "7509",
                    "contractNo": "0410001383",
                    "contractItemNo": "000020",
                    "netPrice": 1633,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "RM",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.128,
                    "netWeightTon": 0.128,
                    "weightUnitTon": "TON",
                    "prItem": "00002",
                    "materialType": "84",
                    "bomFlag": "X",
                    "parentItemNo": "000010",
                    "priceDate": "06/10/2023",
                    "baseUnit": "ST",
                },
                {
                    "itemNo": "000030",
                    "material": "Z02RPSD0191",
                    "materialDesc": "RTI125D-108x69 RRK",
                    "itemQty": 2,
                    "salesUnit": "RM",
                    "plant": "7524",
                    "paymentTerm": "NT60",
                    "poNumber": "test it1",
                    "itemCategory": "ZKS3",
                    "materialGroup1": "K02",
                    "purchaseNo": "1042002091",
                    "poSubcontract": "6036000669",
                    "saleText1_th": "กระดาษรีม RTI125D-108x69",
                    "saleText2_th": "RRK",
                    "routeId": "120008",
                    "routeName": "ปทุมธานี-ปทุมธานี",
                    "requestedDate": "15/11/2023",
                    "deliveryTolOver": 10,
                    "weightPerUnit": 93.16,
                    "orderQty": 2,
                    "comfirmQty": 2,
                    "deliveryQty": 2,
                    "deliveryStatus": "A",
                    "status": "A",
                    "saleQtyDivision": 100,
                    "saleQtyFactor": 4658,
                    "prdHierachy": "0220RC TI 125",
                    "shippingPoint": "7509",
                    "contractNo": "0410001383",
                    "contractItemNo": "000030",
                    "netPrice": 1261,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "RM",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.093,
                    "netWeightTon": 0.093,
                    "weightUnitTon": "TON",
                    "prItem": "00003",
                    "bomFlag": "X",
                    "parentItemNo": "000010",
                    "priceDate": "06/10/2023",
                    "baseUnit": "ST",
                },
                {
                    "itemNo": "000040",
                    "material": "Z02RPSD0189",
                    "materialDesc": "RSB110D-79x109 RRK",
                    "itemQty": 3,
                    "salesUnit": "RM",
                    "plant": "7524",
                    "paymentTerm": "NT60",
                    "poNumber": "test it1",
                    "itemCategory": "ZKS3",
                    "materialGroup1": "K02",
                    "purchaseNo": "1042002091",
                    "poSubcontract": "6036000669",
                    "saleText1_th": "กระดาษรีม RSB110D-79x109",
                    "saleText2_th": "RRK",
                    "routeId": "120008",
                    "routeName": "ปทุมธานี-ปทุมธานี",
                    "requestedDate": "18/11/2023",
                    "deliveryTolOver": 10,
                    "weightPerUnit": 142.08,
                    "orderQty": 3,
                    "comfirmQty": 2,
                    "deliveryQty": 2,
                    "deliveryStatus": "B",
                    "status": "B",
                    "saleQtyDivision": 100,
                    "saleQtyFactor": 4736,
                    "prdHierachy": "0220RC SB 110",
                    "shippingPoint": "7509",
                    "contractNo": "0410001383",
                    "contractItemNo": "000040",
                    "netPrice": 1138,
                    "priceCurrency": "THB",
                    "conditionPricingUnit": 1,
                    "unitCondition": "RM",
                    "weightUnit": "KG",
                    "grossWeightTon": 0.142,
                    "netWeightTon": 0.142,
                    "weightUnitTon": "TON",
                    "prItem": "00004",
                },
            ],
            "orderCondition": [
                {
                    "itemNo": "000010",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "currency": "%",
                    "conditionPriceOrder": 118.44,
                    "conditionBaseValue": 1692,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "VPRS",
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionBaseValue": 66.15,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD1",
                    "currency": "%",
                    "conditionBaseValue": 1942,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD2",
                    "conditionRate": -250,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": -250,
                    "conditionBaseValue": 1,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD3",
                    "currency": "%",
                    "conditionBaseValue": 1692,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 1,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 1000,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "ZN00",
                    "conditionRate": 1692,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 1692,
                    "conditionBaseValue": 1,
                },
                {
                    "itemNo": "000010",
                    "conditionType": "ZPR1",
                    "conditionRate": 1942,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 1942,
                    "conditionBaseValue": 1,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "currency": "%",
                    "conditionPriceOrder": 228.62,
                    "conditionBaseValue": 3266,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "VPRS",
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionBaseValue": 128.26,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "YKD1",
                    "currency": "%",
                    "conditionBaseValue": 3768,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "YKD2",
                    "conditionRate": -251,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": -502,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "YKD3",
                    "currency": "%",
                    "conditionBaseValue": 3266,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 2000,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "ZN00",
                    "conditionRate": 1633,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 3266,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000020",
                    "conditionType": "ZPR1",
                    "conditionRate": 1884,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 3768,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "currency": "%",
                    "conditionPriceOrder": 176.54,
                    "conditionBaseValue": 2522,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "VPRS",
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionBaseValue": 93.16,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "YKD1",
                    "currency": "%",
                    "conditionBaseValue": 3026,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "YKD2",
                    "conditionRate": -252,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": -504,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "YKD3",
                    "currency": "%",
                    "conditionBaseValue": 2522,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 2000,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "ZN00",
                    "conditionRate": 1261,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 2522,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000030",
                    "conditionType": "ZPR1",
                    "conditionRate": 1513,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 3026,
                    "conditionBaseValue": 2,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "MWST",
                    "conditionRate": 7,
                    "currency": "%",
                    "conditionPriceOrder": 238.98,
                    "conditionBaseValue": 3414,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "VPRS",
                    "currency": "THB",
                    "conditionUnit": "KG",
                    "conditionPriceUnit": 1000,
                    "conditionBaseValue": 142.08,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "YKD1",
                    "currency": "%",
                    "conditionBaseValue": 4173,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "YKD2",
                    "conditionRate": -253,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": -759,
                    "conditionBaseValue": 3,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "YKD3",
                    "currency": "%",
                    "conditionBaseValue": 3414,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "YKD4",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 3,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "ZKD7",
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionBaseValue": 3000,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "ZN00",
                    "conditionRate": 1138,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 3414,
                    "conditionBaseValue": 3,
                },
                {
                    "itemNo": "000040",
                    "conditionType": "ZPR1",
                    "conditionRate": 1391,
                    "currency": "THB",
                    "conditionUnit": "RM",
                    "conditionPriceUnit": 1,
                    "conditionPriceOrder": 4173,
                    "conditionBaseValue": 3,
                },
            ],
            "orderText": [
                {
                    "ItemNo": "000000",
                    "textId": "Z001",
                    "language": "EN",
                    "textLine": [{"text": "SB110ส่งม้วนสีเก่าในQI-115"}],
                },
                {
                    "ItemNo": "000000",
                    "textId": "Z014",
                    "language": "EN",
                    "textLine": [{"text": "ANY THAILAND PORTS AT THE SELLER'S OPTION"}],
                },
                {
                    "ItemNo": "000000",
                    "textId": "Z015",
                    "language": "EN",
                    "textLine": [
                        {
                            "text": "PACKING: GOODS ARE IN STANDARD EXPORT PACKING FCL/FCL CONT."
                        }
                    ],
                },
                {
                    "ItemNo": "000000",
                    "textId": "Z056",
                    "language": "EN",
                    "textLine": [
                        {"text": "SIAM KRAFT INDUSTRY CO., LTD."},
                        {"text": "1 SIAM CEMENT ROAD BANGSUE"},
                        {"text": "BANGKOK 10800 THAILAND"},
                    ],
                },
                {
                    "ItemNo": "000000",
                    "textId": "Z056",
                    "language": "TH",
                    "textLine": [
                        {"text": "บริษัทสยามคราฟท์อุตสาหกรรม จำกัด"},
                        {"text": "1 ถ.ปูนซิเมนต์ไทย บางซื่อ"},
                        {"text": "กทม. 10800"},
                    ],
                },
                {
                    "ItemNo": "000000",
                    "textId": "Z067",
                    "language": "TH",
                    "textLine": [{"text": '" D/P & COA on Web e-Document "'}],
                },
                {
                    "ItemNo": "000000",
                    "textId": "ZK09",
                    "language": "EN",
                    "textLine": [{"text": "5"}, {"text": ""}],
                },
                {
                    "ItemNo": "000010",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [{"text": "กระดาษรีม RKI125D-108x98"}, {"text": "RRK"}],
                },
                {
                    "ItemNo": "000020",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [{"text": "กระดาษรีม RKI125D-108x95"}, {"text": "RRK"}],
                },
                {
                    "ItemNo": "000030",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [{"text": "กระดาษรีม RTI125D-108x69"}, {"text": "RRK"}],
                },
                {
                    "ItemNo": "000040",
                    "textId": "0001",
                    "language": "TH",
                    "textLine": [{"text": "กระดาษรีม RSB110D-79x109"}, {"text": "RRK"}],
                },
            ],
            "orderSchedulesIn": [
                {
                    "itemNo": "000010",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "ZC",
                    "reqDate": "14/11/2023",
                    "reqQty": 1,
                    "confirmQty": 1,
                },
                {
                    "itemNo": "000020",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "ZC",
                    "reqDate": "14/11/2023",
                    "reqQty": 2,
                    "confirmQty": 2,
                },
                {
                    "itemNo": "000030",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "ZC",
                    "reqDate": "15/11/2023",
                    "reqQty": 2,
                    "confirmQty": 2,
                },
                {
                    "itemNo": "000040",
                    "scheduleLine": "0001",
                    "scheduleLinecate": "ZC",
                    "reqDate": "18/11/2023",
                    "reqQty": 3,
                    "confirmQty": 2,
                },
            ],
        }
    ],
}
